### ISSUE TITLE
not able to run as a human

### ISSUE THREAD

**Issue by lcnature** [deepmind/lab#102]
Hello,
I have successfully installed deepmindlab in a conda environment with python=2.7 and all other required dependencies.
both `bazel build //:deepmind_lab.so` and `bazel test //python/tests:python_module_test` succeeded. 
However, when I tried to run `bazel run :game -- --level_script=tests/empty_room_test --level_setting=logToStdErr=true`, although a black window popped out with title "deepmindlab", it goes unresponding in a while, and the terminal shows:
```
INFO: Analysed target //:game (0 packages loaded).
INFO: Found 1 target...
Target //:game up-to-date:
  bazel-bin/game
INFO: Elapsed time: 0.400s, Critical Path: 0.10s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/game '--level_script=tests/empty_room_test' '--level_setting=logToStdErr=trueINFO: Build completed successfully, 1 total action
logToStdErr: "true"
----- Client Initialization -----
Couldn't read q3history.
----- Initializing Renderer ----
-------------------------------
QKEY building random string
QKEY generated
----- Client Initialization Complete -----
----- R_Init -----
SDL using driver "x11"
Initializing OpenGL display
Display aspect: 1.778
...setting mode -1: 640 480
Using 24 color bits, 24 depth, 8 stencil display.
X Error of failed request:  GLXUnsupportedPrivateRequest
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  16 (X_GLXVendorPrivate)
  Serial number of failed request:  170
  Current serial number in output stream:  171
```

If I run `bazel run //:python_random_agent`, it was able to say the job finished but there was a message of `Failed to get __file__ attribute.` during the output:
```
INFO: Analysed target //:python_random_agent (0 packages loaded).
INFO: Found 1 target...
Target //:python_random_agent up-to-date:
  bazel-bin/python_random_agent
INFO: Elapsed time: 0.300s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Failed to get __file__ attribute.
Starting random spring agent. Action spec: [{'max': 512, 'name': 'LOOK_LEFT_RIGHT_PIXELS_PER_FRAME', 'min': -512}, {'max': 512, 'name': 'LOOK_DOWN_UP_PIXELS_PER_FRAME', 'min': -512}, {'max': 1, 'name': 'STRAFE_LEFT_RIGHT', 'min': -1}, {'max': 1, 'name': 'MOVE_BACK_FORWARD', 'min': -1}, {'max': 1, 'name': 'FIRE', 'min': 0}, {'max': 1, 'name': 'JUMP', 'min': 0}, {'max': 1, 'name': 'CROUCH', 'min': 0}]
Finished after 1000 steps. Total reward received is 0.000000
```

Is there any clue what might be wrong?

Thanks!

**Comment by tkoeppe** [comment]
Several things:

* The `__file__` attribute warning is harmless -- the attribute is set when you build a PIP package, but it's not set (nor necessary) when you run directly via Bazel.

* The random agent doesn't have human controls.

* To see the random agent actions rendered visually, you need to link with the SDL output, e.g.:

        bazel run -c opt --define=graphics=sdl :python_random_agent

**Comment by tkoeppe** [comment]
If you want human controls, use the `:game` binary instead, e.g.:

    bazel run -c opt :game  -- --level_script=tests/empty_room_test
