### ISSUE TITLE
game screen  displays upside down.

### ISSUE THREAD

**Issue by rnunziata** [deepmind/lab#104]
game screen  displays upside down on lua test scripts.
When using human mode it display correctly.

Is there a setting for controlling this?

**Comment by tkoeppe** [comment]
There's no setting. This is the result of making the memory access more efficient internally, and it's surprisingly unobvious how one would make that tunable.

If it's any consolation, human vision is also upside down internally, so if you will, the agent sees the world "as it really is" :-)

**Comment by rnunziata** [comment]
lol..:-)
