### ISSUE TITLE
Initial Build Failing

### ISSUE THREAD

**Issue by kanishkg** [deepmind/lab#107]
Running the initial build with 
`lab$ bazel run :python_random_agent --define graphics=sdl -- \
               --length=10000 --width=640 --height=480`
throws the following error:
`WARNING: Output base '/home/kvg245/.cache/bazel/_bazel_kvg245/25a28887031a9683e83856dc6edb82bb' is on NFS. This may lead to surprising failures and undetermined behavior.`
`WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.`
`ERROR: /home/kvg245/RL/lab/BUILD:880:1: //:dmlab_graphics_sdl: no such attribute 'define_values' in 'config_setting' rule.`
`ERROR: /home/kvg245/RL/lab/BUILD:880:1: //:dmlab_graphics_sdl: missing value for mandatory attribute 'values' in 'config_setting' rule.`
`ERROR: /home/kvg245/RL/lab/BUILD:885:1: //:dmlab_graphics_osmesa_or_glx: no such attribute 'define_values' in 'config_setting' rule.`
`ERROR: /home/kvg245/RL/lab/BUILD:885:1: //:dmlab_graphics_osmesa_or_glx: missing value for mandatory attribute 'values' in 'config_setting' rule.`
`ERROR: /home/kvg245/RL/lab/BUILD:890:1: //:dmlab_graphics_osmesa_or_egl: no such attribute 'define_values' in 'config_setting' rule.`
`ERROR: /home/kvg245/RL/lab/BUILD:890:1: //:dmlab_graphics_osmesa_or_egl: missing value for mandatory attribute 'values' in 'config_setting' rule.`
`ERROR: error loading package '': Package '' contains errors.`
`INFO: Elapsed time: 4.742s`
`ERROR: Build failed. Not running target`

**Comment by tkoeppe** [comment]
a) Try `--define=graphics=sdl`

b) Are you using a relatively recent version of Bazel?

c) Does it work if you just omit the `--define` entirely?

**Comment by kanishkg** [comment]
a) Causes the same error
b) 0.4.5
c) Causes the same error

**Comment by tkoeppe** [comment]
As we are now on version 0.17.2, please upgrade and try again.
