### ISSUE TITLE
Snap package support (Feature/Enhancement)

### ISSUE THREAD

**Issue by Mikerr1111** [deepmind/lab#109]
I was thinking the setup and install process for Ubuntu and other Linux distros could be improved by having a [Snap package](https://snapcraft.io/) version. If it's not a priority would you mind if I implemented the snap?

[Creating a Snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

[Create snaps from your preferred programming language.](https://docs.snapcraft.io/build-snaps/languages)

[Linux distros with Snap support](https://docs.snapcraft.io/core/install)
![snap](https://user-images.githubusercontent.com/18353476/43989596-ec564800-9d01-11e8-89e6-8e0af1434f62.png)

**Comment by tkoeppe** [comment]
What would the outcome of such an installation be? Just the Python package? Or C++ headers + precompiled libraries? What would a typical user experience look like that uses this setup?

**Comment by tkoeppe** [comment]
Also, how would we unit-test that this system works? I have zero experience with Snap, so I'd definitely want some automatic assurance in perpetuity that this isn't getting broken.

**Comment by Mikerr1111** [comment]
Hi @tkoeppe, so the build and test setup for snaps is here https://snapcraft.io/build and the user experience can be seen in the snap store https://snapcraft.io/store.
![spotify](https://user-images.githubusercontent.com/18353476/47253817-ab653480-d40d-11e8-864f-09d9d36c90f1.png)

**Comment by tkoeppe** [comment]
OK, but assume that I know nothing about this, and I'm only the maintainer of this present repository. How does *this* codebase test the correctness of the proposed feature? I'm probably not going to go off an learn a new system and then figure out how to integrate it &ndash; that's where you come in: tell me in terms of *this* repo (i.e. in terms of Travis rules) how this would be tested.

But let's get back to the utility of this feature first. DeepMind Lab is mostly a library that's consumed by including headers and linking against it (and there's also a Python module built against a set of local package installations the user provides). Is Snap useful for this case?

**Comment by Mikerr1111** [comment]
Snap is probably not the best use for this case. Well, thank you for taking the time to talk to me and have a good day.
