### ISSUE TITLE
Comparison with ViZDoom

### ISSUE THREAD

**Issue by wjaskowski** [deepmind/lab#11]
Hi, here the [ViZDoom](https://github.com/Marqt/ViZDoom) project leader. As I did not find any contact information in the paper describing this framework (https://deepmind.com/documents/deepmind_lab.pdf), I decided to complain a little bit here. 

The paper says:

"Unlike in VizDoom, agents [in DeepMind Lab] can look up to the sky or down to the ground." 

The statement regarding ViZDoom is false. Proof: https://www.youtube.com/watch?v=0OR2U6ciBks

**Comment by stigvp** [comment]
Dear Wojciech,

Thank you for getting in touch about this. Please accept our sincere apologies for this error. The paper has now been amended to correct this. This should go live on arxiv later today and we will also update the version hosted on deepmind.com. We will keep this issue open until both are live.

Please note that you can always reach us on lab@deepmind.com.

Many thanks
