### ISSUE TITLE
The picture is upside down

### ISSUE THREAD

**Issue by marooncn** [deepmind/lab#111]
Hi, when I install successfully and run the  test code, the picture is upside down. How can I solve it?

**Comment by tkoeppe** [comment]
It isn't "upside down" (which would presume some human prejudice on what the "right way" is) -- it's just what the agent sees :-) This is working as intended. If your agent doesn't like this, you can install additional computations to transform the output on your end.

The `//:game` binary does perform this transformation, so you can use that to test play levels with a human interface.

**Comment by wookayin** [comment]
I'm confused about this -- when get a RGB observation programmatically, e.g. `img = env.observations()['RGB_INTERLEAVED']` I always get correct images without upside down. If what you mentioned is intentional, why this is the case?
