### ISSUE TITLE
Windows Support? 

### ISSUE THREAD

**Issue by JaeDukSeo** [deepmind/lab#115]
I was just wondering if there would be instructions on running this on windows.

**Comment by tkoeppe** [comment]
There are no plans for Windows support at the moment. We don't have the toolchain to develop it and test it, but moreover, it's not even clear that all our dependencies are available on Windows. I'd welcome information on this if you'd like to help, but it's too early to make any definitive statements. If there's a clear path forward and Travis support, I wouldn't be opposed to getting there eventually.
