### ISSUE TITLE
Unable to bazel build -c opt //:deepmind_lab.so

### ISSUE THREAD

**Issue by jsdd25** [deepmind/lab#116]
Hi

I'm on Ubuntu 16.04 and following the guidelines from https://github.com/deepmind/lab/blob/master/docs/build.md . I'm unable to run bazel build -c opt //:deepmind_lab.so

Error is:
_jin@jin-System-Product-Name:~/lab$ bazel build -c opt //:deepmind_lab.so
INFO: Invocation ID: 2195313b-df07-43d3-9c01-11aab3e415c6
ERROR: /home/jin/lab/BUILD:923:1: no such package '@com_google_absl//absl/container': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule. and referenced by '//:dmlab_so_loader'
ERROR: Analysis of target '//:deepmind_lab.so' failed; build aborted: no such package '@com_google_absl//absl/container': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
INFO: Elapsed time: 0.092s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets conf\
igured)
    currently loading: @bazel_tools//src/tools/launcher_

Any help to resolve this will be appreciated !

**Comment by tkoeppe** [comment]
What's your Bazel version? Can you upgrade it to the latest and run `bazel clean --expunge`?

**Comment by jsdd25** [comment]
@tkoeppe Hello! My Bazel version is 0.20.0. And I run bazel clean --expunge. But I'm also unable to run bazel build -c opt //:deepmind_lab.so
Error is:
`jin@jin-System-Product-Name:~/lab$ bazel build -c opt //:deepmind_lab.so
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 37b3c6fa-030b-4fb1-b88d-3ee32bbb2c77
ERROR: /home/jin/lab/BUILD:923:1: no such package '@com_google_absl//absl/container': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule. and referenced by '//:dmlab_so_loader'
ERROR: Analysis of target '//:deepmind_lab.so' failed; build aborted: no such package '@com_google_absl//absl/container': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
INFO: Elapsed time: 2.216s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (17 packages loaded, 783 targets c\
onfigured)
    Fetching @com_google_absl; fetching`

Please give me some help. Thank you very much!

**Comment by tkoeppe** [comment]
Aha, yes, thanks -- looks like Bazel has changed and this now needs to be a StarLark rule. Fixed by 3b976e59104f5b3e765bc7a84d84a5eefc238991.
