### ISSUE TITLE
Linking errors when building [was: Unable to run a human controlled agent using Deepmind Lab]

### ISSUE THREAD

**Issue by behroozmrd47** [deepmind/lab#118]
Hello,
I have successfully installed deepmindlab in Ubuntu 16.04 with gcc version gcc (Ubuntu 6.5.0-2ubuntu1~16.04) 6.5.0 20181026 and bazel version 0.16.1. 

I have tested both both "bazel build //:deepmind_lab.so" and "bazel test //python/tests:python_module_test" and both passed. I also can run the random agent and a wondow opens and I can see the agnet wondering around. 

However, when I tried to run the human based agent using "bazel run :game -- -l tests/empty_room_test -s logToStdErr=true" and I get the following error message:

INFO: Analysed target //:game (0 packages loaded).
INFO: Found 1 target...
ERROR: /home/behroozmb/lab/BUILD:875:1: Linking of rule '//:game' failed (Exit 1)
bazel-out/k8-fastbuild/bin/external/lua_archive/_objs/lua/loslib.pic.o:loslib.c:function os_tmpname: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/malloc_internal/low_level_alloc.pic.o:low_level_alloc.cc:function absl::base_internal::(anonymous namespace)::ArenaLock::ArenaLock(absl::base_internal::LowLevelAlloc::Arena*): error: undefined reference to 'pthread_sigmask'
bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/malloc_internal/low_level_alloc.pic.o:low_level_alloc.cc:function absl::base_internal::(anonymous namespace)::ArenaLock::Leave(): error: undefined reference to 'pthread_sigmask'
bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/base/thread_identity.pic.o:thread_identity.cc:function absl::base_internal::(anonymous namespace)::AllocateThreadIdentityKey(void (*)(void*)): error: undefined reference to 'pthread_key_create'
bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/base/thread_identity.pic.o:thread_identity.cc:function absl::base_internal::SetCurrentThreadIdentity(absl::base_internal::ThreadIdentity*, void (*)(void*)): error: undefined reference to 'pthread_sigmask'
bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/base/thread_identity.pic.o:thread_identity.cc:function absl::base_internal::SetCurrentThreadIdentity(absl::base_internal::ThreadIdentity*, void (*)(void*)): error: undefined reference to 'pthread_setspecific'
bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/base/thread_identity.pic.o:thread_identity.cc:function absl::base_internal::SetCurrentThreadIdentity(absl::base_internal::ThreadIdentity*, void (*)(void*)): error: undefined reference to 'pthread_sigmask'
bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/base/thread_identity.pic.o:thread_identity.cc:function absl::base_internal::CurrentThreadIdentityIfPresent(): error: undefined reference to 'pthread_getspecific'
collect2: error: ld returned 1 exit status
Target //:game failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.342s, Critical Path: 0.79s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

Any idea what may be wrong. Any help is highly appreciated.
Thanks,

**Comment by tkoeppe** [comment]
This seems to be a recently introduced bug in either Abseil or Bazel. Actually, since you're seeing this on Bazel 0.16.1, it has to be in Abseil (thanks!).

See also https://github.com/abseil/abseil-cpp/issues/240.

For now, you can work around this by passing `--linkopt=-pthread` to Bazel. Hopefully there will be a fix soon.

**Comment by behroozmrd47** [comment]
> This seems to be a recently introduced bug in either Abseil or Bazel. Actually, since you're seeing this on Bazel 0.16.1, it has to be in Abseil (thanks!).
> 
> See also [abseil/abseil-cpp#240](https://github.com/abseil/abseil-cpp/issues/240).
> 
> For now, you can work around this by passing `--linkopt=-pthread` to Bazel. Hopefully there will be a fix soon.

Thanks for your response. I did include the mentioned quick fix but it did not worked and I get the same error. To be concise, I entered the following command "~/lab$ bazel run :game -- -l tests/empty_room_test -s logToStdErr=true --linkopt=-pthread" and got the exact same error. Any ideas why?

Thankfully,

**Comment by tkoeppe** [comment]
You need to pass the option to bazel, not to the program, so put it before the `--`.

**Comment by tkoeppe** [comment]
This should now be fixed in Abseil; please run `bazel clean --expunge` and try again.
