### ISSUE TITLE
Incomplete Lua Api Docs?

### ISSUE THREAD

**Issue by ryanprinster** [deepmind/lab#120]
Are the [Lua Api Docs](https://github.com/deepmind/lab/blob/121e43a02634c13796a8a32d993f87bd080290b6/docs/developers/reference/lua_api.md) incomplete? I ask as I see some functions used that don't seem to be defined here, such as canTrigger and Trigger in [keys_doors_puzzle_factory](https://github.com/deepmind/lab/blob/4293f0338ede63691abac778de1b2801bd9092ff/game_scripts/factories/rooms/keys_doors_puzzle_factory.lua).

If so, where can I go to see exactly how api functions not defined in the lua api docs are used?

**Comment by charlesbeattie** [comment]
The documentation is incomplete.
We will look to update it.
The methods can be found called from C++ here: https://github.com/deepmind/lab/blob/4293f0338ede63691abac778de1b2801bd9092ff/deepmind/engine/context.cc#L1117

The two functions that can be called are:

function api:canTrigger(entityId, targetName, playerId)
  local allowTriggerToActivate = true
  return allowTriggerToActivate
end


function api:trigger(entityId, targetName, playerId)
  local performTriggerAction = true
  return performTriggerAction
end

Triggers are built-in to Quake3 and use targnames. These can be read and adjusted during updateSpawnVars which intercepts entity loading.

Take inspiration from keys_doors_puzzle_factory.

Opening doors at will may require adding a call we have not investigated it.

**Comment by ryanprinster** [comment]
But I believe that has been done? The Deepmind [Grid Cell Paper](https://www.nature.com/articles/s41586-018-0102-6.epdf?author_access_token=BjM-5BdGxd14c17YFA6PsdRgN0jAjWel9jnR3ZoTv0OEfySMT4t78PpPpCS7uExW3njb8Q4UlgcwRM32WwBCKZs73SThwkfI42wHhFEtJM-Y7sQxDsR1cR7_C9Kq1GwuxGJn46kzRnujvrDMGzc4TQ%3D%3D) seems to have doors open or closed for at least an entire episode, if you look at Fig 3a,b and Fig 4a,b,d,e. Is this not the case?

**Comment by charlesbeattie** [comment]
Sorry for not getting back to you sooner.

Doors can be spawned open or closed with spawnflags.
See game_scripts/factories/explore/obstructed_goals_factory.lua
In the updateSpawnVars section the door state can be set with spawnflags.

```Lua
        spawnVars.spawnflags = '1' -- open
        spawnVars.spawnflags = '0' -- closed
```

**Comment by ryanprinster** [comment]
No worries. And I see, although that only seems to change the initial state, as the doors still change state when a player approaches.

As a workaround, I changed spawnVars.wait and spawnVars.speed to keep the doors open or closed, but would there be a way to change what triggers the door? For instance, linking it to a position trigger. I don't understand how to use api:canTrigger and api:trigger, and if those can help. 

Additionally, is there a way to edit spawnVars during a game? It seems as if the only way to edit them is through the updateSpawnVars api call, which is not called mid-game. 

If I can edit spawnVars in game, is it possible to spawn new rewards / remove old rewards mid-game as well?

**Comment by charlesbeattie** [comment]
Yes! Take a look at:
https://github.com/deepmind/lab/blob/master/game_scripts/levels/tests/extra_entities_test.lua
