### ISSUE TITLE
Can't build to simple gym-like interface

### ISSUE THREAD

**Issue by bjg2** [deepmind/lab#127]
Walking through the examples, I haven't understood how can I build the code, and after build have an easy, gym-like environment I could instantiate / reset / step / etc? Everything that I managed was building and starting stuff directly through bazel, similar to python_random_agent, but I don't see how to call step/reset outside of bazel. Am I missing something or there is no description of how to build+run such an environment?

**Comment by tkoeppe** [comment]
DeepMind Lab is predominantly a *library* that you integrate into your own project. We use Bazel as the build system, but there are several ways you can use the code from elsewhere:

* If you want to program in Python, you can build DeepMind Lab as a PIP, install that and then just import the module from Python.

* You can also build the shared library (either with software or with hardware rendering); see the BUILD file for the relevant targets, and then link against that (either directly, at link time, from native code, or dynamically via `dlopen`). Then you'd use the provided C API to drive the environment. In fact, that's exactly what the Python module is doing, so you can use the Python module source code as an example for loading the DSO.

**Comment by mtrazzi** [comment]
@tkoeppe thanks for the answer. I'm also trying to build some kind of gym-like API to a deepmind lab env. The pip package tutorial & dmlab_module.c in python are well-documented, so thanks for that as well. A few comments on the gym-like env and pip package:

-  I'm also (cc @bjg2 ) trying to build some kind of gym-like wrapper to a DeepMind Lab env ([here ](https://gist.github.com/mtrazzi/02f03c5816b62ab10a79a9705ac0c68b) for the gist to my current wrapper). I'm trying to find a way of querying whether an env has finished or not ([this one](https://github.com/deepmind/lab/blob/master/game_scripts/levels/contributed/psychlab/harlow.lua)). I saw in the [lua api doc](https://github.com/deepmind/lab/blob/master/docs/developers/reference/lua_api.md) that there seems to be a `hasEpisodeFinished` method to query the env via lua. @tkoeppe Is there a way to do the same via the python API? The "done" variable is necessary for some "gym-like" interface.

- Also, I've tried to build a pip package from mac, and it's almost working on the macos branch. It's just a matter of changing the cp/mkdir/mktemp options from linux to mac (what I've almost finished [here](https://github.com/mtrazzi/lab/blob/b1a140c3b448363a4d485aa682d4bda7f52018bf/python/pip_package/build_pip_package.sh)). @tkoeppe Should I do a pull request on the macos branch when I'm done?

**Comment by bjg2** [comment]
So I built and run pip - tank you very much. I found pip installation page via google though and I'm not sure how could anyone know where to find pip installation instructions? I think readme should improve answering that question, cause I guess that's the main thing people coming here are looking for?

Regarding above question, I found answer on [python API readme](https://github.com/deepmind/lab/blob/master/docs/users/python_api.md):
```
Resets the environment to its initialization state. This method needs to be called to start a new episode after the last episode ended (which puts the environment into is_running() == False state).
```

I have one more question: what kind of events could be returned with events() method?

For anyone breaking their head on how to start environments via python:
```
# Install external dependencies as described in https://github.com/deepmind/lab#external-dependencies-prerequisites-and-porting-notes
git clone https://github.com/deepmind/lab.git dm-lab
cd dm-lab
virtualenv -p python3 venv
source venv/bin/activate
# Change files similar to this change, but for python3.6 https://github.com/deepmind/lab/commit/20449696670d2de5fa71be86b21330a227e33d49
bazel build -c opt python/pip_package:build_pip_package
./bazel-bin/python/pip_package/build_pip_package $(pwd)
# pip install generated wheel from wherever
# Test the instalation, for example with https://github.com/deepmind/lab/tree/master/python/pip_package#testing-the-installation
```

**Comment by tkoeppe** [comment]
@mtrazzi: Regarding the macos branch: Will this work generally and for everyone? I haven't looked at the PIP build script, so if you can/have, that would be very helpful. I think we would integrate those changes into the "floating commit", such as ccfe8a6245d9374167e8e442629f8d99b7b9230c.

It's a bit of a pain for users to have the "macos" branch be this constant rebasing; I'm thinking of turning the branch into a checked in `.patch` file that you just apply locally...

**Comment by tkoeppe** [comment]
@mtrazzi: I'm not super familiar with the Python API, but have a look at `is_running`. According to the [`reset` documentation](https://github.com/deepmind/lab/blob/master/docs/users/python_api.md#resetepisode-1-seednone), that's what tells you that an episode has ended.

**Comment by mtrazzi** [comment]
@tkoeppe The `is_running()` method works well, thanks. [Here](https://gist.github.com/mtrazzi/b8c8ada8be07e7f65feb5b43598f9a80) is a working gym-like wrapper @bjg2, let me know if that helps.

@tkoeppe I'm not sure how to contribute to this "floating commit". I tried to git checkout to the commit and make a pull request but it doesn't seem to belong to any branch. Here is the [pip bash script](https://gist.github.com/mtrazzi/d1154dfb71a9d98ec5917ce2aa9abd40) that works on macos.

**Comment by tkoeppe** [comment]
@mtrazzi: I think you can just make a pull request against the "macos" branch? What I mean by "floating" is that I'll eventually rebase that branch, so that commit will "float up" to to the top (and get a new commit hash).

**Comment by mtrazzi** [comment]
@tkoeppe done

**Comment by tkoeppe** [comment]
So, I think that the macos branch _already_ contains the necessary modifications, right? I think that settles everything? Please feel free to reopen if you have new information.

Note also that I recently added a Python wrapper module for our new `dm_env` Python API, in case that's of interest or use to anyone.
