### ISSUE TITLE
Python API questions

### ISSUE THREAD

**Issue by bjg2** [deepmind/lab#128]
I'm reading the [python API](https://github.com/deepmind/lab/blob/master/docs/users/python_api.md) and I have a few questions to check if I am understanding the API correctly:

- step(action) is returning action reward?
- If the episode is done is_runining() will return False?
- What kind of data events() method can return?

**Comment by tkoeppe** [comment]
1) yes, 2) yes, 3) events are user-defined by the level's Lua script, and each event can be queried for its type upon receipt.

**Comment by tkoeppe** [comment]
Please reopen if you have any further questions.
