### ISSUE TITLE
undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by ricoj** [deepmind/lab#13]
Hi, when I follow the instructions from https://github.com/deepmind/lab to install lab at ubuntu 16.04, I get a "undefined symbol: _Py_ZeroStruct" error after executing the following command:

`bazel run :python_module_test --define headless=glx`

The full command line output is:
```
INFO: Found 1 target...
Target //:python_module_test up-to-date:
  bazel-bin/python_module_test
INFO: Elapsed time: 0.230s, Critical Path: 0.01s

INFO: Running command line: bazel-bin/python_module_test
Traceback (most recent call last):
  File "/home/rico/.cache/bazel/_bazel_rico/4b96fd176693dd396977e881a84a79f8/execroot/lab/bazel-out/local-fastbuild/bin/python_module_test.runfiles/org_deepmind_lab/python/dmlab_module_test.py", line 26, in <module>
    import deepmind_lab
ImportError: /home/rico/.cache/bazel/_bazel_rico/4b96fd176693dd396977e881a84a79f8/execroot/lab/bazel-out/local-fastbuild/bin/python_module_test.runfiles/org_deepmind_lab/deepmind_lab.so: undefined symbol: _Py_ZeroStruct
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

**Comment by heiner** [comment]
Hey Rico, can you make sure you're using Python 2.7 and the development files you have installed are for that version?

On my machine:
```shell
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
$ python --version
Python 2.7.12
```

**Comment by ricoj** [comment]
Ahh, my Anaconda installation of python3 got in the way. "python" linked to python3 rather than python2. Removing the path to Anaconda in my ~/.bashrc solved the problem.

Thank you, Heinrich, for your quick and helpful reply!
