### ISSUE TITLE
Video and game is mirror on Y axis

### ISSUE THREAD

**Issue by talregev** [deepmind/lab#136]
I create a deepmind lab environment on google colaboratory. 
https://colab.research.google.com/drive/1P4l_iFbzRGdMsnnmyAlWhJjqLY7qIWWE

I run the random agent:
`bazel run -c opt :python_random_agent`
And the video was created as Y mirror axis. 
Can you fix it?

**Comment by talregev** [comment]
Can you add dqn train example?

**Comment by tkoeppe** [comment]
This is a duplicate of #104.
