### ISSUE TITLE
what's up with https://mirror.bazel.build

### ISSUE THREAD

**Issue by luxe** [deepmind/lab#139]
Hey, does bazel have any documentation about these "mirror builds"?  
Is that a thing other bazel users can be expected to use?  
Or since deepmind is a google thing, you are able to host things there?  
just curious; thanks!

**Comment by tkoeppe** [comment]
I'm not exactly sure. I think it's a bit of a manual setup at the moment, so it's neither well documented nor available for general use. I don't even think all current mirror entries in our WORKSPACE are populated. I can try and have that fixed for Lab, but I don't think it's open to arbitrary new submissions.
