### ISSUE TITLE
Why is angular velocity always (0,0,0)?

### ISSUE THREAD

**Issue by winds-line** [deepmind/lab#140]
Whatever I change the action's parameters of the random agent, the outputs of observation['VEl.ROT']  are always (0,0,0). Please how to generate the angular velocity by setting the action's parameters of the random agent.
![2019-03-04 10-53-03](https://user-images.githubusercontent.com/15816659/53708097-c68c8a00-3e6c-11e9-978a-5a0c1d11faed.png)
![2019-03-04 10-54-26](https://user-images.githubusercontent.com/15816659/53708106-cdb39800-3e6c-11e9-819d-85cbe38f0f87.png)

**Comment by winds-line** [comment]
This is the action's parameter that I have changed.
![2019-03-04 11-03-12](https://user-images.githubusercontent.com/15816659/53708328-e4a6ba00-3e6d-11e9-8842-777e5364a03a.png)

**Comment by tkoeppe** [comment]
See also #180 for analysis and resolution.
