### ISSUE TITLE
When I do the command:bazel build -c opt //:deepmind_lab.so, I find that:

### ISSUE THREAD

**Issue by chaobiubiu** [deepmind/lab#141]
INFO: Build options --compilation_mode and --define have changed, discarding analysis cache.
ERROR: /home/lichao/lab/BUILD:923:1: no such package '@com_google_absl//absl/container': java.io.IOException: Error downloading [https://github.com/abseil/abseil-cpp/archive/master.zip] to /home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/external/com_google_absl/master.zip: Read timed out and referenced by '//:dmlab_so_loader'
ERROR: Analysis of target '//:deepmind_lab.so' failed; build aborted: no such package '@com_google_absl//absl/container': java.io.IOException: Error downloading [https://github.com/abseil/abseil-cpp/archive/master.zip] to /home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/external/com_google_absl/master.zip: Read timed out
INFO: Elapsed time: 217.872s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 2690 targets c\
onfigured)
    Fetching @com_google_absl; fetching 217s

**Comment by tkoeppe** [comment]
"Read timed out" sounds weird, can you just try again? (Maybe after `bazel clean --expunge`?)

**Comment by chaobiubiu** [comment]
> "Read timed out" sounds weird, can you just try again? (Maybe after `bazel clean --expunge`?)
When I do as you said, it shows that: Build completed successfully, 936 total actions. But when I do the second command:bazel test -c opt //python/tests:python_module_test, it suggests that:
FAIL: //python/tests:python_module_test (see /home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/execroot/org_deepmind_lab/bazel-out/k8-opt/testlogs/python/tests/python_module_test/test.log)
Target //python/tests:python_module_test up-to-date:
  bazel-bin/python/tests/python_module_test
I am sorry to ask for your help again.

**Comment by tkoeppe** [comment]
That seems like an unrelated issue. What does the log file say?

**Comment by chaobiubiu** [comment]
> That seems like an unrelated issue. What does the log file say?

Failed to get __file__ attribute.
Failed to open library! - /home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/sandbox/linux-sandbox/1/execroot/org_deepmind_lab/bazel-out/k8-opt/bin/python/tests/python_module_test.runfiles/org_deepmind_lab/libdmlab_headless_sw.so
/home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1)
EFailed to open library! - /home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/sandbox/linux-sandbox/1/execroot/org_deepmind_lab/bazel-out/k8-opt/bin/python/tests/python_module_test.runfiles/org_deepmind_lab/libdmlab_headless_sw.so
/home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1)
EFailed to open library! - /home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/sandbox/linux-sandbox/1/execroot/org_deepmind_lab/bazel-out/k8-opt/bin/python/tests/python_module_test.runfiles/org_deepmind_lab/libdmlab_headless_sw.so
/home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1)
EFailed to open library! - /home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/sandbox/linux-sandbox/1/execroot/org_deepmind_lab/bazel-out/k8-opt/bin/python/tests/python_module_test.runfiles/org_deepmind_lab/libdmlab_headless_sw.so
/home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1)
EFailed to open library! - /home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/sandbox/linux-sandbox/1/execroot/org_deepmind_lab/bazel-out/k8-opt/bin/python/tests/python_module_test.runfiles/org_deepmind_lab/libdmlab_headless_sw.so
/home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1)
EFailed to open library! - /home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/sandbox/linux-sandbox/1/execroot/org_deepmind_lab/bazel-out/k8-opt/bin/python/tests/python_module_test.runfiles/org_deepmind_lab/libdmlab_headless_sw.so
/home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1)
E.Failed to open library! - /home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/sandbox/linux-sandbox/1/execroot/org_deepmind_lab/bazel-out/k8-opt/bin/python/tests/python_module_test.runfiles/org_deepmind_lab/libdmlab_headless_sw.so
/home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1)
EFailed to open library! - /home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/sandbox/linux-sandbox/1/execroot/org_deepmind_lab/bazel-out/k8-opt/bin/python/tests/python_module_test.runfiles/org_deepmind_lab/libdmlab_headless_sw.so
/home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1)
EFailed to open library! - /home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/sandbox/linux-sandbox/1/execroot/org_deepmind_lab/bazel-out/k8-opt/bin/python/tests/python_module_test.runfiles/org_deepmind_lab/libdmlab_headless_sw.so
/home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1)
EFailed to open library! - /home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/sandbox/linux-sandbox/1/execroot/org_deepmind_lab/bazel-out/k8-opt/bin/python/tests/python_module_test.runfiles/org_deepmind_lab/libdmlab_headless_sw.so
/home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1)
E
======================================================================
ERROR: testEvents (__main__.DeepMindLabTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/sandbox/linux-sandbox/1/execroot/org_deepmind_lab/bazel-out/k8-opt/bin/python/tests/python_module_test.runfiles/org_deepmind_lab/python/tests/dmlab_module_test.py", line 143, in testEvents
    config={'height': '32', 'width': '32'})
RuntimeError: Failed to connect RL API

======================================================================
ERROR: testInitArgs (__main__.DeepMindLabTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/sandbox/linux-sandbox/1/execroot/org_deepmind_lab/bazel-out/k8-opt/bin/python/tests/python_module_test.runfiles/org_deepmind_lab/python/tests/dmlab_module_test.py", line 36, in testInitArgs
    deepmind_lab.Lab('tests/empty_room_test', [], {'wrongtype': 3})
RuntimeError: Failed to connect RL API

======================================================================
ERROR: testOpenClose (__main__.DeepMindLabTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/sandbox/linux-sandbox/1/execroot/org_deepmind_lab/bazel-out/k8-opt/bin/python/tests/python_module_test.runfiles/org_deepmind_lab/python/tests/dmlab_module_test.py", line 80, in testOpenClose
    deepmind_lab.Lab('tests/empty_room_test', []) for _ in range(5)]
RuntimeError: Failed to connect RL API

======================================================================
ERROR: testReset (__main__.DeepMindLabTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/sandbox/linux-sandbox/1/execroot/org_deepmind_lab/bazel-out/k8-opt/bin/python/tests/python_module_test.runfiles/org_deepmind_lab/python/tests/dmlab_module_test.py", line 43, in testReset
    lab = deepmind_lab.Lab('tests/empty_room_test', [], {})
RuntimeError: Failed to connect RL API

======================================================================
ERROR: testRun (__main__.DeepMindLabTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/sandbox/linux-sandbox/1/execroot/org_deepmind_lab/bazel-out/k8-opt/bin/python/tests/python_module_test.runfiles/org_deepmind_lab/python/tests/dmlab_module_test.py", line 85, in testRun
    env = deepmind_lab.Lab('lt_chasm', [observation])
RuntimeError: Failed to connect RL API

======================================================================
ERROR: testRunClosed (__main__.DeepMindLabTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/sandbox/linux-sandbox/1/execroot/org_deepmind_lab/bazel-out/k8-opt/bin/python/tests/python_module_test.runfiles/org_deepmind_lab/python/tests/dmlab_module_test.py", line 97, in testRunClosed
    env = deepmind_lab.Lab('lt_chasm', ['RGB_INTERLEAVED'])
RuntimeError: Failed to connect RL API

======================================================================
ERROR: testSpecs (__main__.DeepMindLabTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/sandbox/linux-sandbox/1/execroot/org_deepmind_lab/bazel-out/k8-opt/bin/python/tests/python_module_test.runfiles/org_deepmind_lab/python/tests/dmlab_module_test.py", line 49, in testSpecs
    lab = deepmind_lab.Lab('tests/empty_room_test', [])
RuntimeError: Failed to connect RL API

======================================================================
ERROR: testStringObervations (__main__.DeepMindLabTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/sandbox/linux-sandbox/1/execroot/org_deepmind_lab/bazel-out/k8-opt/bin/python/tests/python_module_test.runfiles/org_deepmind_lab/python/tests/dmlab_module_test.py", line 130, in testStringObervations
    config={'height': '32', 'width': '32'})
RuntimeError: Failed to connect RL API

======================================================================
ERROR: testVeloctyObservations (__main__.DeepMindLabTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/sandbox/linux-sandbox/1/execroot/org_deepmind_lab/bazel-out/k8-opt/bin/python/tests/python_module_test.runfiles/org_deepmind_lab/python/tests/dmlab_module_test.py", line 197, in testVeloctyObservations
    config={'height': str(height), 'width': str(width), 'fps': '60'})
RuntimeError: Failed to connect RL API

======================================================================
ERROR: testWidthHeight (__main__.DeepMindLabTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lichao/.cache/bazel/_bazel_lichao/273586862bc1b1afbaa0e75578419068/sandbox/linux-sandbox/1/execroot/org_deepmind_lab/bazel-out/k8-opt/bin/python/tests/python_module_test.runfiles/org_deepmind_lab/python/tests/dmlab_module_test.py", line 115, in testWidthHeight
    config={'height': str(height), 'width': str(width)})
RuntimeError: Failed to connect RL API
Sorry, because I am not good at it, I only pass the whole log record to you.

**Comment by tkoeppe** [comment]
> /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version GLIBCXX_3.4.22' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1)

This looks like an installation problem with your C++ compiler and C library.

**Comment by chaobiubiu** [comment]
> > /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version GLIBCXX_3.4.22' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1)
> 
> This looks like an installation problem with your C++ compiler and C library.



> > /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version GLIBCXX_3.4.22' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1)
> 
> This looks like an installation problem with your C++ compiler and C library.

Thank you!!!

**Comment by chaobiubiu** [comment]
> > /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version GLIBCXX_3.4.22' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1)
> 
> This looks like an installation problem with your C++ compiler and C library.

I have successfully run the deepmind lab by modifying some files. Thank you for your help again sincerely. OvO

**Comment by Idolphint** [comment]
> > > /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version GLIBCXX_3.4.22' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1)
> > 
> > 
> > This looks like an installation problem with your C++ compiler and C library.
> 
> I have successfully run the deepmind lab by modifying some files. Thank you for your help again sincerely. OvO



> > > /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version GLIBCXX_3.4.22' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1)
> > 
> > 
> > This looks like an installation problem with your C++ compiler and C library.
> 
> I have successfully run the deepmind lab by modifying some files. Thank you for your help again sincerely. OvO



> > > /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version GLIBCXX_3.4.22' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1)
> > 
> > 
> > This looks like an installation problem with your C++ compiler and C library.
> 
> I have successfully run the deepmind lab by modifying some files. Thank you for your help again sincerely. OvO

can you share what has been modified? I encount the same error(but no c++ errors)
