### ISSUE TITLE
Installing in conda environment

### ISSUE THREAD

**Issue by sg2** [deepmind/lab#142]
Hi, I'm trying to PIP install Lab into a Python 3.6 conda environment on Ubuntu 16.04.

After following the [PIP instructions](https://github.com/deepmind/lab/tree/master/python/pip_package), I'm able to build with: `bazel build -c opt python/pip_package:build_pip_package --python_path=/home/sam/anaconda3/envs/dmlab/bin/python`

And I am able to test successfully with: `bazel test -c opt //python/tests:python_module_test python_path=/home/sam/anaconda3/envs/dmlab/bin/python`

And `bazel run :game -- --level_script=tests/empty_room_test --level_setting=logToStdErr=true`

And  `bazel run :python_random_agent`

I then install with: pip install /tmp/dmlab_pkg/DeepMind_Lab-1.0-py3-none-any.whl --force-reinstall

But, when I try to run `agent.py` (from the PIP instructions) I get
```
(dmlab) sam@sam-ThinkCentre-M83:~/Documents/dmlab$ python agent.py 
Traceback (most recent call last):
  File "agent.py", line 1, in <module>
    import deepmind_lab
  File "/home/sam/anaconda3/envs/dmlab/lib/python3.6/site-packages/deepmind_lab/__init__.py", line 7, in <module>
    __name__, 'deepmind_lab.so'))
  File "/home/sam/anaconda3/envs/dmlab/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/sam/anaconda3/envs/dmlab/lib/python3.6/site-packages/deepmind_lab/deepmind_lab.so: undefined symbol: PyString_Type
```
I've read [#96](https://github.com/deepmind/lab/issues/96), and from that I tried replacing my `dmlab_module.c` with the one from [0e4e3f5](https://github.com/deepmind/lab/blob/0e4e3f5dcb43f00aebb8b3e3fbf997cb4eaf79d8/python/dmlab_module.c) but then I get a segfault during the `bazel test` command. 

My conda environment is running Python 3.6. For reference, here are the changes I made to get it to build:

`WORKSPACE` changed to
```
# TODO: Replace with hermetic build
new_local_repository(
    name = "sdl_system",
    build_file = "sdl.BUILD",
    path = "/usr",
)

new_local_repository(
    name = "python_system",
    build_file = "python.BUILD",
    path = "/home/sam/anaconda3/envs/dmlab",
)
```

 `python.BUILD` changed to
```
cc_library(
    name = "python",
    hdrs = glob([
        "include/python3.6m/*.h",
        "lib/python3.6/site-packages/numpy-1.16.2-py3.6-linux-x86_64.egg/numpy/core/include/*.h",
    ]),
    includes = [
        "include/python3.6m",
        "lib/python3.6/site-packages/numpy-1.16.2-py3.6-linux-x86_64.egg/numpy/core/include",
    ],
    visibility = ["//visibility:public"],
)
```
Note, for those trying to set their numpy include path, run: ` python -c 'import numpy as np; print(np.get_include())'`

**Comment by tkoeppe** [comment]
There seems to be something missing from your message.

**Comment by sg2** [comment]
Sorry, that is fixed now.

**Comment by sg2** [comment]
I forgot to re-run `./bazel-bin/python/pip_package/build_pip_package /tmp/dmlab_pkg` before running `pip install /tmp/dmlab_pkg/DeepMind_Lab-1.0-py3-none-any.whl --force-reinstall`

Now `agent.py` runs without error :)
