### ISSUE TITLE
Sorry i don't know what i'm doing wrong

### ISSUE THREAD

**Issue by ZombiePm** [deepmind/lab#144]
user@PC001:~$ cd lab
user@PC001:~/lab$ sudo bazel run :game -- --level_script=tests/empty_room_test --level_setting=logToStdErr=true --sandbox_debug
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: SHA256 (https://github.com/abseil/abseil-cpp/archive/master.zip) = f63fa171a79bfd38f995b899989e74144255fcea57ad74079792385841db64dd
DEBUG: Rule 'com_google_absl' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "f63fa171a79bfd38f995b899989e74144255fcea57ad74079792385841db64dd"
INFO: Analysed target //:game (51 packages loaded, 3679 targets configured).
INFO: Found 1 target...
ERROR: /home/user/.cache/bazel/_bazel_root/851aceb1df3dfff730804dc58954a97b/external/glib_archive/BUILD.bazel:1:1: Executing genrule @glib_archive//:gen_configure failed (Exit 1) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
configure: error:
*** You must have either have gettext support in your C library, or use the
*** GNU gettext library. (http://www.gnu.org/software/gettext/gettext.html)

Target //:game failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 254.198s, Critical Path: 46.81s
INFO: 154 processes: 154 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by tkoeppe** [comment]
Well, can you install gettext via your system's package management? (E.g. `sudo apt-get install gettext` (see [instructions](https://github.com/deepmind/lab/blob/master/docs/users/build.md#step-by-step-instructions-for-building-and-running))?

**Comment by tkoeppe** [comment]
Also, there should be no need to use `sudo` to run things!

**Comment by ZombiePm** [comment]
user@PC001:~/lab$ sudo bazel run :game -- --level_script=tests/empty_room_test --level_setting=logToStdErr=true --sandbox_debug
DEBUG: Rule 'com_google_absl' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "f63fa171a79bfd38f995b899989e74144255fcea57ad74079792385841db64dd"
INFO: Analysed target //:game (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
INFO: From Compiling deepmind/engine/lua_text_level_maker.cc:
deepmind/engine/lua_text_level_maker.cc: In member function 'virtual deepmind::lab::Theme::Texture deepmind::lab::{anonymous}::LuaTheme::wall(int, deepmind::lab::Theme::Direction)':
deepmind/engine/lua_text_level_maker.cc:126:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
INFO: From Compiling deepmind/engine/context_pickups.cc:
In file included from deepmind/engine/context_pickups.cc:25:0:
deepmind/engine/context_pickups.cc: In member function 'void deepmind::lab::ContextPickups::ReadExtraEntity(int, char*, int*, int (*)[2], int*)':
deepmind/engine/context_pickups.cc:232:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   CHECK(0 <= entity_index && entity_index < extra_entities_.size());
                              ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
./deepmind/support/logging.h:159:15: note: in definition of macro 'CHECK'
              (condition) ? nullptr : new std::string(#condition)))             \
               ^~~~~~~~~
./deepmind/support/logging.h: In instantiation of 'deepmind::internal::CheckOpString deepmind::internal::Check_LEImpl(const T1&, const T2&, const char*) [with T1 = long unsigned int; T2 = int]':
deepmind/engine/context_pickups.cc:220:3:   required from here
./deepmind/support/logging.h:73:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 DEFINE_CHECK_OP_IMPL(Check_LE, <=)
                                ^
./deepmind/support/logging.h:32:48: note: in definition of macro 'PREDICT_TRUE'
 #  define PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                ^
./deepmind/support/logging.h:73:1: note: in expansion of macro 'DEFINE_CHECK_OP_IMPL'
 DEFINE_CHECK_OP_IMPL(Check_LE, <=)
 ^~~~~~~~~~~~~~~~~~~~
INFO: From Compiling deepmind/engine/context.cc:
In file included from deepmind/engine/context.cc:32:0:
./deepmind/support/logging.h: In instantiation of 'deepmind::internal::CheckOpString deepmind::internal::Check_LTImpl(const T1&, const T2&, const char*) [with T1 = long unsigned int; T2 = int]':
deepmind/engine/context.cc:971:9:   required from here
./deepmind/support/logging.h:74:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 DEFINE_CHECK_OP_IMPL(Check_LT, < )
                                ^
./deepmind/support/logging.h:32:48: note: in definition of macro 'PREDICT_TRUE'
 #  define PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                ^
./deepmind/support/logging.h:74:1: note: in expansion of macro 'DEFINE_CHECK_OP_IMPL'
 DEFINE_CHECK_OP_IMPL(Check_LT, < )
 ^~~~~~~~~~~~~~~~~~~~
./deepmind/support/logging.h: In instantiation of 'deepmind::internal::CheckOpString deepmind::internal::Check_EQImpl(const T1&, const T2&, const char*) [with T1 = int; T2 = long unsigned int]':
deepmind/engine/context.cc:1370:3:   required from here
./deepmind/support/logging.h:71:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 DEFINE_CHECK_OP_IMPL(Check_EQ, ==)
                                ^
./deepmind/support/logging.h:32:48: note: in definition of macro 'PREDICT_TRUE'
 #  define PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                ^
./deepmind/support/logging.h:71:1: note: in expansion of macro 'DEFINE_CHECK_OP_IMPL'
 DEFINE_CHECK_OP_IMPL(Check_EQ, ==)
 ^~~~~~~~~~~~~~~~~~~~
INFO: From Compiling deepmind/model_generation/geometry_cube.cc:
In file included from deepmind/model_generation/geometry_cube.cc:21:0:
./deepmind/support/logging.h: In instantiation of 'deepmind::internal::CheckOpString deepmind::internal::Check_GTImpl(const T1&, const T2&, const char*) [with T1 = long unsigned int; T2 = int]':
deepmind/model_generation/geometry_cube.cc:35:3:   required from here
./deepmind/support/logging.h:76:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 DEFINE_CHECK_OP_IMPL(Check_GT, > )
                                ^
./deepmind/support/logging.h:32:48: note: in definition of macro 'PREDICT_TRUE'
 #  define PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                ^
./deepmind/support/logging.h:76:1: note: in expansion of macro 'DEFINE_CHECK_OP_IMPL'
 DEFINE_CHECK_OP_IMPL(Check_GT, > )
 ^~~~~~~~~~~~~~~~~~~~
INFO: From Compiling deepmind/model_generation/geometry_sphere.cc:
In file included from deepmind/model_generation/geometry_sphere.cc:21:0:
./deepmind/support/logging.h: In instantiation of 'deepmind::internal::CheckOpString deepmind::internal::Check_GTImpl(const T1&, const T2&, const char*) [with T1 = long unsigned int; T2 = int]':
deepmind/model_generation/geometry_sphere.cc:36:3:   required from here
./deepmind/support/logging.h:76:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 DEFINE_CHECK_OP_IMPL(Check_GT, > )
                                ^
./deepmind/support/logging.h:32:48: note: in definition of macro 'PREDICT_TRUE'
 #  define PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                ^
./deepmind/support/logging.h:76:1: note: in expansion of macro 'DEFINE_CHECK_OP_IMPL'
 DEFINE_CHECK_OP_IMPL(Check_GT, > )
 ^~~~~~~~~~~~~~~~~~~~
INFO: From Compiling deepmind/model_generation/geometry_cylinder.cc:
In file included from deepmind/model_generation/geometry_cylinder.cc:21:0:
./deepmind/support/logging.h: In instantiation of 'deepmind::internal::CheckOpString deepmind::internal::Check_GTImpl(const T1&, const T2&, const char*) [with T1 = long unsigned int; T2 = int]':
deepmind/model_generation/geometry_cylinder.cc:36:3:   required from here
./deepmind/support/logging.h:76:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 DEFINE_CHECK_OP_IMPL(Check_GT, > )
                                ^
./deepmind/support/logging.h:32:48: note: in definition of macro 'PREDICT_TRUE'
 #  define PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                ^
./deepmind/support/logging.h:76:1: note: in expansion of macro 'DEFINE_CHECK_OP_IMPL'
 DEFINE_CHECK_OP_IMPL(Check_GT, > )
 ^~~~~~~~~~~~~~~~~~~~
INFO: From Compiling deepmind/model_generation/model_lua.cc:
deepmind/model_generation/model_lua.cc: In function 'deepmind::lab::lua::ReadResult deepmind::lab::Read(lua_State*, int, deepmind::lab::Model*)':
deepmind/model_generation/model_lua.cc:131:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (min_idx < 1 || max_idx > model_surface.vertices.size() / 8) {
                        ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO: From Compiling external/lua_archive/lauxlib.c:
external/lua_archive/lauxlib.c: In function 'luaL_loadfile':
external/lua_archive/lauxlib.c:577:4: warning: this 'while' clause does not guard... [-Wmisleading-indentation]
    while ((c = getc(lf.f)) != EOF && c != LUA_SIGNATURE[0]) ;
    ^~~~~
external/lua_archive/lauxlib.c:578:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'while'
     lf.extraline = 0;
     ^~
INFO: From Compiling external/lua_archive/ltablib.c:
external/lua_archive/ltablib.c: In function 'addfield':
external/lua_archive/ltablib.c:137:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
   if (!lua_isstring(L, -1))
   ^~
external/lua_archive/ltablib.c:140:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
     luaL_addvalue(b);
     ^~~~~~~~~~~~~
INFO: From Linking game:
bazel-out/k8-fastbuild/bin/external/lua_archive/_objs/lua/loslib.pic.o:loslib.c:function os_tmpname: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
INFO: From Executing genrule @libxml_archive//:gen_configure:
Checking zlib
Checking lzma
Disabling compression support
Checking headers
Checking types
Checking libraries
Found Python version 2.7
Checking configuration requirements
Enabling multithreaded support
Enabled Schematron support
Disabling ICU support
Enabled Schemas/Relax-NG support
Disabling code coverage for GCC
Done configuring
'config.h' -> 'bazel-out/k8-fastbuild/genfiles/external/libxml_archive/config.h'
'include/libxml/xmlversion.h' -> 'bazel-out/k8-fastbuild/genfiles/external/libxml_archive/include/libxml/xmlversion.h'
INFO: From Executing genrule @glib_archive//:gen_configure:
configure: WARNING:
  You will not be able to create source packages with 'make dist'
  because gtk-doc >= 1.20 is not found.
'config.h' -> 'bazel-out/k8-fastbuild/genfiles/external/glib_archive/config.h'
'glib/glibconfig.h' -> 'bazel-out/k8-fastbuild/genfiles/external/glib_archive/glibconfig.h'
Target //:game up-to-date:
  bazel-bin/game
INFO: Elapsed time: 228.363s, Critical Path: 90.52s
INFO: 540 processes: 540 processwrapper-sandbox.
INFO: Build completed successfully, 542 total actions
INFO: Build completed successfully, 542 total actions
logToStdErr: "true"
/home/user/.cache/bazel/_bazel_root/851aceb1df3dfff730804dc58954a97b/execroot/org_deepmind_lab/bazel-out/k8-fastbuild/bin/game: unrecognized option '--sandbox_debug'
Bad command-line flag. Use --help for usage instructions.

**Comment by ZombiePm** [comment]
user@PC001:~/lab$ sudo bazel run :game -- --level_script=tests/empty_room_test --level_setting=logToStdErr=true
DEBUG: Rule 'com_google_absl' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "f63fa171a79bfd38f995b899989e74144255fcea57ad74079792385841db64dd"
INFO: Analysed target //:game (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:game up-to-date:
  bazel-bin/game
INFO: Elapsed time: 0.939s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
logToStdErr: "true"
----- Client Initialization -----
Couldn't read q3history.
----- Initializing Renderer ----
-------------------------------
QKEY building random string
QKEY generated
----- Client Initialization Complete -----
----- R_Init -----
error: XDG_RUNTIME_DIR not set in the environment.
SDL_Init( SDL_INIT_VIDEO ) FAILED (No available video device)
error: XDG_RUNTIME_DIR not set in the environment.
SDL_Init( SDL_INIT_VIDEO ) FAILED (No available video device)
Setting r_mode -1 failed, falling back on r_mode 3
error: XDG_RUNTIME_DIR not set in the environment.
SDL_Init( SDL_INIT_VIDEO ) FAILED (No available video device)
----- Client Shutdown (Client fatal crashed: GLimp_Init() - could not load OpenGL subsystem) -----
RE_Shutdown( 1 )
Hunk_Clear: reset the hunk ok
-----------------------
GLimp_Init() - could not load OpenGL subsystem
GLimp_Init() - could not load OpenGL subsystem. See "/tmp/dmlab_temp_folder_2EYx11/baselab/crashlog.txt" for details.

**Comment by ZombiePm** [comment]
this /tmp/dmlab_temp_folder_2EYx11/baselab/crashlog.txt empty

**Comment by tkoeppe** [comment]
a) can you please post slightly better formatted questions?

b) are you sitting directly at the machine, or are you using some sort of SSH connection? You need to have GLX available in your X client for the headful `:game` program. Try the random agent with software rendering, that should work.

**Comment by ZombiePm** [comment]
why all up side down
![image](https://user-images.githubusercontent.com/20536989/55657515-21662800-5803-11e9-9c4e-34aa0fbc5a27.png)

**Comment by ZombiePm** [comment]
if i run

**Comment by tkoeppe** [comment]
See https://github.com/deepmind/lab/issues/111 -- it's not really "upside down", just "not conforming to your human prejudice".

**Comment by tkoeppe** [comment]
I don't think this needs any further action from our end? Feel free to reopen if you have new information.
