### ISSUE TITLE
bazel run 

### ISSUE THREAD

**Issue by chocolateHszd** [deepmind/lab#148]
Hi

I'm having problem running the random agent example, any idea how i can fix this error?

` INFO: Build options --compilation_mode and --define have changed, discarding analysis cache.
ERROR: /home/.../dev/openai-lab-master/q3map2/BUILD:54:1: no such package '@png_archive//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/glennrp/libpng/archive/v1.6.34.zip, https://github.com/glennrp/libpng/archive/v1.6.34.zip] to /home/.../.cache/bazel/_bazel_.../fe98e0ac1b12f6cf4b26846c89d47bf4/external/png_archive/v1.6.34.zip: All mirrors are down: [PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target] and referenced by '//q3map2:q3map2'
ERROR: Analysis of target '//:python_random_agent' failed; build aborted: no such package '@png_archive//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/glennrp/libpng/archive/v1.6.34.zip, https://github.com/glennrp/libpng/archive/v1.6.34.zip] to /home/.../.cache/bazel/_bazel_.../fe98e0ac1b12f6cf4b26846c89d47bf4/external/png_archive/v1.6.34.zip: All mirrors are down: [PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target]
INFO: Elapsed time: 17.183s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 1930 targets configured)
FAILED: Build did NOT complete successfully (1 packages loaded, 1930 targets configured) `

**Comment by tkoeppe** [comment]
Hm, looks like a problem with the mirror that serves the dependencies; can you just try again?

**Comment by chocolateHszd** [comment]
I think it's a certificate issue on my side because I can wget the links without getting any exceptions but running the build script fails :
`ERROR: /home/..../dev/openai-lab-master/q3map2/BUILD:54:1: no such package '@png_archive//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/glennrp/libpng/archive/v1.6.34.zip, https://github.com/glennrp/libpng/archive/v1.6.34.zip] to /home/.../.cache/bazel/_bazel_.../fe98e0ac1b12f6cf4b26846c89d47bf4/external/png_archive/v1.6.34.zip: All mirrors are down: [PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target] and referenced by '//q3map2:q3map2'
ERROR: Analysis of target '//:python_random_agent' failed; build aborted: no such package '@png_archive//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/glennrp/libpng/archive/v1.6.34.zip, https://github.com/glennrp/libpng/archive/v1.6.34.zip] to /home/.../.cache/bazel/_bazel_.../fe98e0ac1b12f6cf4b26846c89d47bf4/external/png_archive/v1.6.34.zip: All mirrors are down: [PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target]
INFO: Elapsed time: 19.108s`

**Comment by tkoeppe** [comment]
Interesting. Could you perhaps try replacing the source links with different URLs (provided you have some at hand), or maybe just remove the bazel-mirror ones?

**Comment by chocolateHszd** [comment]
Commenting out the mirrors didn't fix my proxy problem, instead I downloaded lua, zlib and png archives and changed WORKSPACE and BUILD files for each to work with them locally and it works now.
Thanks
