### ISSUE TITLE
Help:  The Error When I do the command:bazel build -c opt //:deepmind_lab.so

### ISSUE THREAD

**Issue by jingquanliang** [deepmind/lab#149]
I am using ubuntu 19.04，and I do the command:bazel build -c opt //:deepmind_lab.so，The error is below， Please help me！！ Thank u！

jql@ubuntu:~/deepmind/lab$  sudo bazel build -c opt //:deepmind_lab.so
[sudo] password for jql: 
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 10 seconds ...
INFO: Invocation ID: b6595e63-c2b3-496a-86f6-485058de47fb
INFO: Analysed target //:deepmind_lab.so (52 packages loaded, 3780 targets configured).
INFO: Found 1 target...
ERROR: /home/jql/deepmind/lab/BUILD:62:1: Executing genrule //:lcc_dagcheck failed (Exit 1) bash failed: error executing command /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/lburg engine/code/tools/lcc/src/dagcheck.md > "bazel-out/host/genfiles/engine/code/tools/lcc/src/dagcheck.c"'

Use --sandbox_debug to see verbose messages from the sandbox
line 1: invalid character `%'
line 1: invalid character `{'
line 1: invalid character `\015'
line 2: invalid character `#'
line 2: syntax error
line 2: invalid character `\015'
line 3: syntax error
line 3: invalid character `;'
line 3: invalid character `\015'
line 4: invalid character `#'
line 4: syntax error
line 4: invalid character `-'
line 4: invalid character `>'
line 4: invalid character `\015'
line 5: invalid character `#'
line 5: syntax error
line 5: invalid character `-'
line 5: invalid character `>'
line 5: invalid character `['
line 5: invalid character `]'
line 5: invalid character `\015'
line 6: invalid character `#'
line 6: syntax error
line 6: invalid character `-'
line 6: invalid character `>'
line 6: invalid character `['
line 6: invalid character `]'
line 6: invalid character `\015'
line 7: invalid character `#'
line 7: syntax error
line 7: invalid character `-'
line 7: invalid character `>'
line 7: invalid character `.'
line 7: invalid character `\015'
line 8: invalid character `#'
line 8: syntax error
line 8: invalid character `\015'
line 9: invalid character `%'
line 9: invalid character `}'
line 9: invalid character `\015'
line 10: invalid character `\015'
line 11: invalid character `\015'
line 12: invalid character `\015'
line 13: invalid character `\015'
line 14: invalid character `\015'
line 15: invalid character `\015'
line 16: invalid character `\015'
line 17: invalid character `\015'
line 18: invalid character `\015'
line 19: invalid character `\015'
line 20: invalid character `\015'
line 21: invalid character `\015'
line 22: invalid character `\015'
line 23: invalid character `\015'
line 24: invalid character `\015'
line 25: invalid character `\015'
line 26: invalid character `\015'
line 27: invalid character `\015'
line 28: invalid character `\015'
line 29: invalid character `\015'
line 30: invalid character `\015'
line 31: invalid character `\015'
line 32: invalid character `\015'
line 33: invalid character `\015'
line 34: invalid character `\015'
line 35: invalid character `\015'
line 36: invalid character `\015'
line 37: invalid character `\015'
line 38: invalid character `\015'
line 39: invalid character `\015'
line 40: invalid character `\015'
line 41: invalid character `\015'
line 42: invalid character `\015'
line 43: invalid character `\015'
line 44: invalid character `\015'
line 45: invalid character `\015'
line 46: invalid character `\015'
line 47: invalid character `\015'
line 48: invalid character `\015'
line 49: invalid character `\015'
line 50: invalid character `\015'
line 51: invalid character `\015'
line 52: invalid character `\015'
line 53: invalid character `\015'
line 54: invalid character `\015'
line 55: invalid character `\015'
line 56: invalid character `\015'
line 57: invalid character `\015'
line 58: invalid character `\015'
line 59: invalid character `\015'
line 60: invalid character `\015'
line 61: invalid character `\015'
line 62: invalid character `\015'
line 63: invalid character `\015'
line 64: invalid character `\015'
line 65: invalid character `\015'
line 66: invalid character `\015'
line 67: invalid character `\015'
line 68: invalid character `\015'
line 69: invalid character `\015'
line 70: invalid character `\015'
line 71: invalid character `\015'
line 72: invalid character `\015'
line 73: invalid character `\015'
line 74: invalid character `\015'
line 75: invalid character `\015'
line 76: invalid character `\015'
line 77: invalid character `\015'
line 78: invalid character `\015'
line 79: invalid character `\015'
line 80: invalid character `\015'
line 81: invalid character `\015'
line 82: invalid character `\015'
line 83: invalid character `\015'
line 84: invalid character `\015'
line 85: invalid character `\015'
line 86: invalid character `\015'
line 87: invalid character `\015'
line 88: invalid character `\015'
line 89: invalid character `\015'
line 90: invalid character `\015'
line 91: invalid character `\015'
line 92: invalid character `\015'
line 93: invalid character `\015'
line 94: invalid character `\015'
line 95: invalid character `\015'
line 96: invalid character `\015'
line 97: invalid character `\015'
line 98: invalid character `\015'
line 99: invalid character `\015'
line 100: invalid character `\015'
line 101: invalid character `\015'
line 102: invalid character `\015'
line 103: invalid character `\015'
line 104: invalid character `\015'
line 105: invalid character `\015'
line 106: invalid character `\015'
line 107: invalid character `\015'
line 108: invalid character `\015'
line 109: invalid character `\015'
line 110: invalid character `\015'
line 111: invalid character `\015'
line 112: invalid character `\015'
line 113: invalid character `\015'
line 114: invalid character `\015'
line 115: invalid character `\015'
line 116: invalid character `\015'
line 117: invalid character `\015'
line 118: invalid character `\015'
line 119: invalid character `\015'
line 120: invalid character `\015'
line 121: invalid character `\015'
line 122: invalid character `\015'
line 123: invalid character `\015'
line 124: invalid character `\015'
line 125: invalid character `\015'
line 126: invalid character `\015'
line 127: invalid character `\015'
line 128: invalid character `\015'
line 129: invalid character `\015'
line 130: invalid character `\015'
line 131: invalid character `\015'
line 132: invalid character `\015'
line 133: invalid character `\015'
line 134: invalid character `\015'
line 135: invalid character `\015'
line 136: invalid character `\015'
line 137: invalid character `\015'
line 138: invalid character `\015'
line 139: invalid character `\015'
line 140: invalid character `\015'
line 141: invalid character `\015'
line 142: invalid character `\015'
line 143: invalid character `\015'
line 144: invalid character `\015'
line 145: invalid character `\015'
line 146: invalid character `\015'
line 147: invalid character `\015'
line 148: invalid character `\015'
line 149: invalid character `\015'
line 150: invalid character `\015'
line 151: invalid character `\015'
line 152: invalid character `\015'
line 153: invalid character `\015'
line 154: invalid character `\015'
line 155: invalid character `\015'
line 156: invalid character `\015'
line 157: invalid character `\015'
line 158: invalid character `\015'
line 159: invalid character `\015'
line 160: invalid character `\015'
line 161: invalid character `\015'
line 162: invalid character `\015'
Target //:deepmind_lab.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 140.965s, Critical Path: 5.95s
INFO: 4 processes: 4 processwrapper-sandbox.
FAILED: Build did NOT complete successfully

**Comment by jingquanliang** [comment]
When i add --sandbox_debug, The result is below!

jql@ubuntu:~/deepmind/lab$ sudo bazel build -c opt //:deepmind_lab.so --sandbox_debug
INFO: Invocation ID: 9f2c1783-1406-47fc-8077-5b2d365ffd8d
INFO: Analysed target //:deepmind_lab.so (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/jql/deepmind/lab/BUILD:62:1: Executing genrule //:lcc_dagcheck failed (Exit 1) process-wrapper failed: error executing command 
  (cd /home/jql/.cache/bazel/_bazel_root/93546fce752155bd98e1ba4319a59e74/execroot/org_deepmind_lab && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
    TMPDIR=/tmp \
  /home/jql/.cache/bazel/_bazel_root/install/3aadb0885b1cb52846820562c39bed63/_embedded_binaries/process-wrapper '--timeout=0' '--kill_delay=15' /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/lburg engine/code/tools/lcc/src/dagcheck.md > "bazel-out/host/genfiles/engine/code/tools/lcc/src/dagcheck.c"')
line 1: invalid character `%'
line 1: invalid character `{'
line 1: invalid character `\015'
line 2: invalid character `#'
line 2: syntax error
line 2: invalid character `\015'
line 3: syntax error
line 3: invalid character `;'
line 3: invalid character `\015'
line 4: invalid character `#'
line 4: syntax error
line 4: invalid character `-'
line 4: invalid character `>'
line 4: invalid character `\015'
line 5: invalid character `#'
line 5: syntax error
line 5: invalid character `-'
line 5: invalid character `>'
line 5: invalid character `['
line 5: invalid character `]'
line 5: invalid character `\015'
line 6: invalid character `#'
line 6: syntax error
line 6: invalid character `-'
line 6: invalid character `>'
line 6: invalid character `['
line 6: invalid character `]'
line 6: invalid character `\015'
line 7: invalid character `#'
line 7: syntax error
line 7: invalid character `-'
line 7: invalid character `>'
line 7: invalid character `.'
line 7: invalid character `\015'
line 8: invalid character `#'
line 8: syntax error
line 8: invalid character `\015'
line 9: invalid character `%'
line 9: invalid character `}'
line 9: invalid character `\015'
line 10: invalid character `\015'
line 11: invalid character `\015'
line 12: invalid character `\015'
line 13: invalid character `\015'
line 14: invalid character `\015'
line 15: invalid character `\015'
line 16: invalid character `\015'
line 17: invalid character `\015'
line 18: invalid character `\015'
line 19: invalid character `\015'
line 20: invalid character `\015'
line 21: invalid character `\015'
line 22: invalid character `\015'
line 23: invalid character `\015'
line 24: invalid character `\015'
line 25: invalid character `\015'
line 26: invalid character `\015'
line 27: invalid character `\015'
line 28: invalid character `\015'
line 29: invalid character `\015'
line 30: invalid character `\015'
line 31: invalid character `\015'
line 32: invalid character `\015'
line 33: invalid character `\015'
line 34: invalid character `\015'
line 35: invalid character `\015'
line 36: invalid character `\015'
line 37: invalid character `\015'
line 38: invalid character `\015'
line 39: invalid character `\015'
line 40: invalid character `\015'
line 41: invalid character `\015'
line 42: invalid character `\015'
line 43: invalid character `\015'
line 44: invalid character `\015'
line 45: invalid character `\015'
line 46: invalid character `\015'
line 47: invalid character `\015'
line 48: invalid character `\015'
line 49: invalid character `\015'
line 50: invalid character `\015'
line 51: invalid character `\015'
line 52: invalid character `\015'
line 53: invalid character `\015'
line 54: invalid character `\015'
line 55: invalid character `\015'
line 56: invalid character `\015'
line 57: invalid character `\015'
line 58: invalid character `\015'
line 59: invalid character `\015'
line 60: invalid character `\015'
line 61: invalid character `\015'
line 62: invalid character `\015'
line 63: invalid character `\015'
line 64: invalid character `\015'
line 65: invalid character `\015'
line 66: invalid character `\015'
line 67: invalid character `\015'
line 68: invalid character `\015'
line 69: invalid character `\015'
line 70: invalid character `\015'
line 71: invalid character `\015'
line 72: invalid character `\015'
line 73: invalid character `\015'
line 74: invalid character `\015'
line 75: invalid character `\015'
line 76: invalid character `\015'
line 77: invalid character `\015'
line 78: invalid character `\015'
line 79: invalid character `\015'
line 80: invalid character `\015'
line 81: invalid character `\015'
line 82: invalid character `\015'
line 83: invalid character `\015'
line 84: invalid character `\015'
line 85: invalid character `\015'
line 86: invalid character `\015'
line 87: invalid character `\015'
line 88: invalid character `\015'
line 89: invalid character `\015'
line 90: invalid character `\015'
line 91: invalid character `\015'
line 92: invalid character `\015'
line 93: invalid character `\015'
line 94: invalid character `\015'
line 95: invalid character `\015'
line 96: invalid character `\015'
line 97: invalid character `\015'
line 98: invalid character `\015'
line 99: invalid character `\015'
line 100: invalid character `\015'
line 101: invalid character `\015'
line 102: invalid character `\015'
line 103: invalid character `\015'
line 104: invalid character `\015'
line 105: invalid character `\015'
line 106: invalid character `\015'
line 107: invalid character `\015'
line 108: invalid character `\015'
line 109: invalid character `\015'
line 110: invalid character `\015'
line 111: invalid character `\015'
line 112: invalid character `\015'
line 113: invalid character `\015'
line 114: invalid character `\015'
line 115: invalid character `\015'
line 116: invalid character `\015'
line 117: invalid character `\015'
line 118: invalid character `\015'
line 119: invalid character `\015'
line 120: invalid character `\015'
line 121: invalid character `\015'
line 122: invalid character `\015'
line 123: invalid character `\015'
line 124: invalid character `\015'
line 125: invalid character `\015'
line 126: invalid character `\015'
line 127: invalid character `\015'
line 128: invalid character `\015'
line 129: invalid character `\015'
line 130: invalid character `\015'
line 131: invalid character `\015'
line 132: invalid character `\015'
line 133: invalid character `\015'
line 134: invalid character `\015'
line 135: invalid character `\015'
line 136: invalid character `\015'
line 137: invalid character `\015'
line 138: invalid character `\015'
line 139: invalid character `\015'
line 140: invalid character `\015'
line 141: invalid character `\015'
line 142: invalid character `\015'
line 143: invalid character `\015'
line 144: invalid character `\015'
line 145: invalid character `\015'
line 146: invalid character `\015'
line 147: invalid character `\015'
line 148: invalid character `\015'
line 149: invalid character `\015'
line 150: invalid character `\015'
line 151: invalid character `\015'
line 152: invalid character `\015'
line 153: invalid character `\015'
line 154: invalid character `\015'
line 155: invalid character `\015'
line 156: invalid character `\015'
line 157: invalid character `\015'
line 158: invalid character `\015'
line 159: invalid character `\015'
line 160: invalid character `\015'
line 161: invalid character `\015'
line 162: invalid character `\015'
Target //:deepmind_lab.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 49.851s, Critical Path: 1.29s
INFO: 60 processes: 60 processwrapper-sandbox.
FAILED: Build did NOT complete successfully

**Comment by jkulhanek** [comment]
+1

**Comment by jkulhanek** [comment]
The error is caused by "bazel build :lcc_dagcheck".

**Comment by jkulhanek** [comment]
The problem is with git checkout style. The files should not be normalized to CRLF. https://github.com/drh/lcc/issues/37

**Comment by tkoeppe** [comment]
Is this a fault on our end?

**Comment by jkulhanek** [comment]
Please check the line ending of LLC source code files and the configuration of your repository. I believe the files are checked out as CRLF and thus it does not work for people with autocrlf = false.

**Comment by jkulhanek** [comment]
No, the problem is not on your end. The files have correct line endings in the repo. Can you confirm @jingquanliang that you did not convert the line endings from LF to CRLF when checking out? I think it is the case and this issue can be closed.

**Comment by tkoeppe** [comment]
I don't think this needs action from our end, right? Feel free to reopen if you have new information.
