### ISSUE TITLE
Calling C API from C++ app: no video frame

### ISSUE THREAD

**Issue by ChelaruViorel** [deepmind/lab#15]
Hi,
I am running the game_main.c from a separate C++ project, without bazel, using the libdmlab.so and the files outputed by bazel in dirpath ./deepmind_lab.runfiles.

It works, meaning it starts the episode, and loops getting reward=0 most of the time, but the video frame is not opening, it's like in headless mode. 
I tried setting this:
if (env_c_api.setting(context, "headless", "false") != 0) {
		sys_error("Failed to apply 'headless=false' setting.");
		exit(1);
	}
but it's not calling exit()...so setting this param does not break the app, but doesn't have any effect either.

What setting should I put to open the video frame ?

Thanks a lot,
Viorel

**Comment by tkoeppe** [comment]
Did you compile the DSO with `--define headless=osmesa`? Headlessness is a build-time property, not a runtime property. You will also need to make sure that the asset data is in the correct directory relative to the DSO (the data in the `baselab` directory).

**Comment by ChelaruViorel** [comment]
I've built it using 
bazel build :deepmind_lab.so --define headless=glx 
as in the documentation, I didn't knew this is the spot that makes the difference.

Now, I've built it using
bazel build :deepmind_lab.so --define headless=false
and it works.

Thanks !
