### ISSUE TITLE
How to correct update the pre-built maps

### ISSUE THREAD

**Issue by Cranial-XIX** [deepmind/lab#154]
what I did:
1) modified the .map file under assets/maps/src
2) bazel build -c opt //:map_assets
3) unzip -d assets/maps/built/ bazel-bin/baselab/maps/nav_maze_static_01.pk3
4) bazel build -c opt //:deepmind_lab.so
But I found that the nav_maze_static_01 remained unchanged. I wonder where I did it wrong and what is the correct way of updating a pre-built map?

Really thank you very much in advance.

**Comment by charlesbeattie** [comment]
With the latest version try:
```
3a. unzip -d /tmp/ bazel-bin/baselab/nav_maze_static_01.pk3
3b. mv -v /tmp/maps/* assets/maps/built/ 
```

**Comment by tkoeppe** [comment]
@Cranial-XIXL: Does that work for you?

**Comment by Cranial-XIX** [comment]
Thanks very much. @tkoeppe Yes, it works.
