### ISSUE TITLE
Is there a way to get the coordinates of the walls/mapsize? 

### ISSUE THREAD

**Issue by eabeUO** [deepmind/lab#155]
I am trying to create an random agent to walk around an environment but avoid walls.  To do this I was going to create a sequence of actions depending on the location of the agent using DEBUG.POS.TRANS.  However, I have not been able to figure out how the coordinates of the map are created.  The output of DEBUG.POS.TRANS coordinates are offset and I am not sure where this offset comes from.  Any help with this is appreciated.  Thank you.

**Comment by charlesbeattie** [comment]
`DEBUG.POS.TRANS` is the absolute location of the Agent in world units.
Grid squares are 100 x 100 units.
The following command will print the location every frame.
`bazel run //:game -- -l contributed/dmlab30/explore_goal_locations_small -o DEBUG.POS.TRANS`
You should able to navigate to a corner at `{150, 150, 25.125000}`.
And the opposite corner `{950, 950, 25.125000}`.

**Comment by charlesbeattie** [comment]
Ah The map size is the ascii grid size * 100 including walls.

**Comment by NguyenHaiAnh11** [comment]
Im not sure I understand this. 
How do these units work exactly, where is the origin, and what is the relation with regards to DEBUG.CAMERA.TOP_DOWN? How do the height and width parameter of DEBUG.CAMERA.TOP_DOWN influence the grid units and agent position?
Thanks.

**Comment by eabeUO** [comment]
The origin is in the top left of the generated map.  For example if the map is something like: (The quotes are just there so it would show up in the text)

'****
'*   *'
****'

Each star is a 100x100 square so the origin is in the top left start. The walls however take up space so you cannot actually go to the (0,0) position

The DEBUG.CAMERA.TOP_DOWN have coordinates of x,y and height.  The DEBUG.CAMERA.TOP_DOWN does not influence the size of the arena, that is set when making the map.  
What you can do is use DEBUG.CAMERA.TOP_DOWN to get out the top down view. You have to position the camera to view a particular area.  I was just testing out a simple square arena so I placed it in the center and high enough to view the entire arena.  I think the settings you override are in the lua file for the arena. 
If you have this in the lua script I think this is what can change the top down camera:
local setting_overrides = require 'decorators.setting_overrides'

setting_overrides.decorate{
  api = api,
  apiParams = {episodeLengthSeconds = 10*60, camera = {-120, -120, 750}}, -- This is the parameter to change
  decorateWithTimeout = true,
  enableCameraMovement = true
}
