### ISSUE TITLE
level cache with Python API

### ISSUE THREAD

**Issue by ninji3** [deepmind/lab#158]
When I follow the instructions to create a level cache with the Python API as described in the [Python API doc](https://github.com/deepmind/lab/blob/master/docs/users/python_api.md) it throws up an IOError like so:

```
(tfgpu) jbolick@ee-tik-vm007:~/120GBext/lab/python$ python random_agent.py
Traceback (most recent call last):
  File "random_agent.py", line 232, in <module>
    args.record, args.demo, args.demofiles, args.video)
  File "random_agent.py", line 183, in run
    env.reset()
  File "random_agent.py", line 52, in write
    shutil.copyfile(pk3_path, path)
  File "/local/home/jbolick/120GBext/anaconda3/envs/tfgpu/lib/python2.7/shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/tmp/cache/empty_room_noaas_5b1ea3a9cefe6533eb495215852407f4'
```

To rule out any other mistakes I then tried to implement the functionality in your random_agent.py by copying the code for the LevelCache class and creating an instance of it in the run function, i.e.:

```
  cache=LevelCache()
  env = deepmind_lab.Lab(level, ['RGB_INTERLEAVED'], config=config, level_cache=cache)
```

Am I missing something obvious here? Thanks for your help.

**Comment by tkoeppe** [comment]
Could you please double-check that the cache directory is actually writable by the user as which the process is running?

**Comment by ninji3** [comment]
Ok I figured out a solution. Apparently, `shutil.copyfile()` does not create a file for me at the specified path (which is a bit weird), therefore I have to create an empty file beforehand:

```
  def write(self, key, pk3_path):
    path = os.path.join(self._cache_dir, key)

    if not os.path.isfile(path):
      # Copy the cached file DeepMind Lab has written to the cache directory.
      os.mknod(path)
      shutil.copyfile(pk3_path, path)
```
Your advice to check if it actually ACTUALLY exists already was enough to simply create the file by hand and see what happens :P I was a bit confused since I also at one point managed to pass the cache directory as the runfile path which obviously gave me all kinds of errors.

As far as I'm concerned you can close the issue or change the doc accordingly if you can verify this as a general problem. Thanks again!

**Comment by tkoeppe** [comment]
No problem! :-)
