### ISSUE TITLE
Cannot use .reset() method for dmlab30 in python package 

### ISSUE THREAD

**Issue by Shengyu-Feng** [deepmind/lab#161]
After I've installed python package for deepmind_lab, I find errors will appear whenever I try to use .reset() method for dmlab30 environment, which doesn't appear for other levels. 

 Here's my code 
`import deepmind_lab`
`lab = deepmind_lab.Lab('contributed/dmlab30/language_select_described_object',['RGBD'],{'fps':'30','height':'84','width':'84'})`
`lab.reset()`

and the error message says:

> Traceback (most recent call last):
  File "<stdin\>", line 1, in <module\>
RuntimeError: Failed to start environment - "First argument must be an object of type: 'deepmind.lab.RandomView'
Did you forget to use ':' when calling?
Argument received: '5.11232e+08'
stack traceback:
        [C]: in function 'seed'
        .../deepmind_lab/baselab/game_scripts/common/random.lua:36: in function 'seed'
        .../baselab/game_scripts/factories/language/factory.lua:161: in function 'start'
        ...mind_lab/baselab/game_scripts/decorators/timeout.lua:58: in function <...mind_lab/baselab/game_scripts/decorators/timeout.lua:56>"

**Comment by charlesbeattie** [comment]
Should it be:

`lab:reset()`

?

**Comment by charlesbeattie** [comment]
Sorry I'm in Lua land. I'll take another look.  Does it require a seed
being passed in?

**Comment by Shengyu-Feng** [comment]
I've tried it and it does not work, either. Besides, I think .reset() works for other levels like 'tests/empty_room_test' in the example code
