### ISSUE TITLE
can't find Lua modules   dmlab.system.*

### ISSUE THREAD

**Issue by KeviKai** [deepmind/lab#162]
I want to test the Lua scripts in lua_tests, like colors_test.lua, but I could not find the dmlab.system.* modules, such as dmlab.system.game.  where can I find those modules?

**Comment by tkoeppe** [comment]
Those modules are installed by the native code. They're not written in Lua, but only available in the Lua runtime that's run by the DeepMind Lab: https://github.com/deepmind/lab/blob/master/deepmind/engine/context.cc#L740-L769

I think it might be nice to have a standalone Lua interpreter that provides those same modules; @charlesbeattie may have some opinions on that, too.

**Comment by tkoeppe** [comment]
I'm not sure if there's anything for us to do here. Please reopen if you have a concrete plan.
