### ISSUE TITLE
Unable to bazel build deepmind_lab.so

### ISSUE THREAD

**Issue by hecong97** [deepmind/lab#168]
I met the problem when run the command"bazel build deepmind_lab.so".

### ERROR: /home/hecong/lab/BUILD:923:1: error loading package '@com_google_absl//absl/container': Unable to find package for @rules_cc//cc:defs.bzl: The repository '@rules_cc' could not be resolved. and referenced by '//:dmlab_so_loader'
ERROR: Analysis of target '//:deepmind_lab.so' failed; build aborted: error loading package '@com_google_absl//absl/container': Unable to find package for @rules_cc//cc:defs.bzl: The repository '@rules_cc' could not be resolved.
INFO: Elapsed time: 0.194s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 7 targets configured)
    currently loading: @com_google_absl//absl/container

I have never seen the question before reconfiguring the server.

**Comment by tkoeppe** [comment]
This was fixed by ae2d292f3ee08205058c0c604fd996b204450e20.
