### ISSUE TITLE
Is it possible to render image in vnc environment?

### ISSUE THREAD

**Issue by zhengwx11** [deepmind/lab#17]
by running `~/lab$ bazel run :random_agent --define headless=false`, a graphic interface is obtained when I use physical screen, mouse and keyboard. 

Is there any way to run it under vnc viewer?
I've tried but got a 'GlxBadRenderRequest'.

**Comment by frankcarey** [comment]
I had similar issues See https://github.com/deepmind/lab/issues/22#issuecomment-269807210

**Comment by chankim** [comment]
I tried building deepmind lab and running it. I'm doing it on vnc window. When I run 'bazel run :game --define headless=false -- --level_script tests/demo_map' I see a window pop up saying 'GLimp_Init()-could not load OpenGL subsystem. See "/home/ckim/.deepmind_lab/baselab/crashlog.txt" for details.' Has it something to do with vnc? I searched the web but couldn't figure out yet.

**Comment by tkoeppe** [comment]
@chankim: The `headless=false` build probably requires OpenGL, which may not work via VNC. Try the `headless=osmesa` build (or rebuild your SDL library with osmesa?).

**Comment by chankim** [comment]
Ok, Thank you for the information.
Chan

**Comment by tkoeppe** [comment]
I assume this is settled? Please reopen if not.
