### ISSUE TITLE
Python API for environment manipulations

### ISSUE THREAD

**Issue by uahic** [deepmind/lab#172]
Hi there,

I've just installed the lab for the first time without errors and it looks pretty nice. Now, I'd like to work on navigation/RL/grid-cell experiments. However, I am not familiar with LUA yet and looked through the game_scripts folder, leaving me with the question if there are any plans to extend the python API such that controlling the environment with python only will be possible?

I guess for the moment that Quake3 itself is calling the LUA scripts and its hard t o use something else but I could imagine having the chance for manipulations between env.step()-calls would be possible

**Comment by tkoeppe** [comment]
It's unlikely we'll implement such a thing. Bear in mind that the Python API is essentially just "an example" of what you can do with DeepMind Lab. The principal API is the one exposed through the EnvCAPI struct, and that's all about the "RL environment": actions, observations, stepping. The details of the environment are not part of this API, deliberately so.

You could of course make any number of extensions yourself in a fork. But I'm not sure if you really want to patch things through to the agent side.

Please do know that we have an as-of-yet unpublished "properties" extension, by which agents can query and set abstract "properties" (e.g. query the FPS value), and one feature of this system is that _writable_ properties (i.e. the ones that the agent can _set_) can modify the running environment. If this particular system sounds adequate for your needs, we can try and get that out. But that's a far cry from a "general way to programmatically describe the environment" in the way the Lua scripts do.

**Comment by uahic** [comment]
Fair enough! Thank you for your answer. I will sit down then and learn Lua / study the example scripts ;)
