### ISSUE TITLE
Unable to build python interface

### ISSUE THREAD

**Issue by TPrivat** [deepmind/lab#174]
I am trying to build deepmindlab.so but keep getting the same error. 

`bazel build -c opt //:deepmind_lab.so`

I am on Ubuntu 18.04 & bazel 0.14.0. It says it should run out of the box on ubuntu. I tried updating the python.BUILD file like build.md expains but that does not help either. In-case I simply messed something up I deleted and recloned the repo and still got the same message. Im new to github and bazel so any help is appreciated. 

Run command & Error Message:
`~/lab$ bazel build -c opt //:deepmind_lab.so
Starting local Bazel server and connecting to it...
......
ERROR: /home/taylor/.cache/bazel/_bazel_taylor/fc55910dca61cd13c193e109fb922fb7/external/python_system/BUILD.bazel:6:1: no such target '@bazel_tools//tools/python:PY2': target 'PY2' not declared in package 'tools/python' defined by /home/taylor/.cache/bazel/_bazel_taylor/fc55910dca61cd13c193e109fb922fb7/external/bazel_tools/tools/python/BUILD and referenced by '@python_system//:python'
ERROR: /home/taylor/.cache/bazel/_bazel_taylor/fc55910dca61cd13c193e109fb922fb7/external/python_system/BUILD.bazel:6:1: no such target '@bazel_tools//tools/python:PY3': target 'PY3' not declared in package 'tools/python' defined by /home/taylor/.cache/bazel/_bazel_taylor/fc55910dca61cd13c193e109fb922fb7/external/bazel_tools/tools/python/BUILD and referenced by '@python_system//:python'
ERROR: /home/taylor/.cache/bazel/_bazel_taylor/fc55910dca61cd13c193e109fb922fb7/external/python_system/BUILD.bazel:6:1: no such target '@bazel_tools//tools/python:PY2': target 'PY2' not declared in package 'tools/python' defined by /home/taylor/.cache/bazel/_bazel_taylor/fc55910dca61cd13c193e109fb922fb7/external/bazel_tools/tools/python/BUILD and referenced by '@python_system//:python'
ERROR: /home/taylor/.cache/bazel/_bazel_taylor/fc55910dca61cd13c193e109fb922fb7/external/python_system/BUILD.bazel:6:1: no such target '@bazel_tools//tools/python:PY3': target 'PY3' not declared in package 'tools/python' defined by /home/taylor/.cache/bazel/_bazel_taylor/fc55910dca61cd13c193e109fb922fb7/external/bazel_tools/tools/python/BUILD and referenced by '@python_system//:python'
ERROR: /home/taylor/.cache/bazel/_bazel_taylor/fc55910dca61cd13c193e109fb922fb7/external/python_system/BUILD.bazel:15:16: Configurable attribute "includes" doesn't match this configuration: Internal error, Python version should be one of PY2 or PY3
ERROR: Analysis of target '//:deepmind_lab.so' failed; build aborted: 

/home/taylor/.cache/bazel/_bazel_taylor/fc55910dca61cd13c193e109fb922fb7/external/python_system/BUILD.bazel:15:16: Configurable attribute "includes" doesn't match this configuration: Internal error, Python version should be one of PY2 or PY3
INFO: Elapsed time: 1.894s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (55 packages loaded)`

Let me know if there are any other details needed that I have not given

**Comment by tkoeppe** [comment]
Bazel 0.14 is very very old, can you please try again with a contemporary version?

**Comment by TPrivat** [comment]
Okay updating bazel seemed to fix the python problem, though a new problem has appeared.

```
C++ compilation of rule '//:deepmind_lab.so' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 39 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
python/dmlab_module.c:26:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
```

**Comment by tkoeppe** [comment]
Yes, you may need to edit the `python.BUILD` file to set the path to your local Python library correctly. This file isn't auto-generated and instead just contains one particular configuration that may not apply to your machine; most likely the version number needs to be adjusted.

**Comment by TPrivat** [comment]
Awesome, Build was successful. Thanks for the help!
