### ISSUE TITLE
How to utilize GPU in deepmind lab?

### ISSUE THREAD

**Issue by Jthon** [deepmind/lab#176]
I was wondering how to use GPU for training in Deepmind lab effectively, I mean when running the online Reinforcement Learning Algorithm like A3C, the agent is using a lot of time interacting with the enviroment and I want to know how to speed up the interaction process. Thank you in advance.

**Comment by tkoeppe** [comment]
We have multiple OpenGL backends: Mesa, GLX, EGL. Maybe one of those will let you use your GPU?

**Comment by Jthon** [comment]
Thank you @tkoeppe ! But when I want to use GLX for renderer, I got an error "Failed to open library ! - ./libdmlab_headless_hw.so ./libdmlab_headless_hw.so: undefined symbol : eglMakeCurrent" , so am I making some mistakes when installing OpenGL?

**Comment by tkoeppe** [comment]
See https://github.com/deepmind/lab/blob/master/BUILD#L892-L900.

To make "hw" mean GLX, you need to build with `--define graphics=osmesa_or_glx`, otherwise it picks the default of EGL (https://github.com/deepmind/lab/blob/master/BUILD#L911).

**Comment by Jthon** [comment]
I solved this problem, thank you for your advice! @tkoeppe
