### ISSUE TITLE
How to build new maps

### ISSUE THREAD

**Issue by XUChengguang** [deepmind/lab#179]
Hi,

I am trying to build new maps from some personal written .txt files. Could you please give me any instructions to do that?

**Comment by tkoeppe** [comment]
You can look at the compile_map.sh script, which provides a frontend for the "text map" map encoding, in case that's what you're after. Beyond that, you can also directly call q3map2 and bspc on your own .map files, just as for regular QuakeIII, and then use the resulting .bsp files directly.

**Comment by cgxuvector** [comment]
I got it. Thanks a lot!

**Comment by tkoeppe** [comment]
Great!
