### ISSUE TITLE
RGBD frame contains strange objects in the depth channel.

### ISSUE THREAD

**Issue by ChelaruViorel** [deepmind/lab#18]
Hi,
I am using the C API, and I got a frame + depth by getting the observation RGBD_INTERLACED.
But the depth is strange, because it contains 2 squares at the bottom with depth information, which I think are not useful at all, and also I don't think are part of the environment. I think only the walls and the apple should be the environment, so only they should have depth information....so I think this is a bug, but if it's not, please explain me the existence and meaning of these 2 objects in the depth information.

I attached the RGB frame, the depth frame, and the inverted depth frame.

Thanks a lot,
Viorel

![frame](https://cloud.githubusercontent.com/assets/6955503/21438300/e6f84166-c890-11e6-8189-96d62a0d8e85.png)

![depth](https://cloud.githubusercontent.com/assets/6955503/21438301/ed32bdcc-c890-11e6-8667-af801d165024.png)

![depth_inverted](https://cloud.githubusercontent.com/assets/6955503/21438310/f18c4c9e-c890-11e6-85db-9d23ea20ab5c.png)

![depth_inverted2](https://cloud.githubusercontent.com/assets/6955503/21438314/f6088210-c890-11e6-9def-26a7509dd379.png)

**Comment by charlesbeattie** [comment]
This is working as intended as they are 3D rendered parts of the UI.
You will be able to remove these artefacts by editing assets/q3config.cfg:
Change the line:
`seta cg_draw3dIcons "1"`
To:
`seta cg_draw3dIcons "0"`

**Comment by ChelaruViorel** [comment]
thanks

**Comment by frankcarey** [comment]
note that the top of assets/q3config.cfg says:

`// generated by quake, do not modify`
https://github.com/deepmind/lab/blob/master/assets/q3config.cfg#L1

**Comment by tkoeppe** [comment]
@frankcarey: That's probably meaningless. We modified the engine so that it would not (by default) re-write the current configuration to disk, so that the config file is effectively stable.

**Comment by tangbohu** [comment]
Would you mind sharing how you modify the engine?
