### ISSUE TITLE
Successfully building and installing via pip, but issues remain (Conda based setup)

### ISSUE THREAD

**Issue by osdf** [deepmind/lab#183]
Hi,
after adapting the bazel files along #178 (python3.7 in my case), the following works:

* `bazel build -c opt --python_version=PY3 //python/pip_package:build_pip_package`
*  `./bazel-bin/python/pip_package/build_pip_package /tmp/dmlab_pkg`
*  `pip install /tmp/dmlab_pkg/deepmind_lab-1.0-py3-none-any.whl --force-reinstalľ`

A short test also 'works', `bazel run -c opt //:python_random_agent`, but always produces
0 reward. Testing it with graphics output, `bazel run :python_random_agent --define graphics=sdl -- --length=10000 --width=640 --height=480` works in the sense that graphics is displayed, but everything is mirrored! However, when running `bazel run :game -- --level_script=tests/empty_room_test --level_setting=logToStdErr=true` the graphics output is correct.

Trying to run the test from the `build.md` page, `bazel test -c opt //python/tests:python_module_test` fails, citing a missing `<Python.h>`? Finally, running the last example from (https://github.com/deepmind/lab/blob/master/python/pip_package/README.md) first produces an error, complaining about the missing `dm_env` package. Resolving this with a pip install the makes this example run, but it doesn't produce the  return of 11 (it always gets 0 return, trying various seeds).

So while things seem to run, there still are problems. What am I doing wrong here?

**Comment by tkoeppe** [comment]
Most of this sounds working as intended: the random agent is unlikely to produce a reward. "Mirrored" presupposes a chironormative worldview that is not warranted (see #104); who says it's not _you_ who are the wrong way round? The :game binary performs special shuffling that the learning agent doesn't care to do.

For the test, can you also pass `--python_version=PY3`? I don't know your platform details, but you can look at the Travis script for an example setup that works, and you can adjust your python.BUILD file appropriately according to the location of your Python.h for the desired Python version.

I'm not sure the seeding is reliably; it depends on details of the C++ standard library implementation and may not be as useful as we thought. If the environment is returning plausible observations (i.e. screen images), then it's working, regardless of the specific reward you get. Maybe try some other level that gives rewards more easily and see if you can get any?

**Comment by tkoeppe** [comment]
The requiremet of `dm_env` came in accidentally when I intended to add _optional_ dm_env bindings. That's not great, and we should really make that dependency optional. Feel free to undo the changes from https://github.com/deepmind/lab/commit/86557ab0706fae479c34150da4de38a2639d44ce#diff-96bc5ad904f29be97a5936e65e3b12d7 locally for the time being!

**Comment by tkoeppe** [comment]
The lack of reward in the demo actually has a different, simpler explanation: the "empty_room_test" map doesn't produce any rewards. The readme was written originally with a different (unreleased) map, which did result in rewards, but when we changed the map, we didn't update the bit about the rewards.

I'll see if we can add a new, simple demo level with rewards. Thanks for raising this!

**Comment by tkoeppe** [comment]
The demo reward should now have a functioning example in 9c1e1b9eb0ee241d07066a81edf3de8d33e4a621.

**Comment by osdf** [comment]
Hi Thomas, thanks for your time and help!! The demo works as intended with the fix. I wasn't able to get forward with the problem of running python tests, even with ``python_version=PY3`` it still complains about the missing ``Python.h`` (which is found when building the package...). I'm probably still missing something here, I'll come back to it later.

**Comment by tkoeppe** [comment]
You could perhaps try a `find` command such as the one at https://github.com/deepmind/lab/blob/dae25c739fd6da50190c7afaf9c76c615dc5364f/.travis.yml#L25 (suitably modified to start at, say, `/usr`) to find all the relevant local libraries...
