### ISSUE TITLE
Loading different map for each episode

### ISSUE THREAD

**Issue by cgxuvector** [deepmind/lab#185]
Hi

I am doing some research using DeepMind Lab (nice work:). However, I need to load a different map for each episode. I tried to solve this by random selecting one map in the api:start() and api:nextMap() functions in .lua file.  It sort of works. I observe a different map for each episode. However, using that strategy, I don't know which map is used for the current episode in my main.py script. 

I try to write api:start(maze_size, seed) in .lua file and env.reset(maze_size, seed) in main.py. And I hope the parameters can transfer magically. However, it seems these two functions are not connected in this easy fashion. 

Could you please give me some suggestions about how to realize this or transferring parameters from .py to .lua?

Best,

**Comment by charlesbeattie** [comment]
Hi, The seed is indeed remixed to ensure good randomness and to switch between testing and training.
In this case you may want to use the property api.
See python/tests/properties_test.py
and game_scripts/levels/tests/properties_test.lua
To see how they work.

This allows reading and writing properties to the environment while it is running.

**Comment by cgxuvector** [comment]
Thanks for your reply. I understand it seems impossible to use lab.reset() to pass the desired seed. Let me explain my situation in more details:
1. I find some predefined txt files(from another repo) that define the txt level. For example, one .txt file looks like followings:
"*****"
"* * G*" 
"* *  *"
"*P  *"
"*****"
2. I build the txt files (.aas and .bsp files) and write a .lua file to construct the 3D maze environment. Each customized map file is named as "map_size_seed" (Following the name in the raw repo). Therefore, my .lua file is written as follows:
-- serve as libraries loader
local pickups = require 'common.pickups'
local custom_observations = require 'decorators.custom_observations'
local timeout = require 'decorators.timeout'
local random = require 'common.random'

-- Loads a random maze with thick walls.
-- Apples are placed near the goal and spawn points away from it.
-- Timeout is set to 3 minutes.
local api = {}

function api:createPickup(className)
  return pickups.defaults[className]
end

function api:start()
    api._maze_size = random.uniformInt(5, 13)
    api._seed = random.uniformInt(1, 20)
end

function api:nextMap()
  return 'map_' .. api._maze_size .. '_' .. api._seed
end

custom_observations.decorate(api)
timeout.decorate(api, 5 * 60)
return api

As you can see, the randomly generated maze _size_ and _seed_ are independent with my main.py script because I can't pass any parameters to the .lua file from my main.py script. Therefore, how can I define the maze _size_ and the random _seed_ and pass these two parameters to the .lua file?

One more question, it is possible to obtain an image observation from a specific position. For example, I know a position (100, 100, 100) in the 3D maze environment, can I retrieve the observation at that position?

best,

**Comment by charlesbeattie** [comment]
For the camera question the answer is yes. 
Take a look at game_scripts/levels/tests/custom_view.lua
for an example.

I think you are failing to seed the random number generator in start.
The seed doesn't get passed as is so you can't switch on it but you should definitely be able to do what you want to do:
 
```Lua
function api:start(episode, seed)
  random:seed(seed)
  api._maze_size = random.uniformInt(5, 13)
  api._seed = random.uniformInt(1, 20)
end

```

**Comment by cgxuvector** [comment]
Thanks for your kind replay. I think I have already solved the question related to the maps based on your suggestions.

Just to be clear about the camera question, I have read the custom_view.lua file. Here is my understanding
```
function look()
          local info = game:playerInfo()
          local pos = info.eyePos
          local look = info.angles
          local buffer = game:renderCustomView{

                    width = SHAPE.width,
                    height = SHAPE.height,
                    pos = pos,
                    look = look,
                   renderPlayer = false,
          }
          return buffer:transpose(3, 2):transpose(2, 1):reverse(2):clone()
end
```
If I want to observe position {100, 100, 30}, then I just set the variable pos (info.eyePos) to be
 {"100", "100", "30"} right?
In addition, could you give  me some intuition about the line _return buffer ...._? It seems for the new version. I don't need to reverse the observation

Best,

**Comment by charlesbeattie** [comment]
Look in this case will use the players position and eye rotations.
You can just change `pos = pos` to `pos = { x, y, z}` and `look = look` to `look={pitch, yaw, roll}`
Where pitch, roll, yaw angles are in degrees, and. x, y, z are in game units.

**Comment by cgxuvector** [comment]
Awesome! Thanks a lot!

**Comment by cgxuvector** [comment]
Hi, 

Sorry to bother you again. I am wondering whether it is possible to fix the texture of the walls, floors, and the sky. (i.e. wall are always green, the floors are always yellow, and the sky is always blue.). Recall I currently load different mazes in different episodes with random textures.

I know how to do it if I use the make_map() function with a defined map in the lua file. However, my case is sort of different. I load the map from the pre-built .ass and .bsp files. Therefore, I guess there are some pre-generated textures for the floors, walls, and the sky. Can I override them in the lua file? (i.e. fix the theme to be one of the provided themes)

Otherwise, could you please tell me how to convert a ".txt" map into a ".map" map?
For example, I can create a text file that describes a map named "test_map.txt". Can I convert to a "text_map.map" file?

Best,

**Comment by cgxuvector** [comment]
I just figured out a way to do it. Never mind.
