### ISSUE TITLE
Compiling Text Map into .map or .bsp file

### ISSUE THREAD

**Issue by dmklee** [deepmind/lab#186]
I would like to train an agent on a large set of randomly designed maps.  So I have generated a set of such maps as txt files.  However, I find that compiling each map during training is slow and I would like to compile the maps offline.  

Could you please point me toward any functions that could be used to convert txt files into map or bsp files? 

In #179, someone referenced "compile_map.sh" but that is only for map -> bsp conversion.  I also saw that "translate_text_level.cc" is able to perform txt -> map conversion.  I was hoping there might be some access to this functionality in lua.  

Thank you for your help!

**Comment by tkoeppe** [comment]
Ah, that's right, we never published the command line interface for the text-level compilation.

Essentially you just need to call `TranslateTextLevel` here with suitbale parameters: https://github.com/deepmind/lab/blob/master/deepmind/level_generation/text_level/translate_text_level.h#L124-L129

But there isn't a free-standing executable that does just that. You could copy the resulting files out while your environment is running, or you could write a small tool yourself. Let me know if you need help with that (but do give it a try yourself).

**Comment by dmklee** [comment]
Thank you very much for the quick response!  

I opted for what seemed like the easier solution, which was to create a copy of compiled maps while the environment is running.  

For anyone interested in more details:
In the example script, "make_map_from_text.lua", the make_map.makeMap{} call compiles the map into a .bsp file and places it in a temporary directory.  As long as the environment is still running, you can copy the bsp file to another directory.  The temporary directory is named like "dmlab_temp_folder_*" and is located in your tmp directory.  Inside this folder is a ".pk3" which includes the bsp file (and aas file if requested).  

My implementation can be found here:
https://github.com/dmklee/rl_in_dmlab/tree/master/precompile_maps

**Comment by tkoeppe** [comment]
Great, glad that works, and thanks for reporting!
