### ISSUE TITLE
Speeding up the DMLab simulation process

### ISSUE THREAD

**Issue by jafphd** [deepmind/lab#189]
I am running a simulation on a 8 core CPU computer. It will take ~200 hs to finish. Basically, I have 8 threads running simultaneously and each one opens a DeepMind lab session and process several iterations. 

My question is whether there is a way to make the process of simulating the trajectories in DeepMind lab faster in computational terms? In other words, can we run the DeepMind lab in terms of computer cycles rather than waiting the specified secs? (the parameter  episodeLengthSeconds  indicates "Episode length in seconds"). But, changing that parameter to a small value  (e.g. episodeLengthSeconds = 0.01) does not seem to be a solution.

There is not any indication of how to speed up that simulation process at: https://github.com/deepmind/lab/blob/master/docs/developers/minimal_level_tutorial.md

Thank you very much in advance!

**Comment by charlesbeattie** [comment]
`episodeLengthSeconds` is a proxy for setting the number of frames to run the simulation for.
1 second = 60 frames of simulation. Each step of the simulation advances the in-game timer by 1/60th of a second (~16 milliseconds). The wall-time (actual time passed) will be different depending on your hardware.

**Comment by jafphd** [comment]
Thanks @charlesbeattie for the clarification. I will play around more with that variable and see whether I can speed up the simulation somehow. Best!

**Comment by charlesbeattie** [comment]
`episodeLengthSeconds` will not affect the simulation speed it only affect the number of steps an agent will have to perform a task. I would look to ensuring that you build with optimisations and and maybe GPU support if you have one.

**Comment by jafphd** [comment]
I see. Regarding the optimization issue, that is exactly what I am currently working on. The simulation is working fine with some optimizators, but relatively slow as I described. Unfortunately, I do not have any GPU support yet, for which I was looking for a way to speed it up based on CPU. Thanks!
