### ISSUE TITLE
Error:/compile_map.sh  

### ISSUE THREAD

**Issue by ElectricSquirrel** [deepmind/lab#19]
Extracting Bazel installation...
..........................................
INFO: Found 1 target...
ERROR: /media/Data/UbuntuFiles/Document/lab/deepmind/level_generation/BUILD:6:1: failed to create symbolic link 'deepmind/level_generation/compile_map_sh': file 'deepmind/level_generation/compile_map.sh'

**Comment by tkoeppe** [comment]
I'm afraid there's not enough context here to allow for any reasonable analysis.
