### ISSUE TITLE
The top-down view of the environment

### ISSUE THREAD

**Issue by hecong97** [deepmind/lab#190]
In the top-down view of the nav_maze_static_01 maze and the nav_maze_random_goal_01maze, the goal is always invisible. How can I make the goal visible or get the goal location by code in random-goal environment?
[
![map0](https://user-images.githubusercontent.com/15817922/83220513-c1200b80-a1a5-11ea-85b6-bbc7cc1ed5f0.jpg)
](url)

**Comment by hecong97** [comment]
I can get the goal location by the change the random_goal_factory.lua,but I can't find why the goal is invisible

**Comment by hecong97** [comment]
Add the 'hasAltCameras':'true' in init can solve the question

**Comment by rokhmatf** [comment]
hi, how did you manage to display it like that ?
