### ISSUE TITLE
An error occurs when running a test

### ISSUE THREAD

**Issue by sunmoon9898** [deepmind/lab#2]
the platform is ubuntu 16.04, bazel 0.32.

$bazel run :python_module_test --define headless=glx

INFO: Found 1 target...
Target //:python_module_test up-to-date:
  bazel-bin/python_module_test
INFO: Elapsed time: 0.148s, Critical Path: 0.00s

INFO: Running command line: bazel-bin/python_module_test
...Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused

(zenity:28528): Gtk-WARNING **: cannot open display:
ERROR: Non-zero return code '3' from command: Process exited with status 3.

**Comment by tkoeppe** [comment]
Are you running this remotely? You need an X server for GLX. Does the osmesa version work?

**Comment by sunmoon9898** [comment]
thanks tkoppe. you are right, I run it locally, it works now.
