### ISSUE TITLE
Download from https://mirror.bazel.build/pypi.python.org/packages/source/s/six/six-1.15.0.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

### ISSUE THREAD

**Issue by splatboy20081** [deepmind/lab#200]
Download from https://mirror.bazel.build/pypi.python.org/packages/source/s/six/six-1.15.0.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

cmd: bazel run :game

**Comment by tkoeppe** [comment]
Is this actually a problem? There's a second URL provided that should work, doesn't that work? The Bazel mirror isn't _guaranteed_ to work, it's populated in a somewhat obscure way.

**Comment by splatboy20081** [comment]
It fails the build, doesn't give any options

**Comment by tkoeppe** [comment]
Does the other URL (given in the WORKSPACE file) work? If so, try deleting the first ULR?

**Comment by splatboy20081** [comment]
I'll try that

**Comment by splatboy20081** [comment]
where exactly?

**Comment by splatboy20081** [comment]
nvm, found it.

**Comment by splatboy20081** [comment]
![image](https://user-images.githubusercontent.com/64037464/96299828-7c0c4280-0fa9-11eb-986a-ed4f11ad7804.png)
Now it can't find SDl.

**Comment by tkoeppe** [comment]
Please see the general build instructions. You need to install SDL on your system, and possibly adjust the `sdl.BUILD` file to contain the correct paths.
