### ISSUE TITLE
When I build deepmind_lab.so, the error are raised. Could you do me a favor?

### ISSUE THREAD

**Issue by XqWang3** [deepmind/lab#205]
bazel build :deepmind_lab.so
ERROR: /home/ubuntu/wangxq/projects/lab/BUILD:897:2: //:python_game_py2: no such attribute 'python_version' in 'py_binary' rule
ERROR: /home/ubuntu/wangxq/projects/lab/BUILD:897:2: //:python_game_py3: no such attribute 'python_version' in 'py_binary' rule
ERROR: error loading package '': Package '' contains errors

**Comment by tkoeppe** [comment]
Here too, please try this with a recent Bazel version.
