### ISSUE TITLE
I meet the error when bazel build -c opt //:deepmind_lab.so

### ISSUE THREAD

**Issue by XqWang3** [deepmind/lab#206]
bazel build -c opt //:deepmind_lab.so
ERROR: /home/ubuntu/zz/projects/lab/WORKSPACE:146:1: //external:tree_archive: no such attribute 'repo_mapping' in 'http_archive' rule
ERROR: Skipping '//:deepmind_lab.so': error loading package 'external': Package 'external' contains errors
WARNING: Target pattern parsing failed.
ERROR: error loading package 'external': Package 'external' contains errors

**Comment by tkoeppe** [comment]
Which bazel version are you using, and could you try a recent one?

>

**Comment by XqWang3** [comment]
> Which bazel version are you using, and could you try a recent one?
> […](#)

the version of bazel is 0.19.2, because the version of tf installed is 1.13.1. Do I need to upgrade the version of Bazel?

**Comment by tkoeppe** [comment]
Please do, the current version is 4.0.0. You can get self-contained binaries from GitHub, but better to use your system's package management if possible (see https://docs.bazel.build/versions/master/install.html), or maybe use something like https://github.com/bazelbuild/bazelisk.

**Comment by XqWang3** [comment]
I have installed v 4.0.0 of Bazel, But another question is raised, any advices?  

INFO: Analyzed target //:deepmind_lab.so (1 packages loaded, 110 targets configured).
INFO: Found 1 target...
[9 / 262] 16 actions, 15 running
    Compiling absl/strings/internal/cord_internal.cc; 0s linux-sandbox
    Compiling absl/strings/internal/str_format/float_conversion.cc; 0s linux-sandbox
    Compiling absl/strings/internal/str_format/output.cc; 0s linux-sandbox
    Compiling absl/synchronization/internal/graphcycles.cc; 0s linux-sandbox
    Compiling absl/time/internal/cctz/src/time_zone_fixed.cc; 0s linux-sandbox
[17 / 262] 16 actions, 15 running
    Compiling absl/strings/internal/cord_internal.cc; 0s linux-sandbox
    Compiling absl/strings/internal/str_format/float_conversion.cc; 0s linux-sandbox
    Compiling absl/synchronization/internal/graphcycles.cc; 0s linux-sandbox
    Executing genrule //:assets_pk3; 0s linux-sandbox
    Compiling absl/synchronization/barrier.cc; 0s linux-sandbox
[24 / 262] 16 actions running
    Compiling absl/strings/internal/str_format/float_conversion.cc; 0s linux-sandbox
    Compiling absl/synchronization/internal/graphcycles.cc; 0s linux-sandbox
    Executing genrule //:assets_pk3; 0s linux-sandbox
    Compiling deepmind/lua/table_ref.cc; 0s linux-sandbox
    Executing genrule //:game_script_assets; 0s linux-sandbox
[27 / 262] 16 actions running
    Compiling absl/strings/internal/str_format/float_conversion.cc; 0s linux-sandbox
    Compiling absl/synchronization/internal/graphcycles.cc; 0s linux-sandbox
    Executing genrule //:assets_pk3; 0s linux-sandbox
    Compiling deepmind/lua/table_ref.cc; 0s linux-sandbox
    Executing genrule //:game_script_assets; 0s linux-sandbox
[31 / 262] 16 actions running
    Compiling absl/synchronization/internal/graphcycles.cc; 1s linux-sandbox
    Executing genrule //:assets_pk3; 1s linux-sandbox
    Executing genrule //:game_script_assets; 0s linux-sandbox
    Compiling deepmind/model_generation/transform_lua.cc; 0s linux-sandbox
    Compiling deepmind/model_generation/model_lua.cc; 0s linux-sandbox
INFO: From Compiling deepmind/model_generation/model_getters.cc:
In file included from deepmind/model_generation/model_getters.cc:23:0:
./deepmind/support/logging.h: In instantiation of 'deepmind::internal::CheckOpString deepmind::internal::Check_GTImpl(const T1&, const T2&, const char*) [with T1 = long unsigned int; T2 = int]':
deepmind/model_generation/model_getters.cc:47:3:   required from here
./deepmind/support/logging.h:76:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 DEFINE_CHECK_OP_IMPL(Check_GT, > )
                                ^
./deepmind/support/logging.h:32:48: note: in definition of macro 'PREDICT_TRUE'
 #  define PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                ^
./deepmind/support/logging.h:76:1: note: in expansion of macro 'DEFINE_CHECK_OP_IMPL'
 DEFINE_CHECK_OP_IMPL(Check_GT, > )
 ^~~~~~~~~~~~~~~~~~~~
INFO: From Compiling deepmind/model_generation/geometry_cylinder.cc:
In file included from deepmind/model_generation/geometry_cylinder.cc:21:0:
./deepmind/support/logging.h: In instantiation of 'deepmind::internal::CheckOpString deepmind::internal::Check_GTImpl(const T1&, const T2&, const char*) [with T1 = long unsigned int; T2 = int]':
deepmind/model_generation/geometry_cylinder.cc:36:3:   required from here
./deepmind/support/logging.h:76:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 DEFINE_CHECK_OP_IMPL(Check_GT, > )
                                ^
./deepmind/support/logging.h:32:48: note: in definition of macro 'PREDICT_TRUE'
 #  define PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                ^
./deepmind/support/logging.h:76:1: note: in expansion of macro 'DEFINE_CHECK_OP_IMPL'
 DEFINE_CHECK_OP_IMPL(Check_GT, > )
 ^~~~~~~~~~~~~~~~~~~~
INFO: From Compiling deepmind/model_generation/geometry_cone.cc:
In file included from deepmind/model_generation/geometry_cone.cc:21:0:
./deepmind/support/logging.h: In instantiation of 'deepmind::internal::CheckOpString deepmind::internal::Check_GTImpl(const T1&, const T2&, const char*) [with T1 = long unsigned int; T2 = int]':
deepmind/model_generation/geometry_cone.cc:36:3:   required from here
./deepmind/support/logging.h:76:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 DEFINE_CHECK_OP_IMPL(Check_GT, > )
                                ^
./deepmind/support/logging.h:32:48: note: in definition of macro 'PREDICT_TRUE'
 #  define PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                ^
./deepmind/support/logging.h:76:1: note: in expansion of macro 'DEFINE_CHECK_OP_IMPL'
 DEFINE_CHECK_OP_IMPL(Check_GT, > )
 ^~~~~~~~~~~~~~~~~~~~
INFO: From Compiling deepmind/model_generation/model_lua.cc:
deepmind/model_generation/model_lua.cc: In function 'deepmind::lab::lua::ReadResult deepmind::lab::Read(lua_State*, int, deepmind::lab::Model*)':
deepmind/model_generation/model_lua.cc:131:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (min_idx < 1 || max_idx > model_surface.vertices.size() / 8) {
                        ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO: From Compiling deepmind/engine/lua_text_level_maker.cc:
deepmind/engine/lua_text_level_maker.cc: In member function 'virtual deepmind::lab::Theme::Texture deepmind::lab::{anonymous}::LuaTheme::wall(int, deepmind::lab::Theme::Direction)':
deepmind/engine/lua_text_level_maker.cc:126:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
INFO: From Compiling deepmind/engine/context.cc:
In file included from deepmind/engine/context.cc:32:0:
./deepmind/support/logging.h: In instantiation of 'deepmind::internal::CheckOpString deepmind::internal::Check_LTImpl(const T1&, const T2&, const char*) [with T1 = long unsigned int; T2 = int]':
deepmind/engine/context.cc:993:9:   required from here
./deepmind/support/logging.h:74:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 DEFINE_CHECK_OP_IMPL(Check_LT, < )
                                ^
./deepmind/support/logging.h:32:48: note: in definition of macro 'PREDICT_TRUE'
 #  define PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                ^
./deepmind/support/logging.h:74:1: note: in expansion of macro 'DEFINE_CHECK_OP_IMPL'
 DEFINE_CHECK_OP_IMPL(Check_LT, < )
 ^
./deepmind/support/logging.h: In instantiation of 'deepmind::internal::CheckOpString deepmind::internal::Check_EQImpl(const T1&, const T2&, const char*) [with T1 = int; T2 = long unsigned int]':
deepmind/engine/context.cc:1392:3:   required from here
./deepmind/support/logging.h:71:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 DEFINE_CHECK_OP_IMPL(Check_EQ, ==)
                                ^
./deepmind/support/logging.h:32:48: note: in definition of macro 'PREDICT_TRUE'
 #  define PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                ^
./deepmind/support/logging.h:71:1: note: in expansion of macro 'DEFINE_CHECK_OP_IMPL'
 DEFINE_CHECK_OP_IMPL(Check_EQ, ==)
 ^
INFO: From Compiling deepmind/model_generation/geometry_cube.cc:
In file included from deepmind/model_generation/geometry_cube.cc:21:0:
./deepmind/support/logging.h: In instantiation of 'deepmind::internal::CheckOpString deepmind::internal::Check_GTImpl(const T1&, const T2&, const char*) [with T1 = long unsigned int; T2 = int]':
deepmind/model_generation/geometry_cube.cc:35:3:   required from here
./deepmind/support/logging.h:76:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 DEFINE_CHECK_OP_IMPL(Check_GT, > )
                                ^
./deepmind/support/logging.h:32:48: note: in definition of macro 'PREDICT_TRUE'
 #  define PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                ^
./deepmind/support/logging.h:76:1: note: in expansion of macro 'DEFINE_CHECK_OP_IMPL'
 DEFINE_CHECK_OP_IMPL(Check_GT, > )
 ^~~~~~~~~~~~~~~~~~~~
INFO: From Compiling deepmind/model_generation/geometry_sphere.cc:
In file included from deepmind/model_generation/geometry_sphere.cc:21:0:
./deepmind/support/logging.h: In instantiation of 'deepmind::internal::CheckOpString deepmind::internal::Check_GTImpl(const T1&, const T2&, const char*) [with T1 = long unsigned int; T2 = int]':
deepmind/model_generation/geometry_sphere.cc:36:3:   required from here
./deepmind/support/logging.h:76:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 DEFINE_CHECK_OP_IMPL(Check_GT, > )
                                ^
./deepmind/support/logging.h:32:48: note: in definition of macro 'PREDICT_TRUE'
 #  define PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                ^
./deepmind/support/logging.h:76:1: note: in expansion of macro 'DEFINE_CHECK_OP_IMPL'
 DEFINE_CHECK_OP_IMPL(Check_GT, > )
 ^~~~~~~~~~~~~~~~~~~~
INFO: From Compiling deepmind/engine/context_pickups.cc:
In file included from deepmind/engine/context_pickups.cc:25:0:
deepmind/engine/context_pickups.cc: In member function 'void deepmind::lab::ContextPickups::ReadExtraEntity(int, char*, int*, int (*)[2], int*)':
deepmind/engine/context_pickups.cc:232:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   CHECK(0 <= entity_index && entity_index < extra_entities_.size());
                              ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
./deepmind/support/logging.h:159:15: note: in definition of macro 'CHECK'
              (condition) ? nullptr : new std::string(#condition)))             \
               ^~~~~~~~~
./deepmind/support/logging.h: In instantiation of 'deepmind::internal::CheckOpString deepmind::internal::Check_LEImpl(const T1&, const T2&, const char*) [with T1 = long unsigned int; T2 = int]':
deepmind/engine/context_pickups.cc:220:3:   required from here
./deepmind/support/logging.h:73:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 DEFINE_CHECK_OP_IMPL(Check_LE, <=)
                                ^
./deepmind/support/logging.h:32:48: note: in definition of macro 'PREDICT_TRUE'
 #  define PREDICT_TRUE(x) (__builtin_expect(!!(x), 1))
                                                ^
./deepmind/support/logging.h:73:1: note: in expansion of macro 'DEFINE_CHECK_OP_IMPL'
 DEFINE_CHECK_OP_IMPL(Check_LE, <=)
 ^~~~~~~~~~~~~~~~~~~~
ERROR: /home/ubuntu/wangxq/projects/lab/BUILD:62:8: Executing genrule //:lcc_dagcheck [for host] failed: (Exit 1): bash failed: error executing command /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/lburg engine/code/tools/lcc/src/dagcheck.md > "bazel-out/host/bin/engine/code/tools/lcc/src/dagcheck.c"'

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/lburg engine/code/tools/lcc/src/dagcheck.md > "bazel-out/host/bin/engine/code/tools/lcc/src/dagcheck.c"'

Use --sandbox_debug to see verbose messages from the sandbox
line 1: invalid character `%'
line 1: invalid character `{'
line 1: invalid character `\015'
line 2: invalid character `#'
line 2: syntax error
line 2: invalid character `\015'
line 3: syntax error
line 3: invalid character `;'
line 3: invalid character `\015'
line 4: invalid character `#'
line 4: syntax error
line 4: invalid character `-'
line 4: invalid character `>'
line 4: invalid character `\015'
line 5: invalid character `#'
line 5: syntax error
line 5: invalid character `-'
line 5: invalid character `>'
line 5: invalid character `['
line 5: invalid character `]'
line 5: invalid character `\015'
line 6: invalid character `#'
line 6: syntax error
line 6: invalid character `-'
line 6: invalid character `>'
line 6: invalid character `['
line 6: invalid character `]'
line 6: invalid character `\015'
line 7: invalid character `#'
line 7: syntax error
line 7: invalid character `-'
line 7: invalid character `>'
line 7: invalid character `.'
line 7: invalid character `\015'
line 8: invalid character `#'
line 8: syntax error
line 8: invalid character `\015'
line 9: invalid character `%'
line 9: invalid character `}'
line 9: invalid character `\015'
line 10: invalid character `\015'
line 11: invalid character `\015'
line 12: invalid character `\015'
line 13: invalid character `\015'
line 14: invalid character `\015'
line 15: invalid character `\015'
line 16: invalid character `\015'
line 17: invalid character `\015'
line 18: invalid character `\015'
line 19: invalid character `\015'
line 20: invalid character `\015'
line 21: invalid character `\015'
line 22: invalid character `\015'
line 23: invalid character `\015'
line 24: invalid character `\015'
line 25: invalid character `\015'
line 26: invalid character `\015'
line 27: invalid character `\015'
line 28: invalid character `\015'
line 29: invalid character `\015'
line 30: invalid character `\015'
line 31: invalid character `\015'
line 32: invalid character `\015'
line 33: invalid character `\015'
line 34: invalid character `\015'
line 35: invalid character `\015'
line 36: invalid character `\015'
line 37: invalid character `\015'
line 38: invalid character `\015'
line 39: invalid character `\015'
line 40: invalid character `\015'
line 41: invalid character `\015'
line 42: invalid character `\015'
line 43: invalid character `\015'
line 44: invalid character `\015'
line 45: invalid character `\015'
line 46: invalid character `\015'
line 47: invalid character `\015'
line 48: invalid character `\015'
line 49: invalid character `\015'
line 50: invalid character `\015'
line 51: invalid character `\015'
line 52: invalid character `\015'
line 53: invalid character `\015'
line 54: invalid character `\015'
line 55: invalid character `\015'
line 56: invalid character `\015'
line 57: invalid character `\015'
line 58: invalid character `\015'
line 59: invalid character `\015'
line 60: invalid character `\015'
line 61: invalid character `\015'
line 62: invalid character `\015'
line 63: invalid character `\015'
line 64: invalid character `\015'
line 65: invalid character `\015'
line 66: invalid character `\015'
line 67: invalid character `\015'
line 68: invalid character `\015'
line 69: invalid character `\015'
line 70: invalid character `\015'
line 71: invalid character `\015'
line 72: invalid character `\015'
line 73: invalid character `\015'
line 74: invalid character `\015'
line 75: invalid character `\015'
line 76: invalid character `\015'
line 77: invalid character `\015'
line 78: invalid character `\015'
line 79: invalid character `\015'
line 80: invalid character `\015'
line 81: invalid character `\015'
line 82: invalid character `\015'
line 83: invalid character `\015'
line 84: invalid character `\015'
line 85: invalid character `\015'
line 86: invalid character `\015'
line 87: invalid character `\015'
line 88: invalid character `\015'
line 89: invalid character `\015'
line 90: invalid character `\015'
line 91: invalid character `\015'
line 92: invalid character `\015'
line 93: invalid character `\015'
line 94: invalid character `\015'
line 95: invalid character `\015'
line 96: invalid character `\015'
line 97: invalid character `\015'
line 98: invalid character `\015'
line 99: invalid character `\015'
line 100: invalid character `\015'
line 101: invalid character `\015'
line 102: invalid character `\015'
line 103: invalid character `\015'
line 104: invalid character `\015'
line 105: invalid character `\015'
line 106: invalid character `\015'
line 107: invalid character `\015'
line 108: invalid character `\015'
line 109: invalid character `\015'
line 110: invalid character `\015'
line 111: invalid character `\015'
line 112: invalid character `\015'
line 113: invalid character `\015'
line 114: invalid character `\015'
line 115: invalid character `\015'
line 116: invalid character `\015'
line 117: invalid character `\015'
line 118: invalid character `\015'
line 119: invalid character `\015'
line 120: invalid character `\015'
line 121: invalid character `\015'
line 122: invalid character `\015'
line 123: invalid character `\015'
line 124: invalid character `\015'
line 125: invalid character `\015'
line 126: invalid character `\015'
line 127: invalid character `\015'
line 128: invalid character `\015'
line 129: invalid character `\015'
line 130: invalid character `\015'
line 131: invalid character `\015'
line 132: invalid character `\015'
line 133: invalid character `\015'
line 134: invalid character `\015'
line 135: invalid character `\015'
line 136: invalid character `\015'
line 137: invalid character `\015'
line 138: invalid character `\015'
line 139: invalid character `\015'
line 140: invalid character `\015'
line 141: invalid character `\015'
line 142: invalid character `\015'
line 143: invalid character `\015'
line 144: invalid character `\015'
line 145: invalid character `\015'
line 146: invalid character `\015'
line 147: invalid character `\015'
line 148: invalid character `\015'
line 149: invalid character `\015'
line 150: invalid character `\015'
line 151: invalid character `\015'
line 152: invalid character `\015'
line 153: invalid character `\015'
line 154: invalid character `\015'
line 155: invalid character `\015'
line 156: invalid character `\015'
line 157: invalid character `\015'
line 158: invalid character `\015'
line 159: invalid character `\015'
line 160: invalid character `\015'
line 161: invalid character `\015'
line 162: invalid character `\015'
Target //:deepmind_lab.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/ubuntu/wangxq/projects/lab/BUILD:766:8 Executing genrule //:vm_pk3 failed: (Exit 1): bash failed: error executing command /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/lburg engine/code/tools/lcc/src/dagcheck.md > "bazel-out/host/bin/engine/code/tools/lcc/src/dagcheck.c"'

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/lburg engine/code/tools/lcc/src/dagcheck.md > "bazel-out/host/bin/engine/code/tools/lcc/src/dagcheck.c"'

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 11.440s, Critical Path: 11.31s
INFO: 333 processes: 17 internal, 316 linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by XqWang3** [comment]
I have paste the complete log, and the error info raised is the following:

ERROR: /home/ubuntu/wangxq/projects/lab/BUILD:62:8: Executing genrule //:lcc_dagcheck [for host] failed: (Exit 1): bash failed: error executing command /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/lburg engine/code/tools/lcc/src/dagcheck.md > "bazel-out/host/bin/engine/code/tools/lcc/src/dagcheck.c"'

ERROR: /home/ubuntu/wangxq/projects/lab/BUILD:766:8 Executing genrule //:vm_pk3 failed: (Exit 1): bash failed: error executing command /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/bin/lburg engine/code/tools/lcc/src/dagcheck.md > "bazel-out/host/bin/engine/code/tools/lcc/src/dagcheck.c"'

**Comment by tkoeppe** [comment]
Would you mind formatting your output as code so it isn't used as raw markdown?

**Comment by tkoeppe** [comment]
Is your source tree clean? Can you run `bazel clean --expunge` first?

**Comment by XqWang3** [comment]
I have runned $bazel clean --expunge$ first, then $bazel build -c opt //:deepmind_lab.so$. The following issue is raised.

ERROR: /home/ubuntu/wangxq/projects/lab/deepmind/level_generation/BUILD:6:10: Symlinking //deepmind/level_generation:compile_map_sh failed: failed to create symbolic link 'deepmind/level_generation/compile_map_sh': file 'deepmind/level_generation/compile_map.sh' is not executable

**Comment by tkoeppe** [comment]
Odd, the file is definitely checked in as executable: https://github.com/deepmind/lab/blob/master/deepmind/level_generation/compile_map.sh

I'm not sure what's going on I'm afraid. Maybe try again in a new checkout?

**Comment by XqWang3** [comment]
By the way, I have modified the files:
1. I have replaced the file /lab/bazel/PYTHON.BUILD by the following:
cc_library(
    name = "python",
    hdrs = select(
        {
            "@bazel_tools//tools/python:PY2": glob([
                "include/python2.7/*.h",
                "lib64/python2.7/site-packages/numpy/core/include/**/*.h",
            ]),
            "@bazel_tools//tools/python:PY3": glob([
                "include/python3.6m/*.h",
                "lib64/python3.6/site-packages/numpy/core/include/**/*.h",
            ]),
        },
        no_match_error = "Internal error, Python version should be one of PY2 or PY3",
    ),
    includes = select(
        {
            "@bazel_tools//tools/python:PY2": [
                "include/python2.7",
                "lib64/python2.7/site-packages/numpy/core/include",
            ],
            "@bazel_tools//tools/python:PY3": [
                "include/python3.6m",
                "lib64/python3.6/site-packages/numpy/core/include",
            ],
        },
        no_match_error = "Internal error, Python version should be one of PY2 or PY3",
    ),
    visibility = ["//visibility:public"],
)

2. I have added the following in  /lab/WOERKSPACE
 new_local_repository(
    name = "python_system",
    build_file = "bazel/python.BUILD",
    path = "/home/ubuntu/miniconda3/envs/tf",
)
2. I have added the following in  /lab/BUILD
package(default_visibility = ["//visibility:public"])

**Comment by tkoeppe** [comment]
Please, _please_, format your posts. They're extremely hard and tiring to read.

**Comment by XqWang3** [comment]
By the way, I have modified the files:

1. I have replaced the file /lab/bazel/PYTHON.BUILD by the following:
        cc_library(
        name = "python",
        hdrs = select(
        {
        "@bazel_tools//tools/python:PY2": glob([
        "include/python2.7/.h",
        "lib64/python2.7/site-packages/numpy/core/include/**/.h",
        ]),
        "@bazel_tools//tools/python:PY3": glob([
        "include/python3.6m/.h",
        "lib64/python3.6/site-packages/numpy/core/include/**/.h",
        ]),
        },
        no_match_error = "Internal error, Python version should be one of PY2 or PY3",
        ),
        includes = select(
        {
        "@bazel_tools//tools/python:PY2": [
        "include/python2.7",
        "lib64/python2.7/site-packages/numpy/core/include",
        ],
        "@bazel_tools//tools/python:PY3": [
        "include/python3.6m",
        "lib64/python3.6/site-packages/numpy/core/include",
        ],
        },
        no_match_error = "Internal error, Python version should be one of PY2 or PY3",
        ),
        visibility = ["//visibility:public"],
        )

2. I have added the following in /lab/WOERKSPACE
        new_local_repository(
        name = "python_system",
        build_file = "bazel/python.BUILD",
        path = "/home/ubuntu/miniconda3/envs/tf",
        )

3. I have added the following in /lab/BUILD
        package(default_visibility = ["//visibility:public"])

**Comment by XqWang3** [comment]
Ths. I have successfully complied it  by trying again in a new checkout.
