### ISSUE TITLE
failed to build random agent example

### ISSUE THREAD

**Issue by khy0809** [deepmind/lab#210]
lab$ bazel run :python_random_agent --define graphics=sdl --length=10000 --width=640 --height=480
Starting local Bazel server and connecting to it...
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/master.zip) = 39530432fdce0eda8e78d179330ff454f6cbec8973ab7310aab335460a9f06f6
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "39530432fdce0eda8e78d179330ff454f6cbec8973ab7310aab335460a9f06f6"
DEBUG: Repository rules_cc instantiated at:
  /data/private/research/AgentLearning/lab/WORKSPACE:11:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/0b731ae5b68342aa0fec119b6b2b6299/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://mirror.bazel.build/pypi.python.org/packages/source/s/six/six-1.15.0.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: SHA256 (https://github.com/abseil/abseil-cpp/archive/master.zip) = 3c2bb7907c5c7b02f7f2cb5aa39062c474a0694d8227154c6383f47e99edf9e5
DEBUG: Rule 'com_google_absl' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "3c2bb7907c5c7b02f7f2cb5aa39062c474a0694d8227154c6383f47e99edf9e5"
DEBUG: Repository com_google_absl instantiated at:
  /data/private/research/AgentLearning/lab/WORKSPACE:23:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/0b731ae5b68342aa0fec119b6b2b6299/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://mirror.bazel.build/github.com/glennrp/libpng/archive/v1.6.37.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Analyzed target //:python_random_agent (60 packages loaded, 3715 targets configured).
INFO: Found 1 target...
ERROR: /data/private/research/AgentLearning/lab/BUILD:752:8: Executing genrule //:assets_pk3 failed: (Exit 127): bash failed: error executing command /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; A=$(pwd); (cd assets; zip --quiet -r ${A}/bazel-out/k8-fastbuild/bin/baselab/assets.pk3 -- .)'

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; A=$(pwd); (cd assets; zip --quiet -r ${A}/bazel-out/k8-fastbuild/bin/baselab/assets.pk3 -- .)'

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: zip: command not found
Target //:python_random_agent failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 13.683s, Critical Path: 1.82s
INFO: 85 processes: 82 internal, 3 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by tkoeppe** [comment]
You need to install the `zip` package locally, did you do that? See https://github.com/deepmind/lab/blob/master/docs/users/build.md#step-by-step-instructions-for-building-and-running.

**Comment by tkoeppe** [comment]
Please reopen if there is anything else to discuss.
