### ISSUE TITLE
When I run bazel run :python_random_agent --define graphics=sdl -- \                --length=10000 --width=640 --height=480 in Ubuntu 18.04, I meet the following error.

### ISSUE THREAD

**Issue by VolcanicSnow** [deepmind/lab#213]
ERROR: /home/fei/lab/BUILD:995:10: C++ compilation of rule '//:deepmind_lab.so' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -MD -MF ... (remaining 83 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
python/dmlab_module.c:26:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
Target //:python_random_agent failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 8.709s, Critical Path: 0.39s
INFO: 6 processes: 5 internal, 1 linux-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by tkoeppe** [comment]
Please check out the [build instructions](https://github.com/deepmind/lab/blob/master/docs/users/build.md), and in particular the details of how to adjust your `bazel/python.BUILD` file. You _will_ most likely need to adjust that file to match your system's libraries. (We don't include Python source code in our hermetic build tree here, but instead expect it to come from the local system.)

**Comment by VolcanicSnow** [comment]
> Please check out the [build instructions](https://github.com/deepmind/lab/blob/master/docs/users/build.md), and in particular the details of how to adjust your `bazel/python.BUILD` file. You _will_ most likely need to adjust that file to match your system's libraries. (We don't include Python source code in our hermetic build tree here, but instead expect it to come from the local system.)

Thanks you, it's successful.

**Comment by tkoeppe** [comment]
Great!
