### ISSUE TITLE
Adding "I-maze" map/environment

### ISSUE THREAD

**Issue by dnzrgn** [deepmind/lab#231]
Hello,

I'm currently trying to recreate the "I-maze" from this paper:
http://arxiv.org/abs/1611.05763

I cannot figure out how to add a corresponding level for this. I have already tried creating a map using GtkRadiant and converting it to a .bsp file. I also tried to follow the solution in #186, but without success.
Things that I have tried:

- Adding a lua script to "game_scripts/levels"
- Creating a map file, converting to .bsp and adding to "assets/maps/built"
- Adding a map file to "assets/maps/src"

After each of these approaches, I tried to recompile everything using bazel. I don't know what else I could try. Could you point me in the right direction? Do you happen to have the files that were used for the experiments in the paper? Thanks in advance!

**Comment by tkoeppe** [comment]
@charlesbeattie: could you perhaps have a look?

**Comment by dnzrgn** [comment]
Hello again,

I have now got it to work. Previously, I just attempted to replicate the "nav_maze_random_goal_01" script (https://github.com/deepmind/lab/blob/master/game_scripts/levels/nav_maze_random_goal_01.lua) by copying it and only changing the entity layer definition.
After following the "Building a Minimal Level" guide (https://github.com/deepmind/lab/blob/master/docs/developers/minimal_level_tutorial.md), I can now create levels with my own entity layer.

**Comment by tkoeppe** [comment]
Ah, great! Can we close this issue then?

**Comment by dnzrgn** [comment]
From my side, yes, I don't have anything to add, thanks!

**Comment by tkoeppe** [comment]
Thanks!
