### ISSUE TITLE
Wheel not supported error

### ISSUE THREAD

**Issue by DarthMalloc** [deepmind/lab#238]
I am trying to install the deepmind lab python interface on Linux Mint 19.3, but I am getting the following error:

```
ERROR: deepmind_lab-1.0-py2-none-any.whl is not a supported wheel on this platform.
```

Any help in fixing it would be greatly appreciated.

**Comment by tkoeppe** [comment]
Could you build the Python3 wheel instead?

**Comment by DarthMalloc** [comment]
Thanks for getting back to me so soon.
I ran the bazel build using the command
```
bazel build -c opt --python_version=PY3 //python/pip_package:build_pip_package
```
Is there something else for me to do in addition to that?

**Comment by zhang-yingping** [comment]
you built py3 wheel, but execute pip install using py2 wheel, isn't that strange?

**Comment by tkoeppe** [comment]
Hi, how is it going with this, do you still need help?

**Comment by DarthMalloc** [comment]
It seems to be working now, thanks for your help!

**Comment by tkoeppe** [comment]
Grand, thank you!
