### ISSUE TITLE
Banino et. al. Grid Cells explore_goal_locations and explore_obstructed_goals

### ISSUE THREAD

**Issue by jjwang01** [deepmind/lab#243]
Hi there, I'm trying to reproduce some experiments from the "Vector-based navigation using grid-like
representations in artificial agents" paper by Banino et. al. In the appendix, they claim that two tasks they used to train their agent, explore_goal_locations and explore_obstructed_goals, were included as part of a release in DeepMind Lab. I'm having trouble finding these tasks, would you be able to point me to where they are located? Thanks!

**Comment by charlesbeattie** [comment]
See the code and documentation here:
https://github.com/deepmind/lab/tree/master/game_scripts/levels/contributed/dmlab30
Where you will find small and large versions oth those levels.
i.e.
```
levelName="contributed/dmlab30/explore_goal_locations_small"
levelName="contributed/dmlab30/explore_goal_locations_large"
levelName="contributed/dmlab30/explore_obstructed_goals_small"
levelName="contributed/dmlab30/explore_obstructed_goals_large"
```
