### ISSUE TITLE
When I run bazel run :python_random_agent --define graphics=sdl -- \ --length=10000 --width=640 --height=480 in Ubuntu 20.04, I meet the following error.

### ISSUE THREAD

**Issue by aalvan** [deepmind/lab#247]
ERROR: /home/camada/lab/BUILD:693:8: declared output 'baselab/default.cfg' is a dangling symbolic link
ERROR: /home/camada/lab/BUILD:693:8: declared output 'baselab/q3config.cfg' is a dangling symbolic link
ERROR: /home/camada/lab/BUILD:693:8: Executing genrule //:non_pk3_assets failed: not all outputs were created or valid
Target //:python_random_agent failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/camada/lab/BUILD:1047:10 Middleman _middlemen/python_Urandom_Uagent-runfiles failed: not all outputs were created or valid
INFO: Elapsed time: 8.866s, Critical Path: 0.61s
INFO: 98 processes: 41 internal, 57 linux-sandbox.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target

**Comment by stefanwm13** [comment]
Had the same error. I fixed it by installing an older bazel version (6.4.0) and then setting `echo 'build --cxxopt=-std=c++14' > .bazelrc` before building again.

**Comment by aalvan** [comment]
It worked, thank you very much for your help.
