### ISSUE TITLE
A visualization tool

### ISSUE THREAD

**Issue by henrykmichalewski** [deepmind/lab#26]
[The blog post](https://deepmind.com/blog/reinforcement-learning-unsupervised-auxiliary-tasks/) shows an interesting visualization tool with two columns "Live play" and "Auxiliary Tasks". Are you planning to release a tool like this for the live play?

**Comment by tkoeppe** [comment]
That "tool" seems to be a specific *agent*, rather than something that's part of the environment. We don't plan to ship it as part of Lab.
