### ISSUE TITLE
Error occurs when compiling on Ubuntu 14.04

### ISSUE THREAD

**Issue by everdom** [deepmind/lab#28]
I just compiled deepmind lab according to official guidance, but error occured after I ran `bazel build :deepmind_lab.so --define headless=glx --verbose_failures`, at first I thought it could be a problem about privilege, but it didn't work even if I switched to root account. I used ubuntu 14.04，can anyone help? log below:

INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/849b6bbeac370239e55f7f9aec9e5d3e/external/libxml_archive/BUILD:1:1: Executing genrule @libxml_archive//:gen_configure failed: linux-sandbox failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/849b6bbeac370239e55f7f9aec9e5d3e/bazel-sandbox/a84ae3c0-6bfc-42b5-998b-9e7970b5530f-1/execroot/lab && \
  exec env - \
    PATH=/home/everdom/.nvm/versions/node/v6.4.0/bin:/home/everdom/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
    TMPDIR=/tmp/user/0 \
  /root/.cache/bazel/_bazel_root/849b6bbeac370239e55f7f9aec9e5d3e/execroot/lab/_bin/linux-sandbox @/root/.cache/bazel/_bazel_root/849b6bbeac370239e55f7f9aec9e5d3e/bazel-sandbox/a84ae3c0-6bfc-42b5-998b-9e7970b5530f-1/linux-sandbox.params -- /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; ./external/libxml_archive/configure --without-lzma && cp --verbose -- config.h bazel-out/host/genfiles/external/libxml_archive/config.h && cp --verbose -- include/libxml/xmlversion.h bazel-out/host/genfiles/external/libxml_archive/include/libxml/xmlversion.h').
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... mkdir: cannot create directory '/tmp/user/0/cg144-10876': No such file or directory
mkdir: cannot create directory '/tmp/user/0/cg-144': No such file or directory
config.guess: cannot create a temporary directory in /tmp/user/0
configure: error: cannot guess build type; you must specify one
WARNING: Cannot delete sandbox directory after action execution: /root/.cache/bazel/_bazel_root/849b6bbeac370239e55f7f9aec9e5d3e/bazel-sandbox/a84ae3c0-6bfc-42b5-998b-9e7970b5530f-3 (java.io.IOException: /root/.cache/bazel/_bazel_root/849b6bbeac370239e55f7f9aec9e5d3e/bazel-sandbox/a84ae3c0-6bfc-42b5-998b-9e7970b5530f-3/execroot/lab (Device or resource busy)).
Target //:deepmind_lab.so failed to build
INFO: Elapsed time: 0.734s, Critical Path: 0.42s

**Comment by tkoeppe** [comment]
I'm afraid there's not enough context here for an analysis.

**Comment by samuelzhouhe** [comment]
I have almost the same problem. Still couldn't even figure out a way to build deepmind lab
