### ISSUE TITLE
Build DeepMind Lab Failed?

### ISSUE THREAD

**Issue by xjwxjw** [deepmind/lab#3]
Hi,
I run the command:"bazel build : deepmind_lab.so --define headless=glx", and then get the following output:

xu-jinwgei@xujinwgei-Precision-Tower-7910:~/lab-master$ bazel build :deepmind_lab.so --define headless=glx
INFO: Found 1 target...
ERROR: /home/xu-jinwgei/lab-master/BUILD:838:1: Executing genrule //:non_pk3_assets failed: linux-sandbox failed: error executing command /home/xu-jinwgei/.cache/bazel/_bazel_xu-jinwgei/7f9c394f362e8089472ee6d14cb49bf2/execroot/lab-master/_bin/linux-sandbox ... (remaining 5 argument(s) skipped).
/bin/bash: realpath: command not found
ln: missing file operand
Try 'ln --help' for more information.
Target //:deepmind_lab.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.571s, Critical Path: 0.27s

What should I deal with the message?Thanks!

**Comment by jithinoc** [comment]
@xjwxjw sudo apt-get insall realpath

**Comment by xjwxjw** [comment]
yeah, thanks.It works.
But then I try to build it like this:"bazel run :random_agent --define headless=false". It fails, and get the following output:

INFO: Running command line: bazel-bin/random_agent '--length=10000' '--width=640' '--height=480'
Failed to open library! - ./libdmlab.so
./libdmlab.so: undefined symbol: crc32
Traceback (most recent call last):
  File "/home/xu-jinwgei/.cache/bazel/_bazel_xu-jinwgei/7f9c394f362e8089472ee6d14cb49bf2/execroot/lab-master/bazel-out/local-fastbuild/bin/random_agent.runfiles/org_deepmind_lab/python/random_agent.py", line 188, in <module>
    run(args.length, args.width, args.height, args.fps, args.level_script)
  File "/home/xu-jinwgei/.cache/bazel/_bazel_xu-jinwgei/7f9c394f362e8089472ee6d14cb49bf2/execroot/lab-master/bazel-out/local-fastbuild/bin/random_agent.runfiles/org_deepmind_lab/python/random_agent.py", line 146, in run
    'height': str(height)
RuntimeError: Failed to connect RL API
ERROR: Non-zero return code '1' from command: Process exited with status 1.

Do you have any idea with it?Much Thanks!

**Comment by xjwxjw** [comment]
I try the command :"bazel run :random_agent --define headless=false --   --length=10000 --width=640 --height=480". It is the same output as "bazel run :random_agent --define headless=false".

**Comment by xjwxjw** [comment]
Adding the "export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libz.so" to ./bashrc file.It finally works.

**Comment by tkoeppe** [comment]
@xjwxjw: Thanks for investigating, and for the pull request. You shouldn't have to preload libz, since we compile it from source and link it statically. If there is a loading error, could you try adding the "undefined symbols" to `dmlab.so` first? (For an easy hack, just replace the "visible" section in `dmlab.so` by `*'` and see if that resolves it, and then narrow it down to the symbols that are actually used.)
