### ISSUE TITLE
Unable to build: Python include path missing

### ISSUE THREAD

**Issue by hercky** [deepmind/lab#32]
Hi 

I'm on Ubuntu 16.04 and following the guidelines from https://github.com/deepmind/lab/blob/master/docs/build.md . I'm unable to run any of the examples

Here are the major library versions:
* Bazel version: 0.4.3
* Lua: 5.1.5
* Python: 2.7
* OpenGL version: 4.5.0
* GCC:  5.4.0

Error while trying to run a random agent

```
lab$ bazel run :game -- --level_script tests/demo_map --verbose_failures
WARNING: Output base '/home/ml/hsatij/.cache/bazel/_bazel_hsatij/2a466b12af1ad7b6dcfd974c8d06585b' is on NFS. This may lead to surprising failures and undetermined behavior.
INFO: Found 1 target...
ERROR: /home/ml/hsatij/.cache/bazel/_bazel_hsatij/2a466b12af1ad7b6dcfd974c8d06585b/external/jpeg_archive/BUILD:74:1: Executing genrule @jpeg_archive//:configure failed: linux-sandbox failed: error executing command /home/ml/hsatij/.cache/bazel/_bazel_hsatij/2a466b12af1ad7b6dcfd974c8d06585b/execroot/lab/_bin/linux-sandbox ... (remaining 5 argument(s) skipped).
src/main/tools/linux-sandbox-pid1.cc:398: "remount(NULL, /home/ml/hsatij/.cache/bazel/_bazel_hsatij/2a466b12af1ad7b6dcfd974c8d06585b/bazel-sandbox/905e0eef-0788-42e6-8852-7b444149d38c-13/tmp/home/ndg/projects, NULL, 2101281, NULL)": No such file or directory
Target //:game failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.569s, Critical Path: 1.20s
ERROR: Build failed. Not running target.
```

On trying to build the Python interface to DeepMind Lab with OpenGL

```
lab$ bazel build :deepmind_lab.so --define headless=glx --verbose_failures
WARNING: Output base '/home/ml/hsatij/.cache/bazel/_bazel_hsatij/2a466b12af1ad7b6dcfd974c8d06585b' is on NFS. This may lead to surprising failures and undetermined behavior.
INFO: Found 1 target...
ERROR: /home/ml/hsatij/code/libs/lab/BUILD:972:1: C++ compilation of rule '//:dmlablib' failed: linux-sandbox failed: error executing command 
  (cd /home/ml/hsatij/.cache/bazel/_bazel_hsatij/2a466b12af1ad7b6dcfd974c8d06585b/bazel-sandbox/ff30fcd2-9759-4ca4-8fa3-b82956431988-1/execroot/lab && \
  exec env - \
  /home/ml/hsatij/.cache/bazel/_bazel_hsatij/2a466b12af1ad7b6dcfd974c8d06585b/execroot/lab/_bin/linux-sandbox @/home/ml/hsatij/.cache/bazel/_bazel_hsatij/2a466b12af1ad7b6dcfd974c8d06585b/bazel-sandbox/ff30fcd2-9759-4ca4-8fa3-b82956431988-1/linux-sandbox.params -- /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-canonical-system-headers -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/local-fastbuild/bin/_objs/dmlablib/public/dmlab_so_loader.pic.d '-frandom-seed=bazel-out/local-fastbuild/bin/_objs/dmlablib/public/dmlab_so_loader.pic.o' -fPIC -iquote . -iquote bazel-out/local-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 '-DDMLAB_SO_LOCATION="libdmlab.so"' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c public/dmlab_so_loader.cc -o bazel-out/local-fastbuild/bin/_objs/dmlablib/public/dmlab_so_loader.pic.o).
src/main/tools/linux-sandbox-pid1.cc:398: "remount(NULL, /home/ml/hsatij/.cache/bazel/_bazel_hsatij/2a466b12af1ad7b6dcfd974c8d06585b/bazel-sandbox/ff30fcd2-9759-4ca4-8fa3-b82956431988-1/tmp/home/ndg/projects, NULL, 2101281, NULL)": No such file or directory
Target //:deepmind_lab.so failed to build
INFO: Elapsed time: 2.294s, Critical Path: 1.11s
```

I'm new to bazel and unfortunately the error logs are too cryptic for me. Any help to resolve this will be appreciated !

**Comment by jingweiz** [comment]
Hey, did you figure out how to solve it? I'm having this error when I tried to build it:
```
python/dmlab_module.c:29:31: fatal error: numpy/arrayobject.h: No such file or directory
```
Did you come across error message?

**Comment by tkoeppe** [comment]
Did you install the Numpy development package? See https://github.com/deepmind/lab/blob/master/docs/build.md for details.

**Comment by hercky** [comment]
Yeah, I've the numpy-development package ( and the updated versions of other packages specified on the link too )

**Comment by tkoeppe** [comment]
Sorry, the reference was unclear. My question about `numpy-dev` was for @jingweiz; @hercky, I don't know what's going on with you, it looks like some environmental problem. Is that a normal, local desktop machine, not some kind of virtual or remote one?

**Comment by hercky** [comment]
Yeah, a normal local desktop machine .

**Comment by tkoeppe** [comment]
@hercky: Can you try `bazel --expunge` and then try again?

**Comment by tkoeppe** [comment]
@hercky: Any updates on this?

**Comment by hercky** [comment]
Hi @tkoeppe 

I guess you meant the command ``` bazel clean --expunge```. I tried running that but it too fails with the error:
```
WARNING: Output base '/home/ml/hsatij/.cache/bazel/_bazel_hsatij/2a466b12af1ad7b6dcfd974c8d06585b' is on NFS. This may lead to surprising failures and undetermined behavior.
.
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
ERROR: /home/ml/hsatij/.cache/bazel/_bazel_hsatij/2a466b12af1ad7b6dcfd974c8d06585b/server/.nfs0000000001ea365500000a0e (Device or resource busy).
```

**Comment by hercky** [comment]
I found a similar issue at https://github.com/tensorflow/tensorflow/issues/3652 and https://github.com/bazelbuild/bazel/issues/2033 . Using the hints from them, I was able to run the clean 
```
bazel --output_base=/tmp/bazel/lab clean --expunge
```
successfully. But the error on running ``` bazel --output_base=/tmp/bazel/lab run :game -- --level_script tests/demo_map --verbose_failures ``` is still present (although this time it doesn't fails immediately and downloads some resources first). The error message now is:

```
........
INFO: Found 1 target...
ERROR: /home/ml/hsatij/code/libs/lab/deepmind/support/BUILD:37:1: C++ compilation of rule '//deepmind/support:stringprintf' failed: linux-sandbox failed: error executing command /tmp/bazel/lab/execroot/lab/_bin/linux-sandbox @/tmp/bazel/lab/bazel-sandbox/f0413033-1321-4272-8da6-d30340a1617e-0/linux-sandbox.params -- /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' ... (remaining 34 argument(s) skipped).
src/main/tools/linux-sandbox-pid1.cc:398: "remount(NULL, /tmp/bazel/lab/bazel-sandbox/f0413033-1321-4272-8da6-d30340a1617e-0/tmp/home/ndg/projects, NULL, 2101281, NULL)": No such file or directory
Target //:game failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 33.670s, Critical Path: 6.86s
ERROR: Build failed. Not running target.

```

**Comment by samuelzhouhe** [comment]
I am having a similar problem with you. The error message I get after executing ```bazel --output_base=/tmp/bazel/lab run :game -- --level_script tests/demo_map --verbose_failures``` was:
```
........
INFO: Found 1 target...
ERROR: /home/ck1/fyp/lab/deepmind/support/BUILD:37:1: C++ compilation of rule '//deepmind/support:stringprintf' failed: Process exited with status 1 [sandboxed].
src/main/tools/linux-sandbox-pid1.cc:193: "mount(/tmp, /tmp, NULL, MS_BIND, NULL)": Invalid argument
Use --strategy=CppCompile=standalone to disable sandboxing for the failing actions.
Target //:game failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 124.174s, Critical Path: 0.13s
ERROR: Build failed. Not running target.
```
Which is way too esoteric for me as a rookie to bazel.

Any help would be appreciated.

**Comment by bodgergely** [comment]
What do you have at line 74 in the file below?
ERROR: /home/ml/hsatij/.cache/bazel/_bazel_hsatij/2a466b12af1ad7b6dcfd974c8d06585b/external/jpeg_archive/BUILD:74:1

**Comment by dhfromkorea** [comment]
For the record, I had a similar issue and running `bazel clean --expunge` and `bazel --output_base=/tmp/bazel/lab clean --expunge` resolved it.

The issue:

bazel build :deepmind_lab.so --define headless=glx --verbose_failures
INFO: Found 1 target...
ERROR: /home/dhfromkorea/.cache/bazel/_bazel_dhfromkorea/e3cee545b23a7b65a3985039622e146c/external/jpeg_archive/BUILD.bazel:74:1: Executing genrule @jpeg_archive//:configure failed: bash failed: error executing command 
  (exec env - \
    LD_LIBRARY_PATH=/usr/lib/nvidia-375 \
    PATH=/home/dhfromkorea/bin/miniconda3/envs/deepmind-lab/bin:/usr/local/cuda-8.0/bin:/home/dhfromkorea/bin/miniconda3/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; cat <<EOF >bazel-out/local-fastbuild/genfiles/external/jpeg_archive/jconfig.h
#define HAVE_PROTOTYPES 1
#define HAVE_UNSIGNED_CHAR 1
#define HAVE_UNSIGNED_SHORT 1
#define HAVE_STDDEF_H 1
#define HAVE_STDLIB_H 1
#ifdef WIN32
#define INLINE __inline
#else
#define INLINE __inline__
#endif
EOF
')

Use --sandbox_debug to see verbose messages from the sandbox.
src/main/tools/linux-sandbox-pid1.cc:193: "mount(/tmp, /tmp, NULL, MS_BIND, NULL)": Invalid argument
Use --strategy=Genrule=standalone to disable sandboxing for the failing actions.
Target //:deepmind_lab.so failed to build
INFO: Elapsed time: 0.242s, Critical Path: 0.06s

**Comment by 3208173239** [comment]
I meet a error like this.Do you know how to solve it.
 bazel-out/local-fastbuild/bin/deepmind/lua/_objs/table_ref/deepmind/lua/table_ref.pic.o:table_ref.cc:function deepmind::lab::lua::TableRef::TableRef(deepmind::lab::lua::TableRef const&): error: undefined reference to 'luaL_ref'
bazel-out/local-fastbuild/bin/deepmind/lua/_objs/table_ref/deepmind/lua/table_ref.pic.o:table_ref.cc:function deepmind::lab::lua::TableRef::KeyCount() const: error: undefined reference to 'lua_pushnil'
bazel-out/local-fastbuild/bin/deepmind/lua/_objs/table_ref/deepmind/lua/table_ref.pic.o:table_ref.cc:function deepmind::lab::lua::TableRef::KeyCount() const: error: undefined reference to 'lua_next'
bazel-out/local-fastbuild/bin/deepmind/lua/_objs/table_ref/deepmind/lua/table_ref.pic.o:table_ref.cc:function deepmind::lab::lua::TableRef::Create(lua_State*): error: undefined reference to 'luaL_ref'
bazel-out/local-fastbuild/bin/deepmind/lua/_objs/table_ref/deepmind/lua/table_ref.pic.o:table_ref.cc:function deepmind::lab::lua::Read(lua_State*, int, deepmind::lab::lua::TableRef*): error: undefined reference to 'luaL_ref'
collect2: error: ld returned 1 exit status
Use --strategy=CppLink=standalone to disable sandboxing for the failing actions.
Target //:game failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by tkoeppe** [comment]
Is this still a problem?

**Comment by rockkingjy** [comment]
I still have the problem of:
```
python/dmlab_module.c:29:31: fatal error: numpy/arrayobject.h: No such file or directory
```
how did you solve them finally?

**Comment by tkoeppe** [comment]
@rockkingjy: Did you install the necessary numpy development package?

**Comment by rockkingjy** [comment]
Yes, I run
```
sudo pip install numpy
```
I got:
```
Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages
```

**Comment by tkoeppe** [comment]
No, I mean the system development package. E.g. `apt-get install numpy` on Debianesque systems.

**Comment by rockkingjy** [comment]
Hi~ Thanks for you answer, but I think yes:
```
sudo apt-get install python-numpy
```
and have:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-numpy is already the newest version (1:1.11.0-1ubuntu1).
```
And other informations:
```
$ python --version
Python 2.7.12
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
```

**Comment by tkoeppe** [comment]
Ah, OK, I think I had this problem too on some distributions. Try amending your `python.BUILD` to include the Python paths, like so:

```
# Description:
#   Build rule for Python and Numpy.
#   This rule works for Debian and Ubuntu. Other platforms might keep the
#   headers in different places, cf. 'How to build DeepMind Lab' in build.md.

cc_library(
    name = "python",
    hdrs = glob([
        "include/python2.7/*.h",
         "lib64/python2.7/site-packages/numpy/core/include/**/*.h",
    ]),
    includes = [
        "include/python2.7",
        "lib64/python2.7/site-packages/numpy/core/include",
    ],
    visibility = ["//visibility:public"],
)
```

**Comment by rockkingjy** [comment]
Thanks, yes, I've done:
```
locate /arrayobject.h
```
that gave:
```
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h
```
And I've changed the python.BUILD to:
```
cc_library(
    name = "python",
    hdrs = glob([
        "include/python2.7/*.h",
        "lib/python2.7/dist-packages/numpy/core/include/**/*.h",
    ]),
    includes = [
        "include/python2.7",
        "lib/python2.7/dist-packages/numpy/core/include",
    ],
    visibility = ["//visibility:public"],
)
```
But still the same problem:
```
$ sudo bazel build :deepmind_lab.so --define headless=glx
INFO: Analysed target //:deepmind_lab.so (1 packages loaded).
INFO: Found 1 target...
ERROR: /home/enroutelab/Amy/lab/BUILD:988:1: C++ compilation of rule '//:deepmind_lab.so' failed (Exit 1)
python/dmlab_module.c:29:31: fatal error: numpy/arrayobject.h: No such file or directory
compilation terminated.
```

**Comment by tkoeppe** [comment]
The `includes` path is relative to `/usr` (given by the `path` value in `WORKSPACE`), so it should start with `local/lib/...` in your case.

**Comment by rockkingjy** [comment]
Aha, it seems that it works, great~ thanks so much!

**Comment by tkoeppe** [comment]
No problem :-) Perhaps we should add a note to the documentation that this may be required.

**Comment by tkoeppe** [comment]
Oh, we already have that note in https://github.com/deepmind/lab/blob/master/docs/build.md :-S

**Comment by rockkingjy** [comment]
Oh, yes, but for my case of ubuntu, I haven't notice this... because it's in "Build on SUSE Linux subtitle"...

**Comment by tkoeppe** [comment]
(Perhaps a documentation update would be in order.)

**Comment by MrDadaGuy** [comment]
I had this problem as well on Ubuntu 16.04 and @tkoeppe comment above provided me enough info to edit my Python.BUILD accordingly and now I am past this problem.  Thanks!

**Comment by tkoeppe** [comment]
@MrDadaGuy: Ubuntu 16 is what's running the Travis CI test, I believe, so you can always look at that one to see a worked example. I would hope that Ubunutu 16 doesn't require any of the editing that we need on Suse, though.

**Comment by tkoeppe** [comment]
Note also that you need to make sure that the Python and Numpy devel libraries you've compiled against match the Python binary that is found when you just say `python`. This seems straight-forward if you are sudoing and can install libraries system-wide, but it has bitten me when I tried homebrew on macOS and there were different Python versions around.

**Comment by tkoeppe** [comment]
I think we can close this issue. Feel free to reopen if there is new information.
