### ISSUE TITLE
Python3 Compatibility

### ISSUE THREAD

**Issue by djl11** [deepmind/lab#33]
With reference to this issue: https://github.com/deepmind/lab/issues/13
I was wondering if/when Python3 compatibility might be likely?
Having the same issue when trying to import deepmind_lab module in python3 script.

**Comment by tkoeppe** [comment]
At the moment, we're not putting active effort into making the Python bindings compatible with Python 3. For now, think of the Python bindings as an "example" for using the Lab API. The example may not be perfectly suitable to your needs, and you are most welcome to modify or replace it as you see fit.

If you have any good ideas for changing the existing code so it works as both Python 2.7 and 3, it would be interesting to see.

**Comment by tkoeppe** [comment]
There is some experimental support for Python 3 now. Check out the Bazel docs on how to switch versions, too: https://docs.bazel.build/versions/master/be/python.html#py_binary_args
