### ISSUE TITLE
Add supported OS list to README.md?

### ISSUE THREAD

**Issue by liuslevis** [deepmind/lab#39]
Failed to build on OSX. And I found the answer in a closed issue: macOS is not supported.

Can anyone add supported OS list to README.md?

**Comment by tkoeppe** [comment]
Sure, we can make that more explicit. I'll earmark it for the next update.

**Comment by tkoeppe** [comment]
I created a general list of requirements and FAQs in #41. We'll eventually update the documentation proper, but I think keeping a visible list directly in the issues section may be a good idea regardless.
