### ISSUE TITLE
Remove Scores and Texts Display

### ISSUE THREAD

**Issue by jingweiz** [deepmind/lab#43]
Hi,
I get the attached RGB and depth image from the ```"RGBD_INTERLACED"``` observation, but haven't figured out how to remove the scores, texts and boxes in the bottom part of the images, can you give me some instructions? I haven't had any luck from the docs... Thanks in advance!
![rgb](https://cloud.githubusercontent.com/assets/9096283/22698651/6b31655a-ed55-11e6-83a7-33de0615cf18.png) ![depth](https://cloud.githubusercontent.com/assets/9096283/22698652/6b317568-ed55-11e6-9f13-4d997f097a75.png)

**Comment by tkoeppe** [comment]
Is this not covered by #18?

**Comment by jingweiz** [comment]
Ah yes exactly, sorry wasn't searching carefully enough :)
