### ISSUE TITLE
Mouse sensitivity is too high when in game mode

### ISSUE THREAD

**Issue by frankcarey** [deepmind/lab#44]
When running this within VNC in #24  with:

`bazel run :random_agent --define headless=false -- \
               --length=10000 --width=640 --height=480`

Things work fine, but when I use game mode the mouse seems to be much too sensitive and ends up flipping back and forth between gimbal lock, looking straight up or down. Is anyone else experiencing that when using the following?

`bazel run :game -- --level_script tests/demo_map`

Normal:
<img width="709" alt="screen shot 2017-02-09 at 4 59 25 am" src="https://cloud.githubusercontent.com/assets/377330/22778512/3e9b0b50-ee85-11e6-8e94-778168b90bb3.png">

When using mouse, it's either this or looking straight up:
<img width="682" alt="screen shot 2017-02-09 at 5 00 10 am" src="https://cloud.githubusercontent.com/assets/377330/22778544/56d47972-ee85-11e6-80ac-d3ee10e38f49.png">

**Comment by anshulkatta** [comment]
@frankcarey  did you fix this , looks like we need to check in the code and lower the sensitivity

**Comment by PetterBomban** [comment]
I am having the same problem running on a VM.

OS: Ubuntu Desktop 16.04.2 LTS

Hypervisor: VMware ESXi 6.0 Update 3

```shell
bazel run :random_agent --define headless=false -- --width=640 --height=480 --level_script=lt_space_bounce_hard --length 10000
```

**Comment by Science21330** [comment]
I'm experiencing the same issue, any input by mouse and its looking straight down or up, but also, the mouse is caught but not displayed in the window:

https://youtu.be/5LRRjQNbwGw

Like PetterBomban i'm using a UbuntuVM, too (don't mind the gtk-theme, its Ubuntu).

Any ideas?

**Comment by xueeinstein** [comment]
This issue still exists now, especially in Psychlab which requires extensive mouse interaction. @tkoeppe @charlesbeattie Any plan to fix this? Thanks.

**Comment by charlesbeattie** [comment]
We are not planning on addressing this issue directly.
Results may be improved by modifying the frame rate by passing command-line arg --fps 60

One can also use the key bindings for looking around:
(Edit assets/q3config.cfg to choose different key bindings.)

```
bind DEL "+lookdown"
bind PGDN "+lookup"
bind LEFTARROW "+left"
bind RIGHTARROW "+right"
```

**Comment by tkoeppe** [comment]
Please reopen if there are further issues here.
