### ISSUE TITLE
Receiving depth image from the simulator, Changing the environment

### ISSUE THREAD

**Issue by AmirCognitive** [deepmind/lab#46]
Hi,

Thanks for your package.

As I noticed, it is possible to create an agent with your package, move the agent and receive the agent's view (RGB image) in every 4 steps or so.

My question is: can I receive a depth image instead of RGB image? and can I change the environment?

Regards,

**Comment by tkoeppe** [comment]
Yes, one of the observations that you get out of the API is RBGD (have a look which one, I forget).

What do you mean by "change the environment"? Your level script can load different maps dynamically (I think some of the examples demonstrate that).

**Comment by AmirCognitive** [comment]
Thanks, it was RGBD_INTERLACED.

I meant to open a map and edit the walls and other features.

**Comment by tkoeppe** [comment]
There are examples for using the "text level" map generation system to make simple grid maps, which can happen dynamically. You cannot dynamically modify the ready-made .bsp maps (though you could conceivably write code to implement such a feature).

**Comment by AmirCognitive** [comment]
I noticed there is a 'make_map' function in some Lua scripts for making a map from text file. and as I noticed for example I need to have a saved file containing the map information and give it as the input to the Lua function such as:
********
*a * x *****
**     *   *
 ****  I   *
    *  *   *
    *  *****
    *   *
******H*******
*        I P *
**************
as explained in https://github.com/deepmind/lab/blob/master/docs/text_level.md
What I cannot find is that how to call that function in my python code, or how exactly generate the map using that lua function (I didn't work with Lua before).

Beside that, for actions, LOOK_LEFT_RIGHT_PIXELS_PER_FRAME is for turn or rotate to left and right, correct me if I am wrong.

Finally, Is it possible to get a top view of the agent in the environment? (a 2D image that shows the agent as it is a camera looking at the agent from top). And also is it possible to get the position of the agent and/or its distance with the walls? 

Thanks,

**Comment by charlesbeattie** [comment]
You can pass settings via

```
function api:init(params)
  local map = params.textMap
end
```

Then construct the environment with 'textMap'  : <text of map> in the settings dictionary.

**Comment by tkoeppe** [comment]
Closing; please reopen if there are any further problems.
