### ISSUE TITLE
Failed with running "bazel build :deepmind_lab.so --define headless=glx"

### ISSUE THREAD

**Issue by wteo** [deepmind/lab#49]
model name	: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
ubuntu 14.04
gcc 4.8.4

========================================================================
ERROR: /home/cat/lab/BUILD:730:1: C++ compilation of rule '//:game_lib_headless_glx' failed: Process exited with status 1 [sandboxed].
engine/code/qcommon/vm_x86.c: In function 'VM_CallCompiled':
engine/code/qcommon/vm_x86.c:1803:2: error: inconsistent operand constraints in an 'asm'
  __asm__ volatile(
  ^
Use --strategy=CppCompile=standalone to disable sandboxing for the failing actions.
Target //:deepmind_lab.so failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by anshulkatta** [comment]
you need to update your gcc to 5 , 4.8 have some issues..


```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test sudo apt-get update sudo apt-get install gcc-5 g++-5

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
```

**Comment by tkoeppe** [comment]
Yes, please try again with a slightly more modern compiler. We aren't testing this for arbitrarily old platforms. (I think GCC 4.9 should be OK.)
