### ISSUE TITLE
get extra information

### ISSUE THREAD

**Issue by arpit15** [deepmind/lab#50]
What is the way to get extra information from the game like the players position for loop closure prediction as done in the [paper](https://arxiv.org/abs/1611.05397) ?

**Comment by tkoeppe** [comment]
An upcoming update will contain additional APIs to expose this information.

**Comment by arpit15** [comment]
That will be great. Thanks

**Comment by charlesbeattie** [comment]
There are now custom observations that expose lots of internal data including player position.
"DEBUG.POS.TRANS".
