### ISSUE TITLE
Imitation learning recording using python

### ISSUE THREAD

**Issue by JunhongXu** [deepmind/lab#51]
Hi

Thanks for this great environment. I would like to ask how I can play as a human like the example provided:`lab$ bazel run :game -- --level_script tests/demo_map` and record the frames as well as the actions in python script? I did not find any `human mode` api in python.

Thanks!

**Comment by tkoeppe** [comment]
See also #47: generally, you'll need to write your own human interface to the DMLab API (e.g. using SDL), and then you can save any kind of trace information you like.
