### ISSUE TITLE
Disable map creation log printing

### ISSUE THREAD

**Issue by edran** [deepmind/lab#54]
Is there any way to disable all the printing that occurs when creating a map? I can see that the logs are being saved (to e.g. `bspc.log` - any way to parametrise this too by any chance?), so there is no need to show the output from `bsp2aas` and similar tools.

Plus this gets quite troublesome when running multiple environments in the same binary. :smiley:

**Comment by tkoeppe** [comment]
You can try adding `> /dev/null` in places to `compile_map.sh`, that should get rid of most of the output. (We didn't make this parametrizable because worst case it would make it hard to see errors, and we weren't too bothered by the output.)

**Comment by edran** [comment]
Cool, thanks.

I think it'd be great to have a flag at build time to do this, so I may send a patch if I end up doing this automatically (as opposed to manually patching the result of bazel build directly).

**Comment by tkoeppe** [comment]
Hm, I don't think this behaviour can be changed at build time, since the shell script doesn't get "built". It's just run as-is.

In the upcoming update, we've replaced `std::system` with `popen` and we only print the output if there was an error, so that should help matters.

**Comment by tkoeppe** [comment]
Fixed by 91d29b87dde270cc073cbe696e7bbe7cfee2bff9.
