### ISSUE TITLE
Text Map keeps getting re-compiled

### ISSUE THREAD

**Issue by shurjobanerjee** [deepmind/lab#56]
Is there a way to avoid the maps getting constantly recompiled? I'd like to run some experiments on a simple, static custom environment but "compile_maps.sh" seems to run every time an episode ends? 
Thanks!

**Comment by tkoeppe** [comment]
If the map is always the same, can you not generate it just once before any of the episodes start and then reuse it?

**Comment by tkoeppe** [comment]
We changed the build dependencies in a very small way that made most of the code independent of the assets, but this should improve matters a lot. Please reopen if it's still too much rebuilding.
