### ISSUE TITLE
Libgl.so:No such file or directory while building Python interface for DeepMind Lab with OpenGL

### ISSUE THREAD

**Issue by ekta2391** [deepmind/lab#57]
I am using the following for setting up DeepMind Lab environment:
Ubuntu 14.04
JDK 8 
Bazel 
OpenGL 4.5

While building a Python interface for DeepMind Lab with OpenGL using the following command:

```
# Build the Python interface to DeepMind Lab with OpenGL
lab$ bazel build :deepmind_lab.so --define headless=glx
```

The following error is displayed:

![image](https://cloud.githubusercontent.com/assets/25309341/24631146/4d3e5496-188d-11e7-849a-5b37c2cf1f85.png)

Error: `Linking of rule '//:libdmlab.so' failed: Process exited with status 1 [sandboxed].`
`usr/bin/ld.gold: error cannot open usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libGL.so: No such file or directory`

Any help is appreciated

**Comment by vasantivmahajan** [comment]
I am facing the same issue. Did someone face a similar issue and were able to resolve it?

**Comment by anshulkatta** [comment]
did you guys really know linux very well ? its clearly saying it is not able to find the required file or dir..noobs :/
