### ISSUE TITLE
Head required in headless mode?

### ISSUE THREAD

**Issue by sygi** [deepmind/lab#59]
Is is possible to run lab in headless mode with GPU acceleration? I have tried:
```
$ bazel run :python_module_test --define headless=glx
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
Target //:python_module_test up-to-date:
  bazel-bin/python_module_test
INFO: Elapsed time: 0.178s, Critical Path: 0.00s

INFO: Running command line: bazel-bin/python_module_test
...Unable to init server: Could not connect: Connection refused

(zenity:23982): Gtk-WARNING **: cannot open display: 
ERROR: Non-zero return code '3' from command: Process exited with status 3.
```

**Comment by tkoeppe** [comment]
You don't need a head, but you need X, because GLX requires X. If there existed some other OpenGL implementation that didn't require X, we could avoid that :-)

**Comment by sygi** [comment]
Thank you for the information. Could you advise me what would be the best (faster) option between:
- emulating screen using xvfb and running through headless=glx
- running headless=osmesa
assuming I have a reasonable GPU (titan X) available?

**Comment by sygi** [comment]
Closing the issue, as the behavior is expected. Thank you for your help.
