### ISSUE TITLE
Hitting static TLS limit

### ISSUE THREAD

**Issue by sygi** [deepmind/lab#61]
I have successfully managed build lab and run the tests. But, when I try to run more involved code (namely [unreal](https://github.com/miyosuda/unreal)), I am getting an error:
```
Failed to open library! - ./libdmlab.so
dlopen: cannot load any more object with static TLS
Process Process-1:
Traceback (most recent call last):
  File "/part/01/Tmp/lisa/os_v5/anaconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/part/01/Tmp/lisa/os_v5/anaconda/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data/lisa/exp/sygnowsj/lab/unreal/environment/lab_environment.py", line 26, in worker
    'height': str(84)
RuntimeError: Failed to connect RL API
```
when creating the environment.

I am not an OS guru, but as far as I understand it is connected with the way shared libraries are linked within Lab. I wonder -- is it possible to force lab to use dynamic TLS for some libraries? If not, can I resolve the problem in another way? Unfortunately I cannot upgrade glibc to a version with higher DTV_SURPLUS (my version is Debian GLIBC 2.19-18+deb8u7). Thank you :)

**Comment by tkoeppe** [comment]
Could you perhaps try and link against a build of Mesa without TLS? You can disable TLS in Mesa at compile time.

**Comment by sygi** [comment]
Which library/options exactly do you mean? I have installed `libosmesa-dev`. From the [Mesa](https://www.mesa3d.org/intro.html) page it seems to me that TLS is disabled by default.

**Comment by tkoeppe** [comment]
Yes, indeed, you would need to rebuild it from source and change the TLS setting.

**Comment by sygi** [comment]
Ok, I managed to rebuild mesa without tls. Thank you for your guidance. Closing the issue.
