### ISSUE TITLE
Problem with Bazel when building on Ubuntu16.04

### ISSUE THREAD

**Issue by samuelzhouhe** [deepmind/lab#64]
I am running on Ubuntu 16.04 with bazel version 0.5.0 and gcc version 5.4.0
After installing all the dependencies (their dev version), I ran the following command:
```
bazel build :deepmind_lab.so --define headless=glx --verbose_failures
```

But I get the following
```
INFO: Found 1 target...
ERROR: /home/ck1/.cache/bazel/_bazel_ck1/19107686c8303e50a184911018ad8663/external/zlib_archive/BUILD.bazel:5:1: C++ compilation of rule '@zlib_archive//:zlib' failed: gcc failed: error executing command 
  (exec env - \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -MD -MF bazel-out/local-fastbuild/bin/external/zlib_archive/_objs/zlib/external/zlib_archive/gzclose.pic.d -fPIC -iquote external/zlib_archive -iquote bazel-out/local-fastbuild/genfiles/external/zlib_archive -iquote external/bazel_tools -iquote bazel-out/local-fastbuild/genfiles/external/bazel_tools -isystem external/zlib_archive -isystem bazel-out/local-fastbuild/genfiles/external/zlib_archive -isystem external/bazel_tools/tools/cpp/gcc3 -Wno-implicit-function-declaration -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/zlib_archive/gzclose.c -o bazel-out/local-fastbuild/bin/external/zlib_archive/_objs/zlib/external/zlib_archive/gzclose.pic.o)

Use --sandbox_debug to see verbose messages from the sandbox.
src/main/tools/linux-sandbox-pid1.cc:193: "mount(/tmp, /tmp, NULL, MS_BIND, NULL)": Invalid argument
Use --strategy=CppCompile=standalone to disable sandboxing for the failing actions.
Target //:deepmind_lab.so failed to build
INFO: Elapsed time: 0.281s, Critical Path: 0.06s
```

I am getting stuck on this, can anyone offer some help? Any help would be highly appreciated!

**Comment by samuelzhouhe** [comment]
Update: sometimes it gets the above error message, sometimes it gets the following one:
```
INFO: Found 1 target...
ERROR: /home/ck1/.cache/bazel/_bazel_ck1/19107686c8303e50a184911018ad8663/external/jpeg_archive/BUILD.bazel:74:1: Executing genrule @jpeg_archive//:configure failed: bash failed: error executing command 
  (exec env - \
    LD_LIBRARY_PATH='/usr/local/cuda-8.0/lib64${LD_LIBRARY_PATH:+:}' \
    PATH=/usr/local/cuda-8.0/bin:/home/ck1/bin:/home/ck1/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; cat <<EOF >bazel-out/local-fastbuild/genfiles/external/jpeg_archive/jconfig.h
#define HAVE_PROTOTYPES 1
#define HAVE_UNSIGNED_CHAR 1
#define HAVE_UNSIGNED_SHORT 1
#define HAVE_STDDEF_H 1
#define HAVE_STDLIB_H 1
#ifdef WIN32
#define INLINE __inline
#else
#define INLINE __inline__
#endif
EOF
')

Use --sandbox_debug to see verbose messages from the sandbox.
src/main/tools/linux-sandbox-pid1.cc:193: "mount(/tmp, /tmp, NULL, MS_BIND, NULL)": Invalid argument
Use --strategy=Genrule=standalone to disable sandboxing for the failing actions.
Target //:deepmind_lab.so failed to build
INFO: Elapsed time: 0.266s, Critical Path: 0.07s
```

I am really confused on this, could anyone offer help? Thanks so much.

**Comment by bodgergely** [comment]
Check the contents of /home/ck1/.cache/bazel/_bazel_ck1/19107686c8303e50a184911018ad8663/external/zlib_archive/BUILD.bazel. It lists the source files to compile and build of zlib.  Also note that for me external/zlib_archive/BUILD.bazel is a link:
 BUILD.bazel -> /home/geri/workspace/tensorflow/third_party/zlib.BUILD

Do you have tensorflow installed?

Also check the contents of the folder /home/ck1/.cache/bazel/_bazel_ck1/19107686c8303e50a184911018ad8663/external/zlib_archive
and see if the source files of zlib are present.

Greg

**Comment by dhfromkorea** [comment]
Hi, I guess I am suffering from the same INVALID ARGUMENT issue:
INFO: Found 1 target...
ERROR: /home/dhfromkorea/.cache/bazel/_bazel_dhfromkorea/e3cee545b23a7b65a3985039622e146c/external/zlib_archive/BUILD.bazel:5:1: C++ compilation of rule '@zlib_archive//:zlib' failed: gcc failed: error executing command
  (exec env - \
    LD_LIBRARY_PATH=/usr/lib/nvidia-375 \
    PATH=/usr/local/cuda-8.0/bin:/home/dhfromkorea/bin/miniconda3/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -g0 -MD -MF bazel-out/host/bin/external/zlib_archive/_objs/zlib/external/zlib_archive/trees.d -iquote external/zlib_archive -iquote bazel-out/host/genfiles/external/zlib_archive -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -isystem external/zlib_archive -isystem bazel-out/host/genfiles/external/zlib_archive -isystem external/bazel_tools/tools/cpp/gcc3 -Wno-implicit-function-declaration -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/zlib_archive/trees.c -o bazel-out/host/bin/external/zlib_archive/_objs/zlib/external/zlib_archive/trees.o)

Use --sandbox_debug to see verbose messages from the sandbox.
src/main/tools/linux-sandbox-pid1.cc:193: "mount(/tmp, /tmp, NULL, MS_BIND, NULL)": Invalid argument
Use --strategy=CppCompile=standalone to disable sandboxing for the failing actions.
Target //:deepmind_lab.so failed to build
INFO: Elapsed time: 0.291s, Critical Path: 0.09s

1) I do have tensorflow working. 
2) it seems BUILD.bazel lists the source files of zlib correctly:

➜  zlib_archive cat BUILD.bazel
package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # BSD/MIT-like license (for zlib)

cc_library(
    name = "zlib",
    srcs = [
        "adler32.c",
        "compress.c",
        "crc32.c",
        "crc32.h",
        "deflate.c",
        "deflate.h",
        "gzclose.c",
        "gzguts.h",
        "gzlib.c",
        "gzread.c",
        "gzwrite.c",
        "infback.c",
        "inffast.c",
        "inffast.h",
        "inffixed.h",
        "inflate.c",
        "inflate.h",
        "inftrees.c",
        "inftrees.h",
        "trees.c",
        "trees.h",
        "uncompr.c",
        "zconf.h",
        "zutil.c",
        "zutil.h",
    ],
    hdrs = ["zlib.h"],
    copts = ["-Wno-implicit-function-declaration"],
    includes = ["."],
)

any enlightening comments would be deeply appreciated!

**Comment by tkoeppe** [comment]
Are you on some sort of VM? Can you try on a "normal" machine to make sure this isn't some environmental restriction?

**Comment by tkoeppe** [comment]
There's a Travis test now that demonstrates how to build and test this on Ubuntu 14.
