### ISSUE TITLE
How to create procedurally generated levels

### ISSUE THREAD

**Issue by hirotodate** [deepmind/lab#67]
I'm doing some experiments to reproduce the results in "Reinforcement Learning with Unsupervised Auxiliary Tasks."
https://arxiv.org/abs/1611.05397

Does anyone know how to create procedurally generated levels (e.g. nav_maze_all_random 0{1, 2, 3} in the paper)?
In the settings, a new maze (new geometry, textures, goal, and start) should be generated on-the-fly at the start of each episode.

**Comment by DjAntaki** [comment]
Hey! I'm facing problems trying to do procedurally generated levels. I just posted an issue here https://github.com/deepmind/lab/issues/73 .

Have you been successful in your endeavor? If so, may you share some insight with me? 

Thanks.

**Comment by hirotodate** [comment]
Hi, I haven't solved this problem, but the solution in your post looks nice.
I'll try something around it, and let you know if solved.

**Comment by tkoeppe** [comment]
The nav_maze levels were generated with different tools. Note that the Quake3 `.map` format is standard and many tools exist to create maps, so you can take your pick. The built-in "text level" API is fairly simple and can only generate rectangular mazes with "thick" walls.
