### ISSUE TITLE
Top Down View

### ISSUE THREAD

**Issue by shurjobanerjee** [deepmind/lab#68]
Does anyone know how to generate top down perspectives for the maps? I'd like to be able to replicate the top down perspectives from the "Reinforcement Learning with Unsupervised Auxiliary Tasks" paper (https://arxiv.org/pdf/1611.05397.pdf).

**Comment by meteozay** [comment]
Hello,

Similar to that question, I would like to ask how to obtain and visualize layouts of environments from top-down view while reproducing the results given also in the paper "Learning to Navigate in Complex Environments".

Thank you.

Mete

**Comment by charlesbeattie** [comment]
Hi Mete,
I'm afraid we used different tools to produce these videos and the functionality is not currently available.

**Comment by tuitikki** [comment]
In an updated version of the Lab, there is an observation called DEBUG.CAMERA.TOP_DOWN. Would that be the top down view? I tried to retrieve this observation, but unfortunately I didn't manage to save it as an image.

**Comment by charlesbeattie** [comment]
Yes and it is only available to environments that have the custom observation decorator and have informed the camera where to be. ByteTensor format would be 3xHeightxWidth. We may release an Interleaved variation at some point.
