### ISSUE TITLE
bazel fetch (and build) fails on OSX with "no such package '@glib_archive//'"

### ISSUE THREAD

**Issue by machinaut** [deepmind/lab#7]
Doing all this over NIPS conference wifi has been a bit of a ride, but I was able get a setup where all the external dependencies can be pulled reliably (by rehosting them locally).

Trying to just make sure I have all the prerequisites for lab, I'm running `bazel fetch :game`.  Output:

```
$> bazel fetch :game
Extracting Bazel installation...
............
ERROR: /Users/a/code/deepmind-lab/q3map2/BUILD:54:1: no such package '@glib_archive//': Error creating symbolic link from /private/var/tmp/_bazel_a/160592a534b1347832993df9677151a1/external/glib_archive/BUILD to /Users/a/code/deepmind-lab/glib.BUILD: /private/var/tmp/_bazel_a/160592a534b1347832993df9677151a1/external/glib_archive/BUILD (Directory not empty) and referenced by '//q3map2:q3map2'.
ERROR: /Users/a/code/deepmind-lab/q3map2/BUILD:54:1: no such package '@glib_archive//': Error creating symbolic link from /private/var/tmp/_bazel_a/160592a534b1347832993df9677151a1/external/glib_archive/BUILD to /Users/a/code/deepmind-lab/glib.BUILD: /private/var/tmp/_bazel_a/160592a534b1347832993df9677151a1/external/glib_archive/BUILD (Directory not empty) and referenced by '//q3map2:q3map2'.
ERROR: Evaluation of query "deps((:game union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.
```

Might be an issue with bazel on Mac, but want to make sure it's not something obvious I'm missing.

Thanks.

**Comment by machinaut** [comment]
Argh.  I'm pretty sure this is a case-insensitive filesystem issue.

Notably, the symlink it's trying to make (`BUILD`) fails because a directory called `build` already exists.  Trying again with a case-sensitive filesystem.

**Comment by heiner** [comment]
Unfortunately, DeepMind Lab doesn't support OSX at the moment.

Feel free to reach out to me here at NIPS if you have questions about DeepMind Lab. :)
