### ISSUE TITLE
ubuntu 17.04, python 3.5 anaconda, error building bazel build :deepmind_lab.so --define headless=glx                #error GNU libiconv not in use but included iconv.h is from libiconv 

### ISSUE THREAD

**Issue by stjordanis** [deepmind/lab#72]
I get this error when running
bazel build :deepmind_lab.so --define headless=glx --verbose_failures --sandbox_debug

src/main/tools/process-tools.cc:114: sigaction(32, &sa, nullptr) failed
src/main/tools/process-tools.cc:114: sigaction(33, &sa, nullptr) failed
external/glib_archive/glib/gconvert.c:61:2: error: #error GNU libiconv not in use but included iconv.h is from libiconv
 #error GNU libiconv not in use but included iconv.h is from libiconv
  ^
src/main/tools/linux-sandbox-pid1.cc:431: waitpid returned 2
src/main/tools/linux-sandbox-pid1.cc:451: child exited with code 1
src/main/tools/linux-sandbox.cc:193: child exited normally with exitcode 1
Target //:deepmind_lab.so failed to build

Full console log:

INFO: Analysed target //:deepmind_lab.so (0 packages loaded).
INFO: Found 1 target...
ERROR: /home/steliox/.cache/bazel/_bazel_steliox/b504cf183bd37639d6004ec3080c902c/external/glib_archive/BUILD.bazel:35:1: C++ compilation of rule '@glib_archive//:glib' failed (Exit 1): linux-sandbox failed: error executing command 
  (cd /home/steliox/.cache/bazel/_bazel_steliox/b504cf183bd37639d6004ec3080c902c/execroot/org_deepmind_lab && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/cuda/lib:/home/steliox/torch-cl/install/lib:/home/steliox/.deepforge/torch/install/lib:/home/steliox/CNTK/libs:/usr/local/mpi/lib:/usr/local/lib:/home/steliox/cntk/libs:/home/steliox/torch-cl/install/lib:/home/steliox/.deepforge/torch/install/lib: \
    PATH='/home/steliox/anaconda2/envs/conda-35/bin:/usr/local/cuda/bin:/home/steliox/torch-cl/install/bin:/home/steliox/.deepforge/torch/install/bin:/home/steliox/.nvm/versions/node/v6.2.1/bin:/home/steliox/caffe/python:/home/steliox/swig-3.0.10/root:/usr/local/mpi/bin:/home/steliox/anaconda2/bin:/home/steliox/torch-cl/install/bin:/home/steliox/.deepforge/torch/install/bin:/home/steliox/bin:/home/steliox/.local/bin:/home/steliox/pycharm-community-2017.2.1/bin:/usr/local/mpi/bin:/usr/local/lib:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/jdk1.8.0_112/bin:$HOME/cntk/bindings/python:/usr/local/lib::/snap/bin:/usr/bin:/snap/bin' \
    PWD=/proc/self/cwd \
  /home/steliox/.cache/bazel/_bazel_steliox/b504cf183bd37639d6004ec3080c902c/execroot/org_deepmind_lab/_bin/linux-sandbox -D -t 15 -w /home/steliox/.cache/bazel/_bazel_steliox/b504cf183bd37639d6004ec3080c902c/bazel-sandbox/4555332035472693242/execroot/org_deepmind_lab -w /dev/shm -w /tmp -- /home/steliox/anaconda2/envs/conda-35/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/home/steliox/anaconda2/envs/conda-35/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -g0 -MD -MF bazel-out/host/bin/external/glib_archive/_objs/glib/external/glib_archive/glib/gconvert.d -iquote external/glib_archive -iquote bazel-out/host/genfiles/external/glib_archive -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -isystem external/glib_archive -isystem bazel-out/host/genfiles/external/glib_archive -isystem external/bazel_tools/tools/cpp/gcc3 -Iexternal/glib_archive/glib -DGLIB_COMPILATION -DG_DISABLE_CAST_CHECKS '-DG_LOG_DOMAIN="GLib"' -DHAVE_CONFIG_H -DPCRE_STATIC -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/glib_archive/glib/gconvert.c -o bazel-out/host/bin/external/glib_archive/_objs/glib/external/glib_archive/glib/gconvert.o)
src/main/tools/linux-sandbox.cc:153: linux-sandbox-pid1 has PID 24832
src/main/tools/linux-sandbox-pid1.cc:169: working dir: /home/steliox/.cache/bazel/_bazel_steliox/b504cf183bd37639d6004ec3080c902c/bazel-sandbox/4555332035472693242/execroot/org_deepmind_lab
src/main/tools/linux-sandbox-pid1.cc:188: writable: /home/steliox/.cache/bazel/_bazel_steliox/b504cf183bd37639d6004ec3080c902c/bazel-sandbox/4555332035472693242/execroot/org_deepmind_lab
src/main/tools/linux-sandbox-pid1.cc:188: writable: /dev/shm
src/main/tools/linux-sandbox-pid1.cc:188: writable: /tmp
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /dev
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /dev/pts
src/main/tools/linux-sandbox-pid1.cc:259: remount rw: /dev/shm
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /dev/mqueue
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /dev/hugepages
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /run
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /run/lock
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /run/user/1000
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /run/user/1000/gvfs
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /run/snapd/ns
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /run/docker/netns/194846295f79
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /run/docker/netns/acd52c0fd7f5
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /run/docker/netns/299233d1f038
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /run/docker/netns/129d278ddd2a
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /run/docker/netns/33c671e55e7f
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /run/docker/netns/676170ce0ac4
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /run/docker/netns/66e0db8a6eca
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /sys
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /sys/kernel/security
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /sys/fs/cgroup
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /sys/fs/cgroup/systemd
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /sys/fs/cgroup/pids
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /sys/fs/cgroup/net_cls,net_prio
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /sys/fs/cgroup/devices
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /sys/fs/cgroup/freezer
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /sys/fs/cgroup/perf_event
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /sys/fs/cgroup/cpuset
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /sys/fs/cgroup/blkio
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /sys/fs/cgroup/cpu,cpuacct
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /sys/fs/cgroup/hugetlb
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /sys/fs/cgroup/memory
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /sys/fs/pstore
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /sys/kernel/debug
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /sys/fs/fuse/connections
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /proc
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /proc/sys/fs/binfmt_misc
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /proc/sys/fs/binfmt_misc
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /snap/dash-shell/7
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /snap/canonical-livepatch/22
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /snap/canonical-livepatch/21
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /snap/core/2381
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /snap/core/2462
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /snap/core/2774
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /media/Recovery
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /media/steliox/01D0678206E0CE70
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /media/steliox/148A89C98A89A7B6
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /media/download
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /media/apple
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /media/steliox/linux
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /media/steliox/WIN
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /var/lib/docker/aufs
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /var/lib/docker/aufs/mnt/5a1aabcce3e6458d8d4ae4cb985fac36530de3b7ba2d7f8068143397d759bbdb
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /var/lib/docker/aufs/mnt/6a51f074d53d043913797bc597202f385ed4147f4bdd51c05d6fba27ca4e57da
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /var/lib/docker/aufs/mnt/e3ae22cbfc6f822a5cee4cf2198fa7b61048bbde5643e0e838c7012e3e35b021
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /var/lib/docker/aufs/mnt/ae3ed7cb32b98aca27dc34347b7c45bc02a32f9e6bed3dd3800684772f08393c
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /var/lib/docker/aufs/mnt/9e6fefce0de84880ff882a69ee2767cd2eb02eb39e41c377d2deae5f9bb86d1d
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /var/lib/docker/aufs/mnt/2f16279f284581fc4ffda6e0ddfae9439eeae6ef48f0dceeab02bbb6ce9d04e4
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /var/lib/docker/aufs/mnt/9ce5436e3ac3a6f62e8f7ed0e4d8a391232c5e0925220c88d98027b91c3918dc
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /var/lib/docker/containers/87d02a2a3f62484c31fb71833ff14c144fb776f54482ea49d0c798fe3600c42b/shm
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /var/lib/docker/containers/77f878fd6f66880f56be0c89fb73bc609e6937700b220d7cdc7402d61422033a/shm
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /var/lib/docker/containers/cd520f1fd6dfde1526220a535566d64e36802c465938883180ad912e9b00ec48/shm
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /var/lib/docker/containers/3fb1fe0315245559e97fba334252e90afe2ecbfeb2e5980797d0143de4369f47/shm
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /var/lib/docker/containers/b5652cfd2f1df207ea1c8e5e348a663dcddd576fbc9fb72df64bdae300112ab7/shm
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /var/lib/docker/containers/8e00a4e0fe5b8b131da50f56ff31ac785b6dd5989f33b47ff6202265ee44e67c/shm
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /var/lib/docker/containers/a13360ac0ae7e02252f0657b1565431b0e0553fc9e0aee491f1daa2b6197ab27/shm
src/main/tools/linux-sandbox-pid1.cc:259: remount ro: /snap/canonical-livepatch/25
src/main/tools/linux-sandbox-pid1.cc:259: remount rw: /home/steliox/.cache/bazel/_bazel_steliox/b504cf183bd37639d6004ec3080c902c/bazel-sandbox/4555332035472693242/execroot/org_deepmind_lab
src/main/tools/linux-sandbox-pid1.cc:259: remount rw: /home/steliox/.cache/bazel/_bazel_steliox/b504cf183bd37639d6004ec3080c902c/bazel-sandbox/4555332035472693242/execroot/org_deepmind_lab
src/main/tools/linux-sandbox-pid1.cc:259: remount rw: /dev/shm
src/main/tools/linux-sandbox-pid1.cc:259: remount rw: /tmp
src/main/tools/process-tools.cc:114: sigaction(32, &sa, nullptr) failed
src/main/tools/process-tools.cc:114: sigaction(33, &sa, nullptr) failed
external/glib_archive/glib/gconvert.c:61:2: error: #error GNU libiconv not in use but included iconv.h is from libiconv
 #error GNU libiconv not in use but included iconv.h is from libiconv
  ^
src/main/tools/linux-sandbox-pid1.cc:431: waitpid returned 2
src/main/tools/linux-sandbox-pid1.cc:451: child exited with code 1
src/main/tools/linux-sandbox.cc:193: child exited normally with exitcode 1
Target //:deepmind_lab.so failed to build
INFO: Elapsed time: 0.387s, Critical Path: 0.14s
FAILED: Build did NOT complete successfully

**Comment by superMDguy** [comment]
This project doesn't officially support Python 3, which might be causing some of your issues. I don't know if it will fix the libiconv error, but you could try my [fork](https://github.com/superMDguy/lab) which has a Python 3 build target.

**Comment by tkoeppe** [comment]
Yes, we don't support and test Python 3 at the moment. It's possible you can figure out how to get it to work, but I'm afraid we can't help with that just now.
