### ISSUE TITLE
Game script undetected

### ISSUE THREAD

**Issue by DjAntaki** [deepmind/lab#73]
Hello!

With inspiration drawn from the random maze script, I have written my own map and level factory. 
I've place them respectively at "assets/game_scripts/testmap.lua" and "assets/game_scripts/factories/testfactory.lua" .

I tried to run my own python script and the random_agent.py with the flag "--level_script testmap" (and I have also the "headless=false" flag for both script).  Both time, I've ended up in the menu and unable to start a game.

At this point, I'm assuming that the map wasn't found by the python script and that creating the lua file in the game script folder was insufficient to add it to the set of available map. I seem to be missing a step here and I can't find what I'm missing in the documentation.

Any help would be much appreciated.
Thanks.

**Comment by tkoeppe** [comment]
Did you rebuild the relevant binaries or libraries? If you want to locate the file just by its basename ("testscript"), then it needs to be packaged into a PK3, which requires rebuilding (it'll only rebuild the assets part).

I think you can also specify a script as filename, but then you need to include its path.

**Comment by DjAntaki** [comment]
I tried calling again "bazel build" from the root directory before using the previous command. I also tried to put the full path with the level script flag. Both do not work.  To simplify the problem, I just made a copy of nav_maze_random_goal_01.lua under a different name. It does not seem to generate a pk3 file.

**Comment by charlesbeattie** [comment]
Hi the maps referenced by 'nav_maze_random_goal_01.lua' is not procedurally generated and retrieved from the assets/maps folder.
