### ISSUE TITLE
Disable animation

### ISSUE THREAD

**Issue by iordachelivia** [deepmind/lab#75]
Hello!
How can i disable all animation? (apple bopping up and down and rotating, shadows on walls/floor)

**Comment by iordachelivia** [comment]
I managed to stop the shine on the walls. However, the apples keep bobbing

**Comment by charlesbeattie** [comment]
Sorry I hadn't realised that code has not been released yet.
We edit the code around line code/cgame/cg_ents.c 261
This snippet makes the static placement match the center of the bob:

    cent->lerpOrigin[2] += 4;
    AnglesToAxis( es->angles, ent.axis );

**Comment by iordachelivia** [comment]
Thank you
