### ISSUE TITLE
Collision Detection

### ISSUE THREAD

**Issue by TheTazza** [deepmind/lab#78]
Does anyone know if there is, or how to implement collision detection?

I was wondering if there is any way to receive feedback from the environment about wall collision to penalize the agent for hitting the wall.

I couldn't find any clues in the code or online about it, but I'd think that it could be an important feedback method to accelerate training.

**Comment by charlesbeattie** [comment]
There is a new function in the latest release called raycast. This combined with the player location may be able to help.

**Comment by tangbohu** [comment]
But how can I use raycast to detect collision? 

Could I get the information of walls, thus I can know the distance between the robot and the wall.
