### ISSUE TITLE
ERROR: Build failed. Not running target.

### ISSUE THREAD

**Issue by iGamingMango** [deepmind/lab#79]
I need some help, 99% sure it's me but I have no idea how to fix it. I am stuck on a build fail error, the message says "Auto-Configuration Error: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC                                                                  \\VCVARSALL.BAT doesn't exist, please check your VC++ installation"

How can I fix this, I am pretty sure I have got this file since I installed all C++ addons twice for VC to try and fix this (although I did avoid downloading the larger packages). 

I just need to know is there a way to fix this without downloading about 10GB worth of files? I have looked where they should be and I found VCVARSALL140 but it doesn't seem to work. f I only have to download a few files to make it work, please point me in the right direction, too. Thanks!

**Comment by tkoeppe** [comment]
I'm afraid we don't support Windows. Several external dependencies require a Posix environment for `./configure`-style configuration, and I have no idea if those could be ported to Windows at all (e.g. `glib`).

**Comment by iGamingMango** [comment]
Recently got Ubuntu for Windows 10 (Officially supported by Microsoft), getting a similar error with a missing command, I am pretty sure I installed all the dependencies. Is there anything I am missing?

Error log:
"/lab/BUILD:699:1: Executing genrule //:assets_oa_pk3 failed (Exit 1)
/bin/bash: zip: command not found
Target //:random_agent failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.473s, Critical Path: 0.19s
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target"

**Comment by tkoeppe** [comment]
It sounds like you need to install a `zip` binary on your system. Try `apt-get install zip`.

**Comment by tkoeppe** [comment]
Have you made any progress on this?

**Comment by codeisnotcode** [comment]
I had a similar error to iGamingMango. Adding sudo in front made it work for me. Check your permissions on executable files.
sudo bazel run :game -- --level_script=tests/empty_room_test  --level_setting=logToStdErr=true

**Comment by tkoeppe** [comment]
Yikes, you should never run anything under `sudo` (other than one-off system setup).

**Comment by tkoeppe** [comment]
Please reopen if the problem still persists.
