### ISSUE TITLE
Build Error - Executing genrule //:map_assets

### ISSUE THREAD

**Issue by gheyhardy** [deepmind/lab#81]
I am attempting to run the tests on the build page and I get stuck on this "Executing genrule //:map_assets" part with no feedback from --verbose_failures. I am able to run random_agent from the 
/bazel-bin/random_agent.runfiles/org_deepmind_lab directory but I can't get any of the tests to run.

> $ bazel run :random_agent --verbose_failures --define headless=glx
> 
>INFO: Analysed target //:random_agent (0 packages loaded).
>INFO: Found 1 target...
>[982 / 983] Executing genrule //:map_assets; 14s linux-sandbox
>Bazel caught interrupt signal; shutting down.
>Target //:random_agent failed to build
>ERROR: build interrupted
>INFO: Elapsed time: 15.052s, Critical Path: 14.50s
>FAILED: Build did NOT complete successfully
>ERROR: Build failed. Not running target

**Comment by tkoeppe** [comment]
It looks like someone pressed Ctrl-C?

**Comment by gheyhardy** [comment]
Yes, it will run indefinitely on that step with no feedback.

**Comment by tkoeppe** [comment]
How long did you wait? The asset generation takes about 10 minutes.

**Comment by gheyhardy** [comment]
Got it, I did run it longer than 10sec but I closed it before then because I couldnt tell if it was hanging without any output. It is working now.

**Comment by tkoeppe** [comment]
Yes, 10 min is a bit longer than 10 sec :-) Glad it's working. You can use `top` to see if a process is busy, by the way.
