### ISSUE TITLE
Error: undefined reference to 'g_str_to_ascii'

### ISSUE THREAD

**Issue by ConorYatesKoch** [deepmind/lab#82]
The full terminal output is as follows:
`INFO: Analysed target //:random_agent (0 packages loaded).`
`INFO: Found 1 target...`
`ERROR: /home/user/Documents/School/lab/q3map2/BUILD:54:1: Linking of rule '//q3map2:q3map2' failed (Exit 1)`
`bazel-out/k8-fastbuild/bin/external/glib_archive/_objs/glib/external/glib_archive/glib/gstrfuncs.pic.o:gstrfuncs.c:function g_str_tokenize_and_fold: error: undefined reference to 'g_str_to_ascii'`
`collect2: error: ld returned 1 exit status`
`Target //:random_agent failed to build`
`Use --verbose_failures to see the command lines of failed build steps.`
`INFO: Elapsed time: 0.505s, Critical Path: 0.26s`
`FAILED: Build did NOT complete successfully`
`ERROR: Build failed. Not running target`

I have installed Bazel according to their instructions. I have installed Deepmind Lab according to their instructions.

I receive this error when attempting to execute:
`bazel run :random_agent --define headless=false -- \ --length = 10000 --width=640 --height=640`

I am running:

- Ubuntu 16.0.4
- Python 2.7.12 (with dev)
- Bazel 0.9.0
- Lua 5.1.5 (with dev)

I have `libglib2.0-0` and `libglib2.0-dev` installed as well.

Let me know if you have any other questions. Thank you for your help.

**Comment by tkoeppe** [comment]
Ah, I forgot that when updating glib. There's a `.c` file that needs to be added to the glib sources in `glib.BUILD`. Could you perhaps kindly figure out which files need to be added, and I'll make a fix?

**Comment by ConorYatesKoch** [comment]
The error is in `gstrfuncs.c`, but that is present. 

Could you maybe point me in the direction of some potential files that might need to be included, so that I could work with them? I'm not terribly proficient with Ubuntu. I've got `glib.BUILD` open, but I'm not not sure where to even begin searching for missing `.c` files.

**Comment by tkoeppe** [comment]
You shouldn't need to install libglib, since we download it as part of the Bazel workspace.

You need to add to the `srcs` field of the `"glib"` rule in `glib.BUILD`:

    "glib/gtranslit.c",
    "glib/gtranslit-data.h",

I see now why I didn't spot this: i only built in optimized mode (`bazel build -c opt`), and the code appears to be dead, so it got stripped out by the optimizer. In unoptimized builds I do indeed see the linker error.

I'll push a fix.

**Comment by ConorYatesKoch** [comment]
Thank you, this worked!

**Comment by tkoeppe** [comment]
No worries, thanks for reporting it! I should really run tests more carefully :-)
