### ISSUE TITLE
Changing Reward Values

### ISSUE THREAD

**Issue by ConorYatesKoch** [deepmind/lab#84]
I'm interested in changing the value of the rewards of certain actions. Where would be best to look in the code for this?

**Comment by charlesbeattie** [comment]
For pickups the reward is set by adjusting the count in the spawnVars. See:

https://github.com/deepmind/lab/blob/832c50ee2a80b8b1e4a15fd60d1f8c1b7774c8ea/game_scripts/levels/tests/extra_entities_test.lua#L60

Other reward events can be overridden via the `api:rewardOverride(kwargs)` callback. See:

https://github.com/deepmind/lab/blob/master/docs/developers/reference/lua_api.md#rewardoverridekwargs---int-or-nil

**Comment by ConorYatesKoch** [comment]
Thank you!
