### ISSUE TITLE
Error with python_module_test

### ISSUE THREAD

**Issue by xianlopez** [deepmind/lab#85]
Hi.

I am following the instruction of https://github.com/deepmind/lab/blob/master/docs/users/build.md for Ubuntu. I successfuly ran the command
`lab$ bazel build :deepmind_lab.so`
but get an error on the next step,
`lab$ bazel run :python_module_test`

The output is:
`ERROR: Skipping ':python_module_test': no such target '//:python_module_test': target 'python_module_test' not declared in package '' defined by /home/xian/lab/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//:python_module_test': target 'python_module_test' not declared in package '' defined by /home/xian/lab/BUILD
INFO: Elapsed time: 1.070s
FAILED: Build did NOT complete successfully (1 packages loaded)
ERROR: Build failed. Not running target
`

I have Ubuntu 16.04 Xenial, gcc 5.4, lua 5.1, bazel 0.10.0

Any help would be welcome!

**Comment by tkoeppe** [comment]
Sorry, the test got moved to `//python/tests:python_module_test`. Fixed by cdace33a537556d1ef7cbffbd1c51522f0dab887.

**Comment by tkoeppe** [comment]
I also noticed that the map that's used by the random agent by default (`demo_map`) has been removed. You can use `empty_map_test` instead. I'll push a change that changes the default soon.
