### ISSUE TITLE
unable to build/run on macos (ln -L and -t options are not present in macos)

### ISSUE THREAD

**Issue by prabhatsharma** [deepmind/lab#87]
bazel run :python_random_agent
INFO: Analysed target //:python_random_agent (2 packages loaded).
INFO: Found 1 target...
ERROR: /Users/prabhsha/projects/rl/lab/BUILD:669:1: Executing genrule //:non_pk3_assets failed (Exit 1)
ln: illegal option -- L
usage: ln [-Ffhinsv] source_file [target_file]
       ln [-Ffhinsv] source_file ... target_dir
       link source_file target_file
Target //:python_random_agent failed to build

**Comment by tkoeppe** [comment]
We don't currently support MacOS. If you can figure out how to get it to work, we'd be curious to hear, but we don't have a test environment for MacOS and can't really support it properly at this time. See also #41.

**Comment by tkoeppe** [comment]
I'm preparing a patch to change those `ln` invocations. Stay tuned.
