### ISSUE TITLE
Stop the animation of the walls

### ISSUE THREAD

**Issue by tangbohu** [deepmind/lab#88]
Hi, I wonder whether I could stop the animation of the walls, as they keep shining all the time.

**Comment by charlesbeattie** [comment]
This is a deliberate effect. The behaviour can be changed, however by editing the shaders found in: "assets/scripts/lab_games.shader"
Take a look here for how to edit: http://toolz.nexuizninjaz.com/shader/
Maybe removing tcGen will help.
