### ISSUE TITLE
 Multi-threading support in headless mode?

### ISSUE THREAD

**Issue by rnunziata** [deepmind/lab#9]
More of a question then an issue: is multi threading supported in headless mode. I tried this is it does not seem to work....locking up.

**Comment by tkoeppe** [comment]
You should be able to instantiate multiple DMLab environments using the C API and the dso loader; you can run each instance in its own thread. The Python bindings currently create a single, global instance instead and don't use the dso loader, so you can only have a single environment there at the moment. (We could modify the Python bindings to use the loader, which is something on our radar that we've thought about implementing.)

Note that it is in general not allowed to interact with a *single* environment from multiple threads concurrently, although it may be possible to do so if you serialize all interactions. (We are calling GL routines to support the migration of threads in the rendering code.)

**Comment by rnunziata** [comment]
Thanks I am using python looking to multi thread like a3c. Thanks

**Comment by tkoeppe** [comment]
Actually, the Python module *is* using the DSO loader. However, we have not tested it for multithreaded use. It would probably be best to use the C API (via `:dmlab_lib`) for your usecase.

**Comment by heiner** [comment]
The testOpenClose() test in python/dmlab_module_test.py opens (and closes) several Lab instances in parallel. If `bazel test :python_module_test` works for you, you should be good to go in terms of the DSO loader.

**Comment by ava6969** [comment]
> `dmlab_lib` please how do i do that. I am building a c++ drl lib, And i need to make my lib support dmlab env, all my other environments run with multithreading but i cant use the regular header file, it says dmlab connect can only be called once per process.

**Comment by tkoeppe** [comment]
@ava6969 Let's discuss that in #218 then.
