### ISSUE TITLE
ERROR: No such package '@jpeg_archive//'

### ISSUE THREAD

**Issue by ConorYatesKoch** [deepmind/lab#91]
I ran the command: ```bazel run :game -- -l tests/empty_room_test -std=logToStdErr=true``` earlier today and it worked just fine.

I tried to run it again about an hour later, and I got this mess of errors:

```shinobu@Shinobu-School-PC:~/Documents/School/lab$ bazel run :game -- -l tests/empty_room_test -s logToStdErr=true
..........
ERROR: /home/shinobu/Documents/School/lab/BUILD:759:1: no such package '@jpeg_archive//': Error downloading [http://www.ijg.org/files/jpegsrc.v9c.tar.gz] to /home/shinobu/.cache/bazel/_bazel_shinobu/25a930f936501475fb349e11d5d39862/external/jpeg_archive/jpegsrc.v9c.tar.gz: Checksum was 650250979303a649e21f87b5ccd02672af1ea6954b911342ea491f351ceb7122 but wanted 39e111cd9da5e72a589b98feeded334bb0e5776511e507e3d811ab25a213a3cd and referenced by '//:game_lib_sdl'
ERROR: Analysis of target '//:game' failed; build aborted: no such package '@jpeg_archive//': Error downloading [http://www.ijg.org/files/jpegsrc.v9c.tar.gz] to /home/shinobu/.cache/bazel/_bazel_shinobu/25a930f936501475fb349e11d5d39862/external/jpeg_archive/jpegsrc.v9c.tar.gz: Checksum was 650250979303a649e21f87b5ccd02672af1ea6954b911342ea491f351ceb7122 but wanted 39e111cd9da5e72a589b98feeded334bb0e5776511e507e3d811ab25a213a3cd
INFO: Elapsed time: 2.905s
FAILED: Build did NOT complete successfully (21 packages loaded)
ERROR: Build failed. Not running target
```

I have tried downloading http://www.ijg.org/files/jpegsrc.v9c.tar.gz from the link directly, and placing it in the file it's asking for, but when I run the command again, bazel deletes the file and re-creates it with the zipped version and throws the same exact errors again.

I have tried ```bazel clean --expunge```. This also does not work.

I am at a loss, please help.

**Comment by tkoeppe** [comment]
The checksum of the file has changed. I'm not sure what's going on, this is the second time this has happened. You can just update the checksum in `WORKSPACE`  to the actual value.

**Comment by ConorYatesKoch** [comment]
This fixed it right up! Thanks!

**Comment by tkoeppe** [comment]
I pushed the change in ed1b8918c1561ff552f6ec42a5c1ef5141de183e. I'm a bit concerned, though, since I don't know what has changed. I'd love to see an old version of the file so we can compare. Last time there was a typo fix.
