### ISSUE TITLE
Training agents in Psychlab

### ISSUE THREAD

**Issue by HaojieYuan** [deepmind/lab#94]
Hi guys,
I tried to reproduce the experiments in paper below
Psychlab: A Psychology Laboratory for Deep Reinforcement Learning Agents. 

We tried to adjust a lot hyper parameters and even modified some game scripts (e.g. skipping central fixation mechanism) using the UNREAL agent  mentioned in the paper. However, the agent either learnt to keep touching one button or do not converge at all.

Anyone tried training any agents on those psychology  experiments?

**Comment by tkoeppe** [comment]
I saw your email, thanks -- let me try to find an answer for you. This is really more a question for the authors of that paper; DMLab is just the environment and we don't really deal with the agent training.

**Comment by tkoeppe** [comment]
The remaining psychlab tasks will be released soon.

**Comment by tkoeppe** [comment]
New tasks in 3d2615fe21fa3abed3dee61544b17518fdd903a4.
