### ISSUE TITLE
Cannot find all Psychlab tasks

### ISSUE THREAD

**Issue by xueeinstein** [deepmind/lab#95]
As mentioned in the Psychlab tech report [https://arxiv.org/abs/1801.08116](https://arxiv.org/abs/1801.08116), there are at least 8 tasks. However, I only found 2 tasks in current codebase.

**Comment by tkoeppe** [comment]
We'll be releasing additional tasks soon.

**Comment by xueeinstein** [comment]
@tkoeppe  Thanks for your reply. I have noticed that a new level is in this repo now. BTW, I really hope  you to fix #44 bug or __add 'up' and 'down' key binding in game mode__ ('right' and 'left' work well). I tried to set key binding in the game setting, but it doesn't work properly.

**Comment by tkoeppe** [comment]
We don't plan to provide up/down bindings, and I think we don't consider #44 a bug. It's just something that doesn't work well with remote heads. You can try running at a lower framerate (`--fps=60`) when you're connected remotely so that the higher latency doesn't cause too large accelerations.

**Comment by charlesbeattie** [comment]
PgDn and Delete work as up/down keybindings.
feel free to edit assets/q3config.cfg
```
bind DEL "+lookdown"
bind PGDN "+lookup"
bind LEFTARROW "+left"
bind RIGHTARROW "+right"
```

**Comment by xueeinstein** [comment]
@charlesbeattie @tkoeppe This is just what I want. Thanks a lot!

**Comment by tkoeppe** [comment]
New tasks in 3d2615fe21fa3abed3dee61544b17518fdd903a4.

**Comment by xueeinstein** [comment]
cool!
