### ISSUE TITLE
how to build using conda?

### ISSUE THREAD

**Issue by zhan0903** [deepmind/lab#98]
when I built deepmind lab in linux(redhat) using conda environment, there was an error "/bin/bash: realpath: command not found". I don't have the root right, so how to install realpath? or how to build it in conda environment? Thanks.

**Comment by tkoeppe** [comment]
Can't you just install stuff as non-root? And set your `PATH` appropriately?

**Comment by tkoeppe** [comment]
(Please reopen with details if the problem remains.)
